// Code generated by wasm2go. DO NOT EDIT.

package spellfix

import (
	_ "embed"
	"encoding/binary"
	"math"
	"math/bits"
	"runtime"
	"unsafe"
)

type Module struct {
	t0               *[]any
	elements         [][]any
	memory           *[]byte
	memImp           Memory
	maxMem           int64
	___stack_pointer *int32
	___memory_base   int32
	___table_base    int32
	_env             Xenv
}

func New(v0 Xenv) *Module {
	m := new(Module)
	m._env = v0
	m.maxMem = 65536
	m.___stack_pointer = v0.X__stack_pointer()
	m.___memory_base = *v0.X__memory_base()
	m.___table_base = *v0.X__table_base()
	m.memImp = v0.Xmemory()
	m.memory = m.memImp.Slice()
	m.t0 = v0.X__indirect_function_table()
	m.elements = [][]any{{m._transliterateSqlFunc, m._editdistSqlFunc, m._phoneticHashSqlFunc, m._scriptCodeSqlFunc, m._editDist3SqlFunc, m._editDist3ConfigDelete, m._local_sqlite3_free, m._spellfix1RowCompare, m._spellfix1Create, m._spellfix1Connect, m._spellfix1BestIndex, m._spellfix1Disconnect, m._spellfix1Destroy, m._spellfix1Open, m._spellfix1Close, m._spellfix1Filter, m._spellfix1Next, m._spellfix1Eof, m._spellfix1Column, m._spellfix1Rowid, m._spellfix1Update, m._spellfix1Rename}}
	copy((*m.t0)[m.___table_base:], m.elements[0])
	m.elements[0] = nil
	copy((*m.memory)[uint32(m.___memory_base):], data[0:4052])
	copy((*m.memory)[uint32(m.___memory_base+i32(4064)):], data[4052:4184])
	if i, ok := any(v0).(interface {
		Init(any)
	}); ok {
		i.Init(m)
	}
	return m
}

type Xenv = interface {
	Xsqlite3_create_function(v0, v1, v2, v3, v4, v5, v6, v7 int32) int32
	Xsqlite3_create_module(v0, v1, v2, v3 int32) int32
	Xsqlite3_malloc64(v0 int64) int32
	Xsqlite3_create_function_v2(v0, v1, v2, v3, v4, v5, v6, v7, v8 int32) int32
	Xsqlite3_free(v0 int32)
	Xsqlite3_vmprintf(v0, v1 int32) int32
	Xsqlite3_value_text(v0 int32) int32
	Xsqlite3_value_bytes(v0 int32) int32
	Xsqlite3_result_error_nomem(v0 int32)
	Xsqlite3_result_text(v0, v1, v2, v3 int32)
	Xsqlite3_result_error_toobig(v0 int32)
	Xsqlite3_result_error(v0, v1, v2 int32)
	Xsqlite3_result_int(v0, v1 int32)
	Xsqlite3_value_int(v0 int32) int32
	Xsqlite3_mprintf(v0, v1 int32) int32
	Xsqlite3_prepare_v2(v0, v1, v2, v3, v4 int32) int32
	Xsqlite3_bind_value(v0, v1, v2 int32) int32
	Xsqlite3_step(v0 int32) int32
	Xsqlite3_bind_text(v0, v1, v2, v3, v4 int32) int32
	Xsqlite3_column_int(v0, v1 int32) int32
	Xsqlite3_column_bytes(v0, v1 int32) int32
	Xsqlite3_column_text(v0, v1 int32) int32
	Xsqlite3_column_int64(v0, v1 int32) int64
	Xsqlite3_reset(v0 int32) int32
	Xsqlite3_finalize(v0 int32) int32
	Xsqlite3_column_value(v0, v1 int32) int32
	Xsqlite3_result_value(v0, v1 int32)
	Xsqlite3_result_null(v0 int32)
	Xsqlite3_value_int64(v0 int32) int64
	Xsqlite3_vtab_on_conflict(v0 int32) int32
	Xsqlite3_stricmp(v0, v1 int32) int32
	Xsqlite3_value_type(v0 int32) int32
	Xsqlite3_last_insert_rowid(v0 int32) int64
	Xsqlite3_vtab_config(v0, v1, v2 int32) int32
	Xsqlite3_declare_vtab(v0, v1 int32) int32
	Xsqlite3_exec(v0, v1, v2, v3, v4 int32) int32
	Xsqlite3_realloc64(v0 int32, v1 int64) int32
	Xsqlite3_prepare(v0, v1, v2, v3, v4 int32) int32
	Xsqlite3_user_data(v0 int32) int32
	Xsqlite3_context_db_handle(v0 int32) int32
	Xsqlite3_result_error_code(v0, v1 int32)
	X__stack_pointer() *int32
	X__memory_base() *int32
	X__table_base() *int32
	Xmemory() Memory
	X__indirect_function_table() *[]any
}
type Memory = interface {
	Slice() *[]byte
	Grow(delta, max int64) int64
}

func (m *Module) _sqlite3_create_function(v0, v1, v2, v3, v4, v5, v6, v7 int32) int32 {
	return m._env.Xsqlite3_create_function(v0, v1, v2, v3, v4, v5, v6, v7)
}
func (m *Module) _sqlite3_create_module(v0, v1, v2, v3 int32) int32 {
	return m._env.Xsqlite3_create_module(v0, v1, v2, v3)
}
func (m *Module) _sqlite3_malloc64(v0 int64) int32 {
	return m._env.Xsqlite3_malloc64(v0)
}
func (m *Module) _sqlite3_create_function_v2(v0, v1, v2, v3, v4, v5, v6, v7, v8 int32) int32 {
	return m._env.Xsqlite3_create_function_v2(v0, v1, v2, v3, v4, v5, v6, v7, v8)
}
func (m *Module) _sqlite3_free(v0 int32) {
	m._env.Xsqlite3_free(v0)
}
func (m *Module) _sqlite3_vmprintf(v0, v1 int32) int32 {
	return m._env.Xsqlite3_vmprintf(v0, v1)
}
func (m *Module) _sqlite3_value_text(v0 int32) int32 {
	return m._env.Xsqlite3_value_text(v0)
}
func (m *Module) _sqlite3_value_bytes(v0 int32) int32 {
	return m._env.Xsqlite3_value_bytes(v0)
}
func (m *Module) _sqlite3_result_error_nomem(v0 int32) {
	m._env.Xsqlite3_result_error_nomem(v0)
}
func (m *Module) _sqlite3_result_text(v0, v1, v2, v3 int32) {
	m._env.Xsqlite3_result_text(v0, v1, v2, v3)
}
func (m *Module) _sqlite3_result_error_toobig(v0 int32) {
	m._env.Xsqlite3_result_error_toobig(v0)
}
func (m *Module) _sqlite3_result_error(v0, v1, v2 int32) {
	m._env.Xsqlite3_result_error(v0, v1, v2)
}
func (m *Module) _sqlite3_result_int(v0, v1 int32) {
	m._env.Xsqlite3_result_int(v0, v1)
}
func (m *Module) _sqlite3_value_int(v0 int32) int32 {
	return m._env.Xsqlite3_value_int(v0)
}
func (m *Module) _sqlite3_mprintf(v0, v1 int32) int32 {
	return m._env.Xsqlite3_mprintf(v0, v1)
}
func (m *Module) _sqlite3_prepare_v2(v0, v1, v2, v3, v4 int32) int32 {
	return m._env.Xsqlite3_prepare_v2(v0, v1, v2, v3, v4)
}
func (m *Module) _sqlite3_bind_value(v0, v1, v2 int32) int32 {
	return m._env.Xsqlite3_bind_value(v0, v1, v2)
}
func (m *Module) _sqlite3_step(v0 int32) int32 {
	return m._env.Xsqlite3_step(v0)
}
func (m *Module) _sqlite3_bind_text(v0, v1, v2, v3, v4 int32) int32 {
	return m._env.Xsqlite3_bind_text(v0, v1, v2, v3, v4)
}
func (m *Module) _sqlite3_column_int(v0, v1 int32) int32 {
	return m._env.Xsqlite3_column_int(v0, v1)
}
func (m *Module) _sqlite3_column_bytes(v0, v1 int32) int32 {
	return m._env.Xsqlite3_column_bytes(v0, v1)
}
func (m *Module) _sqlite3_column_text(v0, v1 int32) int32 {
	return m._env.Xsqlite3_column_text(v0, v1)
}
func (m *Module) _sqlite3_column_int64(v0, v1 int32) int64 {
	return m._env.Xsqlite3_column_int64(v0, v1)
}
func (m *Module) _sqlite3_reset(v0 int32) int32 {
	return m._env.Xsqlite3_reset(v0)
}
func (m *Module) _sqlite3_finalize(v0 int32) int32 {
	return m._env.Xsqlite3_finalize(v0)
}
func (m *Module) _sqlite3_column_value(v0, v1 int32) int32 {
	return m._env.Xsqlite3_column_value(v0, v1)
}
func (m *Module) _sqlite3_result_value(v0, v1 int32) {
	m._env.Xsqlite3_result_value(v0, v1)
}
func (m *Module) _sqlite3_result_null(v0 int32) {
	m._env.Xsqlite3_result_null(v0)
}
func (m *Module) _sqlite3_value_int64(v0 int32) int64 {
	return m._env.Xsqlite3_value_int64(v0)
}
func (m *Module) _sqlite3_vtab_on_conflict(v0 int32) int32 {
	return m._env.Xsqlite3_vtab_on_conflict(v0)
}
func (m *Module) _sqlite3_stricmp(v0, v1 int32) int32 {
	return m._env.Xsqlite3_stricmp(v0, v1)
}
func (m *Module) _sqlite3_value_type(v0 int32) int32 {
	return m._env.Xsqlite3_value_type(v0)
}
func (m *Module) _sqlite3_last_insert_rowid(v0 int32) int64 {
	return m._env.Xsqlite3_last_insert_rowid(v0)
}
func (m *Module) _sqlite3_vtab_config(v0, v1, v2 int32) int32 {
	return m._env.Xsqlite3_vtab_config(v0, v1, v2)
}
func (m *Module) _sqlite3_declare_vtab(v0, v1 int32) int32 {
	return m._env.Xsqlite3_declare_vtab(v0, v1)
}
func (m *Module) _sqlite3_exec(v0, v1, v2, v3, v4 int32) int32 {
	return m._env.Xsqlite3_exec(v0, v1, v2, v3, v4)
}
func (m *Module) _sqlite3_realloc64(v0 int32, v1 int64) int32 {
	return m._env.Xsqlite3_realloc64(v0, v1)
}
func (m *Module) _sqlite3_prepare(v0, v1, v2, v3, v4 int32) int32 {
	return m._env.Xsqlite3_prepare(v0, v1, v2, v3, v4)
}
func (m *Module) _sqlite3_user_data(v0 int32) int32 {
	return m._env.Xsqlite3_user_data(v0)
}
func (m *Module) _sqlite3_context_db_handle(v0 int32) int32 {
	return m._env.Xsqlite3_context_db_handle(v0)
}
func (m *Module) _sqlite3_result_error_code(v0, v1 int32) {
	m._env.Xsqlite3_result_error_code(v0, v1)
}
func (m *Module) X__wasm_apply_data_relocs() {
	var v0 int32
	store32((*m.memory)[uint32(m.___memory_base+i32(4068)):], uint32(m.___table_base+i32(8)))
	store32((*m.memory)[uint32(m.___memory_base+i32(4072)):], uint32(m.___table_base+i32(9)))
	store32((*m.memory)[uint32(m.___memory_base+i32(4076)):], uint32(m.___table_base+i32(10)))
	store32((*m.memory)[uint32(m.___memory_base+i32(4080)):], uint32(m.___table_base+i32(11)))
	store32((*m.memory)[uint32(m.___memory_base+i32(4084)):], uint32(m.___table_base+i32(12)))
	store32((*m.memory)[uint32(m.___memory_base+i32(4088)):], uint32(m.___table_base+i32(13)))
	store32((*m.memory)[uint32(m.___memory_base+i32(4092)):], uint32(m.___table_base+i32(14)))
	store32((*m.memory)[uint32(m.___memory_base+i32(4096)):], uint32(m.___table_base+i32(15)))
	store32((*m.memory)[uint32(m.___memory_base+i32(4100)):], uint32(m.___table_base+i32(16)))
	store32((*m.memory)[uint32(m.___memory_base+i32(4104)):], uint32(m.___table_base+i32(17)))
	store32((*m.memory)[uint32(m.___memory_base+i32(4108)):], uint32(m.___table_base+i32(18)))
	store32((*m.memory)[uint32(m.___memory_base+i32(4112)):], uint32(m.___table_base+i32(19)))
	store32((*m.memory)[uint32(m.___memory_base+i32(4116)):], uint32(m.___table_base+i32(20)))
	store32((*m.memory)[uint32(m.___memory_base+i32(4140)):], uint32(m.___table_base+i32(21)))
	store32((*m.memory)[uint32(m.___memory_base+i32(4176)):], uint32(m.___memory_base+i32(415)))
	store32((*m.memory)[uint32(m.___memory_base+i32(4180)):], uint32(m.___memory_base+i32(424)))
	t0 := m.___memory_base + i32(4184)
	v0 = m.___memory_base + i32(409)
	store32((*m.memory)[uint32(t0):], uint32(v0))
	store32((*m.memory)[uint32(m.___memory_base+i32(4188)):], uint32(v0))
	store32((*m.memory)[uint32(m.___memory_base+i32(4192)):], uint32(m.___memory_base+i32(431)))
}
func (m *Module) Xsqlite3_extension_init(v0, v1, v2 int32) int32 {
	var v3, v4 int32
	{
		t0 := m._sqlite3_create_function(v0, m.___memory_base+i32(19), i32(1), i32(2049), i32(0), m.___table_base, i32(0), i32(0))
		v1 = t0
		if v1 != 0 {
			goto l0
		}
		t1 := m._sqlite3_create_function(v0, m.___memory_base, i32(2), i32(2049), i32(0), m.___table_base+i32(1), i32(0), i32(0))
		v1 = t1
		if v1 != 0 {
			goto l0
		}
		t2 := m._sqlite3_create_function(v0, m.___memory_base+i32(108), i32(1), i32(2049), i32(0), m.___table_base+i32(2), i32(0), i32(0))
		v1 = t2
		if v1 != 0 {
			goto l0
		}
		t3 := m._sqlite3_create_function(v0, m.___memory_base+i32(200), i32(1), i32(2049), i32(0), m.___table_base+i32(3), i32(0), i32(0))
		v1 = t3
		if v1 != 0 {
			goto l0
		}
		t4 := m._sqlite3_create_module(v0, m.___memory_base+i32(680), m.___memory_base+i32(4064), i32(0))
		v1 = t4
		if v1 != 0 {
			goto l0
		}
		t5 := m._sqlite3_malloc64(i64(8))
		v2 = t5
		if v2 == 0 {
			return i32(7)
		}
		store64((*m.memory)[uint32(v2):], uint64(i64(0)))
		{
			t6 := v0
			v3 = m.___memory_base + i32(570)
			t7 := v3
			t8 := v2
			v4 = m.___table_base + i32(4)
			t9 := m._sqlite3_create_function_v2(t6, t7, i32(2), i32(2049), t8, v4, i32(0), i32(0), i32(0))
			v1 = t9
			if v1 != 0 {
				goto l1
			}
			t10 := m._sqlite3_create_function_v2(v0, v3, i32(3), i32(2049), v2, v4, i32(0), i32(0), i32(0))
			v1 = t10
			if v1 != 0 {
				goto l1
			}
			t11 := m._sqlite3_create_function_v2(v0, v3, i32(1), i32(2049), v2, v4, i32(0), i32(0), m.___table_base+i32(5))
			return t11
		}
	l1:
		m._sqlite3_free(v2)
	}
l0:
	return v1
}
func (m *Module) _transliterateSqlFunc(v0, v1, v2 int32) {
	t0 := int32(load32((*m.memory)[uint32(v2):]))
	t1 := m._sqlite3_value_text(t0)
	t2 := int32(load32((*m.memory)[uint32(v2):]))
	t3 := m._sqlite3_value_bytes(t2)
	t4 := m._transliterate(t1, t3)
	v1 = t4
	if v1 == 0 {
		m._sqlite3_result_error_nomem(v0)
		return
	}
	m._sqlite3_result_text(v0, v1, i32(-1), m.___table_base+i32(6))
}
func (m *Module) _editdistSqlFunc(v0, v1, v2 int32) {
	t0 := int32(load32((*m.memory)[uint32(v2):]))
	t1 := m._sqlite3_value_text(t0)
	t2 := int32(load32((*m.memory)[int64(uint32(v2))+4:]))
	t3 := m._sqlite3_value_text(t2)
	t4 := m._editdist1(t1, t3, i32(0))
	v1 = t4
	if v1 < i32(0) {
		switch v1 + i32(4) {
		case 0:
			goto l0
		case 1:
			goto l1
		case 2:
			goto l2
		default:
			goto l3
		}
	l1:
		m._sqlite3_result_error_nomem(v0)
		return
	l0:
		m._sqlite3_result_error_toobig(v0)
		return
	l2:
		m._sqlite3_result_error(v0, m.___memory_base+i32(1055), i32(-1))
		return
	l3:
		m._sqlite3_result_error(v0, m.___memory_base+i32(1030), i32(-1))
		return
	}
	m._sqlite3_result_int(v0, v1)
}
func (m *Module) _phoneticHashSqlFunc(v0, v1, v2 int32) {
	t0 := int32(load32((*m.memory)[uint32(v2):]))
	t1 := m._sqlite3_value_text(t0)
	v1 = t1
	if v1 != 0 {
		t2 := int32(load32((*m.memory)[uint32(v2):]))
		t3 := m._sqlite3_value_bytes(t2)
		t4 := m._phoneticHash(v1, t3)
		v1 = t4
		if v1 == 0 {
			m._sqlite3_result_error_nomem(v0)
			return
		}
		m._sqlite3_result_text(v0, v1, i32(-1), m.___table_base+i32(6))
	}
}
func (m *Module) _scriptCodeSqlFunc(v0, v1, v2 int32) {
	var v3, v4, v5, v6, v7 int32
	t0 := *m.___stack_pointer
	v4 = t0 - i32(16)
	*m.___stack_pointer = v4
	t1 := int32(load32((*m.memory)[uint32(v2):]))
	t2 := m._sqlite3_value_text(t1)
	v5 = t2
	t3 := int32(load32((*m.memory)[uint32(v2):]))
	t4 := m._sqlite3_value_bytes(t3)
	v3 = t4
	v1 = i32(0)
l1:
	if v3 > i32(0) {
		t5 := m._utf8Read(v5, v3, v4+i32(12))
		v2 = t5
		t6 := int32(load32((*m.memory)[int64(uint32(v4))+12:]))
		t7 := v3
		v6 = t6
		v3 = t7 - v6
		v5 = v5 + v6
		if v2 <= i32(686) {
			if v2 <= i32(127) {
				t8 := int32((*m.memory)[uint32(m.___memory_base+i32(3904)+v2&i32(127))])
				if uint32(t8) > uint32(i32(9)) {
					goto l0
				}
			}
			v1 = v1 | i32(1)
			goto l1
		l0:
			p9 := v7
			if uint32(v2-i32(48)) < uint32(i32(10)) {
				p9 = i32(1)
			}
			v7 = p9
			goto l1
		}
		v6 = v2 & i32(0x7fffff00)
		if v6 == i32(1024) {
			v1 = v1 | i32(2)
			goto l1
		}
		if uint32(v2-i32(902)) <= uint32(i32(72)) {
			v1 = v1 | i32(4)
			goto l1
		}
		var p10 int32
		if uint32(v2-i32(1424)) <= uint32(i32(111)) {
			p10 = v1 | i32(8)
		} else {
			p11 := v1
			if v6 == i32(1536) {
				p11 = v1 | i32(16)
			}
			p10 = p11
		}
		v1 = p10
		goto l1
	}
	v2 = i32(999)
	{
		t13 := v1
		p12 := v1
		if v7 != 0 {
			p12 = i32(1)
		}
		p14 := p12
		if v1 != 0 {
			p14 = t13
		}
		v1 = p14
		switch v1 {
		case 0:
			goto l2
		case 1:
			goto l3
		case 2:
			goto l4
		case 3, 5, 6, 7:
			goto l5
		case 4:
			goto l6
		case 8:
			goto l7
		default:
			goto l8
		}
	}
l3:
	v2 = i32(215)
	goto l2
l4:
	v2 = i32(220)
	goto l2
l6:
	v2 = i32(200)
	goto l2
l7:
	v2 = i32(125)
	goto l2
l8:
	if v1 == i32(16) {
		goto l9
	}
l5:
	v2 = i32(998)
	goto l2
l9:
	v2 = i32(160)
l2:
	*m.___stack_pointer = v4 + i32(16)
	m._sqlite3_result_int(v0, v2)
}
func (m *Module) _editDist3SqlFunc(v0, v1, v2 int32) {
	var v3, v4, v5, v6, v7 int32
	t0 := m._sqlite3_user_data(v0)
	v4 = t0
	t1 := m._sqlite3_context_db_handle(v0)
	v3 = t1
	t2 := int32(load32((*m.memory)[uint32(v2):]))
	t3 := m._sqlite3_value_text(t2)
	v5 = t3
	{
		if v1 == i32(1) {
			t4 := m._editDist3ConfigLoad(v4, v3, v5)
			v1 = t4
			if v1 == 0 {
				return
			}
			m._sqlite3_result_error_code(v0, v1)
			return
		}
		t5 := int32(load32((*m.memory)[int64(uint32(v2))+4:]))
		t6 := m._sqlite3_value_text(t5)
		v6 = t6
		t7 := int32(load32((*m.memory)[uint32(v2):]))
		t8 := m._sqlite3_value_bytes(t7)
		v7 = t8
		t9 := int32(load32((*m.memory)[int64(uint32(v2))+4:]))
		t10 := m._sqlite3_value_bytes(t9)
		v3 = t10
		t12 := v4
		var p11 int32
		if v1 == i32(3) {
			t13 := int32(load32((*m.memory)[int64(uint32(v2))+8:]))
			t14 := m._sqlite3_value_int(t13)
			p11 = t14
		} else {
			p11 = i32(0)
		}
		t15 := m._editDist3FindLang(t12, p11)
		v1 = t15
		t16 := m._editDist3FromStringNew(v1, v5, v7)
		v2 = t16
		if v2 == 0 {
			goto l1
		}
		t17 := m._editDist3Core(v2, v6, v3, v1, i32(0))
		v1 = t17
		m._editDist3FromStringDelete(v2)
		switch v1 + i32(2) {
		case 0:
			goto l2
		case 1:
			goto l1
		default:
			goto l3
		}
	l2:
		m._sqlite3_result_error_toobig(v0)
		return
	l3:
		m._sqlite3_result_int(v0, v1)
	}
	return
l1:
	m._sqlite3_result_error_nomem(v0)
}
func (m *Module) _editDist3ConfigDelete(v0 int32) {
	m._editDist3ConfigClear(v0)
	m._sqlite3_free(v0)
}
func (m *Module) _local_sqlite3_free(v0 int32) {
	m._sqlite3_free(v0)
}
func (m *Module) _transliterate(v0, v1 int32) int32 {
	var v2, v3, v4, v5, v6, v7, v8, v9, v10 int32
	t0 := *m.___stack_pointer
	v10 = t0 - i32(16)
	*m.___stack_pointer = v10
	{
		t1 := m._sqlite3_malloc64(int64(v1)<<2 | i64(1))
		v5 = t1
		if v5 == 0 {
			goto l0
		}
	l2:
		{
			v4 = v2
			var p2 int32
			if v1 > i32(0) {
				t3 := m._utf8Read(v0, v1, v10+i32(12))
				v6 = t3
				t4 := int32(load32((*m.memory)[int64(uint32(v10))+12:]))
				t5 := v1
				v2 = t4
				v1 = t5 - v2
				v0 = v0 + v2
				if v6 < i32(128) {
					goto l1
				}
				v2 = i32(0)
				v7 = i32(388)
			l4:
				{
					if v2 > v7 {
						v6 = i32(63)
						goto l1
					}
					t6 := m.___memory_base + i32(1440)
					v8 = int32(uint32(v2+v7) >> 1)
					v9 = t6 + v8*i32(6)
					t7 := int32(load16((*m.memory)[uint32(v9):]))
					v3 = t7
					if v3 == v6 {
						t8 := int32((*m.memory)[int64(uint32(v9))+2])
						(*m.memory)[uint32(v4+v5)] = byte(t8)
						v2 = v4 + i32(1)
						t9 := int32((*m.memory)[int64(uint32(v9))+3])
						v3 = t9
						if v3 == 0 {
							goto l2
						}
						(*m.memory)[uint32(v2+v5)] = byte(v3)
						v2 = v4 + i32(2)
						var p10 int32
						if v8 != i32(339) {
							p10 = 1
						}
						var p11 int32
						if v8 != i32(307) {
							p11 = 1
						}
						v3 = p10 & p11
						if v3 != 0 {
							goto l2
						}
						t12 := int32((*m.memory)[int64(uint32(v9))+4])
						(*m.memory)[uint32(v2+v5)] = byte(t12)
						v2 = v4 + i32(3)
						if v3 != 0 {
							goto l2
						}
						t13 := int32((*m.memory)[int64(uint32(v9))+5])
						v6 = t13
						p2 = i32(4)
						goto l3
					} else {
						t14 := v2
						t15 := v8 + i32(1)
						var p16 int32
						if v3 > v6 {
							p16 = 1
						}
						v3 = p16
						p17 := t15
						if v3 != 0 {
							p17 = t14
						}
						v2 = p17
						p18 := v7
						if v3 != 0 {
							p18 = v8 - i32(1)
						}
						v7 = p18
						goto l4
					}
				}
			}
			(*m.memory)[uint32(v4+v5)] = byte(i32(0))
			goto l0
		l1:
			v2 = v4
			p2 = i32(1)
		l3:
			(*m.memory)[uint32(v2+v5)] = byte(v6)
			v2 = p2 + v4
			goto l2
		}
	}
l0:
	*m.___stack_pointer = v10 + i32(16)
	return v5
}
func (m *Module) _editdist1(v0, v1, v2 int32) int32 {
	var v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26 int32
	t0 := *m.___stack_pointer
	v20 = t0 - i32(304)
	*m.___stack_pointer = v20
	v3 = i32(-1)
	if v0 == 0 {
		goto l0
	}
	if v1 == 0 {
		goto l0
	}
	v8 = v0 + i32(1)
	v7 = v1 + i32(1)
l2:
	{
		t1 := int32((*m.memory)[uint32(v0)])
		v4 = t1
		if v4 == 0 {
			goto l1
		}
		t2 := int32((*m.memory)[uint32(v1)])
		if v4 != t2 {
			goto l1
		}
		v8 = v8 + i32(1)
		v7 = v7 + i32(1)
		v17 = v17 + i32(1)
		v1 = v1 + i32(1)
		v0 = v0 + i32(1)
		v5 = v4
		goto l2
	}
l1:
	if v2 != 0 {
		store32((*m.memory)[uint32(v2):], uint32(v17))
		t3 := int32((*m.memory)[uint32(v0)])
		v4 = t3
	}
	if v4&i32(255) == 0 {
		t4 := int32((*m.memory)[uint32(v1)])
		if t4 == 0 {
			goto l3
		}
	}
	v3 = v4
l5:
	if v3&i32(255) != 0 {
		if int32(int8(v3)) < i32(0) {
			goto l4
		}
		t5 := int32((*m.memory)[uint32(v8+v11)])
		v3 = t5
		v11 = v11 + i32(1)
		goto l5
	}
	v3 = i32(-4)
	if uint32(v11) > uint32(i32(99999)) {
		goto l0
	}
	v22 = v11 + i32(1)
	v6 = i32(5)
	v12 = i32(4)
l6:
	{
		t6 := int32(int8((*m.memory)[uint32(v1+v9)]))
		v13 = t6
		if v13 != 0 {
			if v13 < i32(0) {
				goto l4
			}
			v6 = v6 + i32(5)
			v12 = v12 + i32(4)
			v9 = v9 + i32(1)
			goto l6
		}
	}
	if uint32(v9) > uint32(i32(99999)) {
		goto l0
	}
	if v11 == 0 {
		t7 := int32((*m.memory)[uint32(v1)])
		v0 = t7
		v3 = i32(0)
	l7:
		{
			if v0&i32(255) == 0 {
				goto l0
			}
			t8 := int32(int8(v5))
			v5 = v0
			t9 := int32(int8((*m.memory)[uint32(v7)]))
			t10 := int32(int8(v5))
			v0 = t9
			t11 := m._insertOrDeleteCost(t8, t10, v0)
			v3 = int32(uint32(t11)>>2) + v3
			v7 = v7 + i32(1)
			goto l7
		}
	}
	if v9 == 0 {
		v3 = i32(0)
	l8:
		{
			if v4&i32(255) == 0 {
				goto l0
			}
			t12 := int32(int8(v5))
			v5 = v4
			t13 := int32(int8((*m.memory)[uint32(v8)]))
			t14 := int32(int8(v5))
			v4 = t13
			t15 := m._insertOrDeleteCost(t12, t14, v4)
			v3 = t15 + v3
			v8 = v8 + i32(1)
			goto l8
		}
	}
	if v4&i32(255) == i32(42) {
		t16 := int32((*m.memory)[int64(uint32(v0))+1])
		if t16 == 0 {
			goto l3
		}
	}
	v4 = i32(0)
	v3 = v20
	{
		if uint32(v9) < uint32(i32(60)) {
			goto l9
		}
		t17 := m._sqlite3_malloc64(int64(uint32(v6)))
		v3 = t17
		v23 = v3
		if v3 != 0 {
			goto l9
		}
		v3 = i32(-3)
		goto l0
	}
l9:
	store32((*m.memory)[uint32(v3):], uint32(i32(0)))
	v18 = v3 + v12
	(*m.memory)[uint32(v18)] = byte(v5)
	v24 = v18 - i32(4)
	v8 = v3
	v7 = v5
l18:
	if v4 == v9 {
		v6 = i32(0)
		v14 = i32(1)
		v7 = i32(0)
		{
			{
			l13:
				if v14 != v22 {
					var p18 int32
					if v11 == v14 {
						p18 = 1
					}
					v4 = v0 + v14
					t19 := int32(int8((*m.memory)[uint32(v4-i32(1))]))
					v7 = t19
					var p20 int32
					if v7 == i32(42) {
						p20 = 1
					}
					if p18&p20 != 0 {
						goto l10
					}
					t21 := int32(int8((*m.memory)[uint32(v4)]))
					t22 := m._insertOrDeleteCost(int32(int8(v5)), v7, t21)
					t23 := v3
					v12 = t22 + v6
					store32((*m.memory)[uint32(t23):], uint32(v12))
					v25 = v7 & i32(127)
					v4 = i32(0)
					v26 = v7 & i32(255)
					v8 = v3
				l12:
					if v4 != v9 {
						v13 = v6
						v21 = v4 + v18
						t24 := int32(int8((*m.memory)[uint32(v21)]))
						v6 = t24
						t25 := v6
						v5 = v1 + v4
						t26 := int32((*m.memory)[uint32(v5)])
						v10 = t26
						v16 = int32(int8(v10))
						t27 := int32(int8((*m.memory)[int64(uint32(v5))+1]))
						t28 := v16
						v15 = t27
						t29 := m._insertOrDeleteCost(t25, t28, v15)
						v5 = t29
						p30 := v5
						if v11 == v14 {
							p30 = int32(uint32(v5) >> 2)
						}
						v19 = p30
						v5 = i32(0)
						t31 := int32(int8((*m.memory)[int64(uint32(v21))+1]))
						t32 := m._insertOrDeleteCost(t31, v7, v15)
						{
							if v10 == v26 {
								goto l11
							}
							if v7^v16 == i32(32) {
								if uint32((v16&i32(223)-i32(65))&i32(255)) < uint32(i32(26)) {
									goto l11
								}
							}
							v5 = i32(40)
							t34 := m.___memory_base
							p33 := i32(3776)
							if v6 != 0 {
								p33 = i32(3904)
							}
							v6 = t34 + p33
							t35 := int32((*m.memory)[uint32(v6+v25)])
							v10 = t35
							t36 := int32((*m.memory)[uint32(v6+v16&i32(127))])
							t37 := v10
							v6 = t36
							if t37 == v6 {
								goto l11
							}
							p38 := i32(100)
							if uint32((v6-i32(2)|(v10-i32(2)))&i32(255)) < uint32(i32(8)) {
								p38 = i32(75)
							}
							v5 = p38
						}
					l11:
						t39 := int32(load32((*m.memory)[uint32(v8):]))
						v10 = t39
						v8 = v8 + i32(4)
						t40 := int32(load32((*m.memory)[uint32(v8):]))
						v6 = t40
						v15 = t32 + v6
						t41 := v15
						v19 = v10 + v19
						var p42 int32
						if t41 < v19 {
							p42 = 1
						}
						v10 = p42
						t43 := v8
						v5 = v5 + v13
						t45 := v5
						p44 := v19
						if v10 != 0 {
							p44 = v15
						}
						v13 = p44
						p46 := v13
						if v5 < v13 {
							p46 = t45
						}
						store32((*m.memory)[uint32(t43):], uint32(p46))
						t48 := v21
						p47 := v16
						if v10 != 0 {
							p47 = v7
						}
						(*m.memory)[int64(uint32(t48))+1] = byte(p47)
						v4 = v4 + i32(1)
						goto l12
					}
					v14 = v14 + i32(1)
					v6 = v12
					v5 = v7
					goto l13
				}
				if v7&i32(255) != i32(42) {
					goto l14
				}
			l10:
				v4 = v3 + i32(4)
				t49 := int32(load32((*m.memory)[uint32(v4):]))
				v3 = t49
				v1 = i32(0)
			l17:
				{
					if v1 == v9 {
						goto l15
					}
					t50 := int32(load32((*m.memory)[uint32(v4):]))
					v5 = t50
					p51 := v3
					if v3 > v5 {
						p51 = v5
					}
					v0 = p51
					if v2 == 0 {
						goto l16
					}
					if v3 <= v5 {
						goto l16
					}
					store32((*m.memory)[uint32(v2):], uint32(v1+v17+i32(1)))
					v0 = v5
				l16:
					v3 = v0
					v1 = v1 + i32(1)
					v4 = v4 + i32(4)
					goto l17
				}
			}
		l14:
			t52 := int32(load32((*m.memory)[uint32(v24):]))
			v3 = t52
		}
	l15:
		m._sqlite3_free(v23)
		goto l0
	} else {
		v6 = v1 + v4
		t53 := int32(int8((*m.memory)[int64(uint32(v6))+1]))
		v12 = t53
		t54 := int32(int8((*m.memory)[uint32(v6)]))
		t55 := v4 + v18
		v6 = t54
		(*m.memory)[int64(uint32(t55))+1] = byte(v6)
		t56 := int32(load32((*m.memory)[uint32(v8):]))
		v13 = t56
		v8 = v8 + i32(4)
		t57 := m._insertOrDeleteCost(int32(int8(v7)), v6, v12)
		store32((*m.memory)[uint32(v8):], uint32(t57+v13))
		v4 = v4 + i32(1)
		v7 = v6
		goto l18
	}
l4:
	v3 = i32(-2)
	goto l0
l3:
	v3 = i32(0)
l0:
	*m.___stack_pointer = v20 + i32(304)
	return v3
}
func (m *Module) _phoneticHash(v0, v1 int32) int32 {
	var v2, v3, v4, v5, v6, v7, v8, v9, v10, v11 int32
	{
		t0 := m._sqlite3_malloc64(int64(v1) + i64(1))
		v5 = t0
		if v5 == 0 {
			goto l0
		}
		{
			if v1 < i32(3) {
				goto l1
			}
			{
				t1 := int32((*m.memory)[uint32(v0)])
				switch t1 - i32(103) {
				case 0, 4:
					goto l2
				default:
					goto l1
				}
			}
		l2:
			t2 := int32((*m.memory)[int64(uint32(v0))+1])
			t3 := v0 + i32(1)
			t4 := v0
			var p5 int32
			if t2 == i32(110) {
				p5 = 1
			}
			v3 = p5
			p6 := t4
			if v3 != 0 {
				p6 = t3
			}
			v0 = p6
			v1 = v1 - v3
		}
	l1:
		p7 := i32(0)
		if v1 > i32(0) {
			p7 = v1
		}
		v10 = p7
		v8 = m.___memory_base + i32(3776)
		v3 = i32(119)
		v9 = i32(119)
	l6:
		{
			{
				{
					v2 = v11
					if v2 != v10 {
						v6 = v0 + v2
						t8 := int32((*m.memory)[uint32(v6)])
						v7 = t8
						v11 = v2 + i32(1)
						if v11 >= v1 {
							goto l3
						}
						if v7 == i32(100) {
							goto l4
						}
						if v7 != i32(119) {
							goto l5
						}
						t9 := int32((*m.memory)[int64(uint32(v6))+1])
						if t9 == i32(114) {
							goto l6
						}
						goto l5
					}
					(*m.memory)[uint32(v4+v5)] = byte(i32(0))
					goto l0
				l4:
					t10 := int32((*m.memory)[int64(uint32(v6))+1])
					switch t10 - i32(103) {
					case 0, 3:
						goto l6
					default:
						goto l5
					}
				}
			l5:
				if v2+i32(2) >= v1 {
					goto l3
				}
				if v7 != i32(116) {
					goto l3
				}
				t11 := int32((*m.memory)[int64(uint32(v6))+1])
				if t11 != i32(99) {
					goto l3
				}
				t12 := int32((*m.memory)[int64(uint32(v6))+2])
				if t12 == i32(104) {
					goto l6
				}
			}
		l3:
			t13 := int32((*m.memory)[uint32(v8+v7&i32(127))])
			v2 = t13
			if v2 == i32(11) {
				goto l6
			}
			var p14 int32
			if v2 == i32(12) {
				p14 = 1
			}
			var p15 int32
			if v3&i32(255) != i32(10) {
				p15 = 1
			}
			if p14&p15 != 0 {
				goto l6
			}
			if v2 != i32(1) {
				goto l7
			}
			if v9&i32(254) != i32(6) {
				goto l7
			}
			v8 = m.___memory_base + i32(3904)
			goto l6
		l7:
			t16 := v4
			var p17 int32
			if v2&i32(254) == i32(6) {
				p17 = 1
			}
			var p18 int32
			if v9&i32(255) == i32(1) {
				p18 = 1
			}
			v4 = t16 - p17&p18
			if v2 != 0 {
				t19 := int32((*m.memory)[uint32(m.___memory_base+i32(454)+v2)])
				v3 = t19
				{
					if v4 == 0 {
						goto l8
					}
					t20 := int32((*m.memory)[uint32(v4+v5-i32(1))])
					if t20 != v3 {
						goto l8
					}
					goto l9
				}
			l8:
				(*m.memory)[uint32(v4+v5)] = byte(v3)
				v4 = v4 + i32(1)
			l9:
				v3 = v2
				v9 = v3
			} else {
				v3 = i32(0)
			}
			v8 = m.___memory_base + i32(3904)
			goto l6
		}
	}
l0:
	return v5
}
func (m *Module) _utf8Read(v0, v1, v2 int32) int32 {
	var v3, v4, v5 int32
	v4 = i32(1)
	{
		t0 := int32((*m.memory)[uint32(v0)])
		v3 = t0
		if uint32(v3) < uint32(i32(192)) {
			goto l0
		}
		p1 := v1
		if v1 <= i32(1) {
			p1 = i32(1)
		}
		v4 = p1
		t2 := int32((*m.memory)[uint32(m.___memory_base+v3+i32(1184))])
		v3 = t2
		v1 = i32(1)
	l1:
		{
			if v1 == v4 {
				goto l0
			}
			t3 := int32((*m.memory)[uint32(v0+v1)])
			v5 = t3
			if v5&i32(192) == i32(128) {
				v3 = v5&i32(63) | v3<<6
				v1 = v1 + i32(1)
				goto l1
			}
		}
		v4 = v1
	}
l0:
	store32((*m.memory)[uint32(v2):], uint32(v4))
	return v3
}
func (m *Module) _insertOrDeleteCost(v0, v1, v2 int32) int32 {
	var v3, v4 int32
	t1 := m.___memory_base
	p0 := i32(3776)
	if v0 != 0 {
		p0 = i32(3904)
	}
	v4 = t1 + p0
	t2 := int32((*m.memory)[uint32(v4+v1&i32(127))])
	v3 = t2
	if v3 == 0 {
		return i32(1)
	}
	if v0 == v1 {
		return i32(10)
	}
	{
		var p3 int32
		if v3 != i32(1) {
			p3 = i32(50)
		} else {
			v1 = i32(20)
			if v0 == i32(114) {
				goto l0
			}
			if v2 == i32(114) {
				goto l0
			}
			p3 = i32(15)
		}
		t4 := int32((*m.memory)[uint32(v4+v0&i32(127))])
		p5 := p3
		if v3 != t4 {
			p5 = i32(100)
		}
		v1 = p5
	}
l0:
	return v1
}
func (m *Module) _spellfix1Create(v0, v1, v2, v3, v4, v5 int32) int32 {
	return m._spellfix1Init(i32(1), v0, v2, v3, v4, v5)
}
func (m *Module) _spellfix1Init(v0, v1, v2, v3, v4, v5 int32) int32 {
	var v6, v7, v8, v9, v10, v11 int32
	t0 := *m.___stack_pointer
	v6 = t0 + i32(-64)
	*m.___stack_pointer = v6
	t1 := int32(load32((*m.memory)[int64(uint32(v3))+8:]))
	v9 = t1
	{
		t2 := int32(load32((*m.memory)[int64(uint32(v3))+4:]))
		v10 = t2
		t3 := m._strlen(v10)
		v7 = t3
		t4 := m._sqlite3_malloc64(int64(v7) + i64(33))
		v8 = t4
		if v8 == 0 {
			v7 = i32(7)
			goto l0
		}
		store64((*m.memory)[int64(uint32(v8))+16:], uint64(i64(0)))
		store64((*m.memory)[int64(uint32(v8))+24:], uint64(i64(0)))
		store64((*m.memory)[int64(uint32(v8))+8:], uint64(i64(0)))
		store64((*m.memory)[uint32(v8):], uint64(i64(0)))
		t5 := v8
		v11 = v8 + i32(32)
		store32((*m.memory)[int64(uint32(t5))+16:], uint32(v11))
		v7 = v7 + i32(1)
		if v7 != 0 {
			memory_copy(*m.memory, uint32(v11), uint32(v10), uint32(v7))
		}
		store32((*m.memory)[int64(uint32(v6))+48:], uint32(v9))
		t6 := m._sqlite3_mprintf(m.___memory_base+i32(100), v6+i32(48))
		v7 = t6
		store32((*m.memory)[int64(uint32(v8))+12:], uint32(v1))
		store32((*m.memory)[int64(uint32(v8))+20:], uint32(v7))
		t8 := v6
		var p7 int32
		if v7 != 0 {
			_ = m._sqlite3_vtab_config(v1, i32(2), i32(0))
			t10 := m._sqlite3_declare_vtab(v1, m.___memory_base+i32(876))
			p7 = t10
		} else {
			p7 = i32(7)
		}
		v7 = p7
		store32((*m.memory)[int64(uint32(t8))+60:], uint32(v7))
		{
			if v0 == 0 {
				goto l1
			}
			if v7 != 0 {
				goto l1
			}
			store32((*m.memory)[int64(uint32(v6))+36:], uint32(v9))
			store32((*m.memory)[int64(uint32(v6))+32:], uint32(v10))
			v0 = v6 + i32(60)
			m._spellfix1DbExec(v0, v1, m.___memory_base+i32(1240), v6+i32(32))
			store32((*m.memory)[int64(uint32(v6))+24:], uint32(v9))
			store32((*m.memory)[int64(uint32(v6))+20:], uint32(v9))
			store32((*m.memory)[int64(uint32(v6))+16:], uint32(v10))
			m._spellfix1DbExec(v0, v1, m.___memory_base+i32(485), v6+i32(16))
			t11 := int32(load32((*m.memory)[int64(uint32(v6))+60:]))
			v7 = t11
		}
	l1:
		v3 = v3 + i32(12)
		v1 = i32(3)
	l4:
		{
			if v7 != 0 {
				goto l0
			}
			if v1 >= v2 {
				goto l0
			}
			var p12 int32
			{
				{
					t13 := int32(load32((*m.memory)[uint32(v3):]))
					t14 := m._strncmp(t13, m.___memory_base+i32(468), i32(16))
					if t14 != 0 {
						goto l2
					}
					t15 := int32(load32((*m.memory)[int64(uint32(v8))+24:]))
					if t15 != 0 {
						goto l2
					}
					t16 := int32(load32((*m.memory)[uint32(v3):]))
					t17 := m._spellfix1Dequote(t16 + i32(16))
					t18 := v8
					v0 = t17
					store32((*m.memory)[int64(uint32(t18))+24:], uint32(v0))
					p19 := i32(7)
					if v0 != 0 {
						p19 = i32(0)
					}
					p12 = p19
					goto l3
				}
			l2:
				t20 := int32(load32((*m.memory)[uint32(v3):]))
				store32((*m.memory)[uint32(v6):], uint32(t20))
				t21 := m._sqlite3_mprintf(m.___memory_base+i32(1120), v6)
				store32((*m.memory)[uint32(v5):], uint32(t21))
				p12 = i32(1)
			}
		l3:
			v7 = p12
			v3 = v3 + i32(4)
			v1 = v1 + i32(1)
			goto l4
		}
	}
l0:
	if v8 == 0 {
		goto l5
	}
	if v7 == 0 {
		goto l5
	}
	store32((*m.memory)[uint32(v4):], uint32(i32(0)))
	_ = m._spellfix1Uninit(i32(0), v8)
	goto l6
l5:
	store32((*m.memory)[uint32(v4):], uint32(v8))
l6:
	*m.___stack_pointer = v6 - i32(-64)
	return v7
}
func (m *Module) _spellfix1Connect(v0, v1, v2, v3, v4, v5 int32) int32 {
	return m._spellfix1Init(i32(0), v0, v2, v3, v4, v5)
}
func (m *Module) _spellfix1BestIndex(v0, v1 int32) int32 {
	var v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12 int32
	var v13 float64
	v0 = i32(0)
	t0 := int32(load32((*m.memory)[uint32(v1):]))
	v5 = t0
	p1 := i32(0)
	if v5 > i32(0) {
		p1 = v5
	}
	v11 = p1
	t2 := int32(load32((*m.memory)[int64(uint32(v1))+4:]))
	v3 = t2
	v6 = i32(4)
	v7 = i32(-1)
	v8 = i32(-1)
	v9 = i32(-1)
	v5 = i32(-1)
	v10 = i32(-1)
l6:
	if v0 != v11 {
		{
			t3 := int32((*m.memory)[int64(uint32(v3))+5])
			if t3 == 0 {
				goto l0
			}
			{
				if v2&i32(1) != 0 {
					goto l1
				}
				t4 := int32(load32((*m.memory)[uint32(v3):]))
				if t4 != 0 {
					goto l1
				}
				t5 := int32((*m.memory)[int64(uint32(v3))+4])
				if t5 != i32(64) {
					goto l1
				}
				t6 := int32(load32((*m.memory)[int64(uint32(v1))+16:]))
				v4 = t6 + v6
				(*m.memory)[uint32(v4)] = byte(i32(1))
				store32((*m.memory)[uint32(v4-i32(4)):], uint32(i32(1)))
				v2 = v2 | i32(1)
			}
		l1:
			{
				if v2&i32(2) != 0 {
					goto l2
				}
				t7 := int32(load32((*m.memory)[uint32(v3):]))
				if t7 != i32(3) {
					goto l2
				}
				t8 := int32((*m.memory)[int64(uint32(v3))+4])
				t9 := v2 | i32(2)
				t10 := v2
				var p11 int32
				if t8 == i32(2) {
					p11 = 1
				}
				v4 = p11
				p12 := t10
				if v4 != 0 {
					p12 = t9
				}
				v2 = p12
				p13 := v7
				if v4 != 0 {
					p13 = v0
				}
				v7 = p13
			}
		l2:
			{
				if v2&i32(4) != 0 {
					goto l3
				}
				t14 := int32(load32((*m.memory)[uint32(v3):]))
				if t14 != i32(7) {
					goto l3
				}
				t15 := int32((*m.memory)[int64(uint32(v3))+4])
				t16 := v2 | i32(4)
				t17 := v2
				var p18 int32
				if t15 == i32(2) {
					p18 = 1
				}
				v4 = p18
				p19 := t17
				if v4 != 0 {
					p19 = t16
				}
				v2 = p19
				p20 := v8
				if v4 != 0 {
					p20 = v0
				}
				v8 = p20
			}
		l3:
			{
				if v2&i32(8) != 0 {
					goto l4
				}
				t21 := int32(load32((*m.memory)[uint32(v3):]))
				if t21 != i32(8) {
					goto l4
				}
				t22 := int32((*m.memory)[int64(uint32(v3))+4])
				t23 := v2 | i32(8)
				t24 := v2
				var p25 int32
				if t22 == i32(2) {
					p25 = 1
				}
				v4 = p25
				p26 := t24
				if v4 != 0 {
					p26 = t23
				}
				v2 = p26
				p27 := v9
				if v4 != 0 {
					p27 = v0
				}
				v9 = p27
			}
		l4:
			{
				if v2&i32(48) != 0 {
					goto l5
				}
				t28 := int32(load32((*m.memory)[uint32(v3):]))
				if t28 != i32(2) {
					goto l5
				}
				t29 := int32((*m.memory)[int64(uint32(v3))+4])
				v4 = t29
				var p30 int32
				if v4 == i32(16) {
					p30 = 1
				}
				v12 = p30
				var p31 int32
				if v12 == 0 {
					p31 = 1
				}
				var p32 int32
				if v4 != i32(8) {
					p32 = 1
				}
				if p31&p32 != 0 {
					goto l5
				}
				p33 := i32(32)
				if v12 != 0 {
					p33 = i32(16)
				}
				v2 = p33 | v2
				v5 = v0
			}
		l5:
			if v2&i32(64) != 0 {
				goto l0
			}
			t34 := int32(load32((*m.memory)[uint32(v3):]))
			if t34 >= i32(0) {
				goto l0
			}
			t35 := int32((*m.memory)[int64(uint32(v3))+4])
			t36 := v2 | i32(64)
			t37 := v2
			var p38 int32
			if t35 == i32(2) {
				p38 = 1
			}
			v4 = p38
			p39 := t37
			if v4 != 0 {
				p39 = t36
			}
			v2 = p39
			p40 := v10
			if v4 != 0 {
				p40 = v0
			}
			v10 = p40
		}
	l0:
		v6 = v6 + i32(8)
		v3 = v3 + i32(12)
		v0 = v0 + i32(1)
		goto l6
	}
	if v2&i32(1) != 0 {
		store32((*m.memory)[int64(uint32(v1))+20:], uint32(v2))
		{
			t41 := int32(load32((*m.memory)[int64(uint32(v1))+8:]))
			if t41 != i32(1) {
				goto l7
			}
			t42 := int32(load32((*m.memory)[int64(uint32(v1))+12:]))
			v0 = t42
			t43 := int32(load32((*m.memory)[uint32(v0):]))
			if t43 != i32(4) {
				goto l7
			}
			t44 := int32((*m.memory)[int64(uint32(v0))+4])
			if t44 != 0 {
				goto l7
			}
			store32((*m.memory)[int64(uint32(v1))+32:], uint32(i32(1)))
		}
	l7:
		v3 = i32(2)
		if v2&i32(2) != 0 {
			t45 := int32(load32((*m.memory)[int64(uint32(v1))+16:]))
			v0 = t45 + v7<<3
			(*m.memory)[int64(uint32(v0))+4] = byte(i32(1))
			store32((*m.memory)[uint32(v0):], uint32(i32(2)))
			v3 = i32(3)
		}
		if v2&i32(4) != 0 {
			t46 := int32(load32((*m.memory)[int64(uint32(v1))+16:]))
			v0 = t46 + v8<<3
			(*m.memory)[int64(uint32(v0))+4] = byte(i32(1))
			store32((*m.memory)[uint32(v0):], uint32(v3))
			v3 = v3 + i32(1)
		}
		if v2&i32(8) != 0 {
			t47 := int32(load32((*m.memory)[int64(uint32(v1))+16:]))
			v0 = t47 + v9<<3
			(*m.memory)[int64(uint32(v0))+4] = byte(i32(1))
			store32((*m.memory)[uint32(v0):], uint32(v3))
			v3 = v3 + i32(1)
		}
		v13 = float64(100000)
		if v2&i32(48) == 0 {
			goto l8
		}
		t48 := int32(load32((*m.memory)[int64(uint32(v1))+16:]))
		v0 = t48 + v5<<3
		(*m.memory)[int64(uint32(v0))+4] = byte(i32(1))
		store32((*m.memory)[uint32(v0):], uint32(v3))
		goto l8
	}
	if v2&i32(64) != 0 {
		store32((*m.memory)[int64(uint32(v1))+20:], uint32(i32(64)))
		t49 := int32(load32((*m.memory)[int64(uint32(v1))+16:]))
		v0 = t49 + v10<<3
		(*m.memory)[int64(uint32(v0))+4] = byte(i32(1))
		store32((*m.memory)[uint32(v0):], uint32(i32(1)))
		v13 = float64(5)
		goto l8
	}
	store32((*m.memory)[int64(uint32(v1))+20:], uint32(i32(0)))
	v13 = float64(1e+50)
l8:
	store64((*m.memory)[int64(uint32(v1))+40:], math.Float64bits(v13))
	return i32(0)
}
func (m *Module) _spellfix1Disconnect(v0 int32) int32 {
	return m._spellfix1Uninit(i32(0), v0)
}
func (m *Module) _spellfix1Uninit(v0, v1 int32) int32 {
	var v2 int32
	t0 := *m.___stack_pointer
	v2 = t0 - i32(16)
	*m.___stack_pointer = v2
	store32((*m.memory)[int64(uint32(v2))+12:], uint32(i32(0)))
	{
		if v0 != 0 {
			t1 := int32(load32((*m.memory)[int64(uint32(v1))+12:]))
			v0 = t1
			t2 := int64(load64((*m.memory)[int64(uint32(v1))+16:]))
			store64((*m.memory)[uint32(v2):], uint64(t2))
			m._spellfix1DbExec(v2+i32(12), v0, m.___memory_base+i32(1154), v2)
			t3 := int32(load32((*m.memory)[int64(uint32(v2))+12:]))
			v0 = t3
			if v0 != 0 {
				goto l0
			}
		}
		t4 := int32(load32((*m.memory)[int64(uint32(v1))+20:]))
		m._sqlite3_free(t4)
		t5 := int32(load32((*m.memory)[int64(uint32(v1))+28:]))
		m._editDist3ConfigDelete(t5)
		t6 := int32(load32((*m.memory)[int64(uint32(v1))+24:]))
		m._sqlite3_free(t6)
		m._sqlite3_free(v1)
		v0 = i32(0)
	}
l0:
	*m.___stack_pointer = v2 + i32(16)
	return v0
}
func (m *Module) _spellfix1Destroy(v0 int32) int32 {
	return m._spellfix1Uninit(i32(1), v0)
}
func (m *Module) _spellfix1Open(v0, v1 int32) int32 {
	var v2 int32
	t0 := m._sqlite3_malloc64(i64(52))
	v2 = t0
	if v2 == 0 {
		return i32(7)
	}
	memory_zero(*m.memory, uint32(v2), uint32(i32(52)))
	store32((*m.memory)[uint32(v1):], uint32(v2))
	store32((*m.memory)[int64(uint32(v2))+4:], uint32(v0))
	return i32(0)
}
func (m *Module) _spellfix1Close(v0 int32) int32 {
	m._spellfix1ResetCursor(v0)
	m._spellfix1ResizeCursor(v0, i32(0))
	t0 := int32(load32((*m.memory)[int64(uint32(v0))+8:]))
	m._sqlite3_free(t0)
	m._sqlite3_free(v0)
	return i32(0)
}
func (m *Module) _spellfix1ResetCursor(v0 int32) {
	var v1, v2 int32
	v1 = i32(8)
l0:
	{
		t0 := int32(load32((*m.memory)[int64(uint32(v0))+16:]))
		if t0 > v2 {
			t1 := int32(load32((*m.memory)[int64(uint32(v0))+48:]))
			t2 := int32(load32((*m.memory)[uint32(t1+v1):]))
			m._sqlite3_free(t2)
			v1 = v1 - i32(-64)
			v2 = v2 + i32(1)
			goto l0
		}
	}
	store32((*m.memory)[int64(uint32(v0))+40:], uint32(i32(0)))
	store32((*m.memory)[int64(uint32(v0))+24:], uint32(i32(0)))
	store32((*m.memory)[int64(uint32(v0))+16:], uint32(i32(0)))
	t3 := int32(load32((*m.memory)[int64(uint32(v0))+44:]))
	v1 = t3
	if v1 != 0 {
		_ = m._sqlite3_finalize(v1)
		store32((*m.memory)[int64(uint32(v0))+44:], uint32(i32(0)))
	}
}
func (m *Module) _spellfix1ResizeCursor(v0, v1 int32) {
	var v2 int32
	t0 := int32(load32((*m.memory)[int64(uint32(v0))+48:]))
	t1 := m._sqlite3_realloc64(t0, int64(uint32(v1<<6)))
	v2 = t1
	{
		if v1 <= i32(0) {
			goto l0
		}
		if v2 != 0 {
			goto l0
		}
		m._spellfix1ResetCursor(v0)
		t2 := int32(load32((*m.memory)[int64(uint32(v0))+48:]))
		m._sqlite3_free(t2)
		v1 = i32(0)
	}
l0:
	store32((*m.memory)[int64(uint32(v0))+48:], uint32(v2))
	store32((*m.memory)[int64(uint32(v0))+20:], uint32(v1))
}
func (m *Module) _spellfix1Filter(v0, v1, v2, v3, v4 int32) int32 {
	var v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16 int32
	var v17 int64
	t0 := *m.___stack_pointer
	v6 = t0 - i32(128)
	*m.___stack_pointer = v6
	store32((*m.memory)[int64(uint32(v0))+12:], uint32(v1))
	{
		{
			{
				if v1&i32(1) != 0 {
					store32((*m.memory)[int64(uint32(v6))+56:], uint32(i32(0)))
					{
						t1 := int32(load32((*m.memory)[int64(uint32(v0))+4:]))
						v5 = t1
						t2 := int32(load32((*m.memory)[int64(uint32(v5))+24:]))
						if t2 == 0 {
							goto l0
						}
						t3 := int32(load32((*m.memory)[int64(uint32(v5))+28:]))
						if t3 != 0 {
							goto l0
						}
						t4 := m._sqlite3_malloc64(i64(8))
						t5 := v5
						v2 = t4
						store32((*m.memory)[int64(uint32(t5))+28:], uint32(v2))
						if v2 == 0 {
							goto l1
						}
						store64((*m.memory)[uint32(v2):], uint64(i64(0)))
						t6 := int32(load32((*m.memory)[int64(uint32(v5))+28:]))
						t7 := int32(load32((*m.memory)[int64(uint32(v5))+12:]))
						t8 := int32(load32((*m.memory)[int64(uint32(v5))+24:]))
						t9 := m._editDist3ConfigLoad(t6, t7, t8)
						v2 = t9
						if v2 != 0 {
							goto l2
						}
					}
				l0:
					v2 = i32(1)
					if v1&i32(2) != 0 {
						t10 := int32(load32((*m.memory)[int64(uint32(v4))+4:]))
						t11 := m._sqlite3_value_int(t10)
						v9 = t11
						v2 = i32(2)
					}
					v15 = i32(20)
					if v1&i32(4) != 0 {
						t12 := int32(load32((*m.memory)[uint32(v4+v2<<2):]))
						t13 := m._sqlite3_value_int(t12)
						v3 = t13
						p14 := v3
						if v3 <= i32(1) {
							p14 = i32(1)
						}
						v15 = p14
						v2 = v2 + i32(1)
					}
					v3 = i32(3)
					if v1&i32(8) != 0 {
						t15 := int32(load32((*m.memory)[uint32(v4+v2<<2):]))
						t16 := m._sqlite3_value_int(t15)
						v3 = t16
						p17 := v3
						if v3 <= i32(1) {
							p17 = i32(1)
						}
						v3 = p17
						p18 := v3
						if v3 >= i32(30) {
							p18 = i32(30)
						}
						v3 = p18
						v2 = v2 + i32(1)
					}
					var p19 int32
					if v1&i32(48) != 0 {
						t20 := int32(load32((*m.memory)[uint32(v4+v2<<2):]))
						t21 := m._sqlite3_value_int(t20)
						v1 = t21 + v1<<27>>31
						p22 := i32(0)
						if v1 > i32(0) {
							p22 = v1
						}
						p19 = p22
					} else {
						p19 = i32(-1)
					}
					v12 = p19
					m._spellfix1ResetCursor(v0)
					m._spellfix1ResizeCursor(v0, v15)
					t23 := int32(load32((*m.memory)[uint32(v4):]))
					t24 := m._sqlite3_value_text(t23)
					v1 = t24
					if v1 == 0 {
						goto l3
					}
					t25 := int32(load32((*m.memory)[int64(uint32(v5))+28:]))
					v2 = t25
					if v2 == 0 {
						goto l4
					}
					t26 := m._editDist3FindLang(v2, v9)
					v16 = t26
					t27 := m._editDist3FromStringNew(v16, v1, i32(-1))
					v13 = t27
					if v13 != 0 {
						goto l4
					}
					v13 = i32(0)
					v2 = i32(7)
					goto l5
				}
				t28 := int32(load32((*m.memory)[int64(uint32(v0))+4:]))
				v2 = t28
				m._spellfix1ResetCursor(v0)
				t29 := int64(load64((*m.memory)[int64(uint32(v2))+16:]))
				v17 = t29
				t30 := v6
				t31 := m.___memory_base
				v5 = v1 & i32(64)
				p32 := i32(1373)
				if v5 != 0 {
					p32 = i32(439)
				}
				store32((*m.memory)[int64(uint32(t30))+8:], uint32(t31+p32))
				store64((*m.memory)[uint32(v6):], uint64(v17))
				t33 := m._sqlite3_mprintf(m.___memory_base+i32(44), v6)
				v1 = t33
				if v1 == 0 {
					goto l1
				}
				t34 := int32(load32((*m.memory)[int64(uint32(v2))+12:]))
				t35 := v1
				v3 = v0 + i32(44)
				t36 := m._sqlite3_prepare_v2(t34, t35, i32(-1), v3, i32(0))
				v2 = t36
				m._sqlite3_free(v1)
				{
					if v5 == 0 {
						goto l6
					}
					if v2 != 0 {
						goto l6
					}
					t37 := int32(load32((*m.memory)[uint32(v3):]))
					t38 := int32(load32((*m.memory)[uint32(v4):]))
					t39 := m._sqlite3_bind_value(t37, i32(1), t38)
					v2 = t39
				}
			l6:
				store32((*m.memory)[int64(uint32(v0))+16:], uint32(i32(0)))
				store32((*m.memory)[int64(uint32(v0))+24:], uint32(i32(0)))
				if v2 != 0 {
					goto l2
				}
				t40 := int32(load32((*m.memory)[uint32(v3):]))
				t41 := m._sqlite3_step(t40)
				v1 = t41
				if v1 == i32(100) {
					store32((*m.memory)[int64(uint32(v0))+24:], uint32(i32(-1)))
					goto l3
				}
				p42 := i32(0)
				if v1 != i32(101) {
					p42 = v1
				}
				v2 = p42
				goto l2
			}
		l4:
			t43 := int32(load32((*m.memory)[uint32(v4):]))
			t44 := m._sqlite3_value_bytes(t43)
			t45 := m._transliterate(v1, t44)
			v10 = t45
			t46 := int32(load32((*m.memory)[int64(uint32(v0))+8:]))
			m._sqlite3_free(t46)
			store32((*m.memory)[int64(uint32(v0))+8:], uint32(v10))
			v2 = i32(7)
			if v10 == 0 {
				goto l5
			}
			t47 := m._strlen(v10)
			v7 = t47
			t48 := int32((*m.memory)[uint32(v7+v10-i32(1))])
			v11 = t48
			t49 := int64(load64((*m.memory)[int64(uint32(v5))+16:]))
			v17 = t49
			store32((*m.memory)[int64(uint32(v6))+40:], uint32(v9))
			store64((*m.memory)[int64(uint32(v6))+32:], uint64(v17))
			t50 := m._sqlite3_mprintf(m.___memory_base+i32(580), v6+i32(32))
			v1 = t50
			if v1 == 0 {
				store32((*m.memory)[int64(uint32(v6))+56:], uint32(i32(0)))
				goto l5
			}
			t51 := int32(load32((*m.memory)[int64(uint32(v5))+12:]))
			t52 := m._sqlite3_prepare_v2(t51, v1, i32(-1), v6+i32(56), i32(0))
			v4 = t52
			m._sqlite3_free(v1)
			store32((*m.memory)[int64(uint32(v0))+28:], uint32(v9))
			{
				if v4 != 0 {
					goto l7
				}
				v4 = i32(0)
				t53 := int32(load32((*m.memory)[int64(uint32(v0))+48:]))
				if t53 == 0 {
					goto l7
				}
				t54 := int32(load32((*m.memory)[int64(uint32(v6))+56:]))
				v8 = t54
				t55 := v10
				t56 := v7
				var p57 int32
				if v11 == i32(42) {
					p57 = 1
				}
				t58 := m._phoneticHash(t55, t56-p57)
				v4 = t58
				if v4 == 0 {
					v4 = i32(7)
					goto l7
				}
				t60 := v3
				var p59 int32
				{
					t61 := m._strlen(v4)
					v1 = t61
					if v1 >= i32(31) {
						(*m.memory)[int64(uint32(v4))+30] = byte(i32(0))
						var p62 int32
						if uint32(v3) < uint32(i32(30)) {
							p62 = 1
						}
						v7 = p62
						p59 = i32(29)
						goto l8
					}
					var p63 int32
					if v1 > v3 {
						p63 = 1
					}
					v7 = p63
					t64 := v1
					var p65 int32
					if v1 > i32(2) {
						p65 = 1
					}
					p59 = t64 - p65
				}
			l8:
				p66 := p59
				if v7 != 0 {
					p66 = t60
				}
				v1 = p66
				var p67 int32
				if v1 == 0 {
					p67 = 1
				}
				v3 = p67
				if v3 == 0 {
					memory_copy(*m.memory, uint32(v6+i32(96)), uint32(v4), uint32(v1))
				}
				m._sqlite3_free(v4)
				v4 = v6 + i32(96)
				(*m.memory)[uint32(v4+v1)] = byte(i32(0))
				if v3 == 0 {
					memory_copy(*m.memory, uint32(v6-i32(-64)), uint32(v4), uint32(v1))
				}
				v3 = v6 - i32(-64)
				store16((*m.memory)[uint32(v3+v1):], uint16(i32(90)))
				v4 = i32(7)
				t68 := m._sqlite3_bind_text(v8, i32(1), v6+i32(96), i32(-1), i32(0))
				if t68 == i32(7) {
					goto l7
				}
				t69 := m._sqlite3_bind_text(v8, i32(2), v3, i32(-1), i32(0))
				if t69 == i32(7) {
					goto l7
				}
				v11 = v1 + i32(1)
				v3 = i32(-1)
				v7 = i32(0)
				var p70 int32
			l11:
				{
					t71 := m._sqlite3_step(v8)
					if t71 != i32(100) {
						goto l9
					}
					store32((*m.memory)[int64(uint32(v6))+60:], uint32(i32(-1)))
					t72 := m._sqlite3_column_int(v8, i32(2))
					v9 = t72
					var p73 int32
					{
						if v13 != 0 {
							t74 := m._sqlite3_column_bytes(v8, i32(1))
							v1 = t74
							t75 := m._sqlite3_column_text(v8, i32(1))
							t76 := m._editDist3Core(v13, t75, v1, v16, v6+i32(60))
							p73 = t76
							goto l10
						}
						t77 := m._sqlite3_column_text(v8, i32(3))
						v1 = t77
						if v1 == 0 {
							goto l11
						}
						t78 := m._editdist1(v10, v1, i32(0))
						p73 = t78
					}
				l10:
					v5 = p73
					if v5 < i32(0) {
						p79 := i32(7)
						if v5 == i32(-4) {
							p79 = i32(18)
						}
						p70 = p79
						goto l12
					}
					t80 := int32(load32((*m.memory)[int64(uint32(v0))+40:]))
					store32((*m.memory)[int64(uint32(v0))+40:], uint32(t80+i32(1)))
					{
						if v12 < i32(0) {
							goto l13
						}
						if uint32(v5) > uint32(v12) {
							goto l11
						}
						t81 := int32(load32((*m.memory)[int64(uint32(v0))+20:]))
						v1 = t81
						t82 := int32(load32((*m.memory)[int64(uint32(v0))+16:]))
						if v1 > t82 {
							goto l13
						}
						t83 := int32((*m.memory)[int64(uint32(v0))+12])
						if t83&i32(4) != 0 {
							goto l13
						}
						m._spellfix1ResizeCursor(v0, v1<<1+i32(10))
						t84 := int32(load32((*m.memory)[int64(uint32(v0))+48:]))
						if t84 == 0 {
							goto l9
						}
					}
				l13:
					v4 = v5 + i32(32)
					v1 = v9
				l14:
					if v1 > i32(0) {
						v4 = v4 - i32(1)
						v1 = int32(uint32(v1) >> 1)
						goto l14
					}
					t85 := int32(load32((*m.memory)[int64(uint32(v0))+16:]))
					v1 = t85
					t86 := int32(load32((*m.memory)[int64(uint32(v0))+20:]))
					if v1 >= t86 {
						if v4 >= v7 {
							goto l11
						}
						t87 := int32(load32((*m.memory)[int64(uint32(v0))+48:]))
						t88 := int32(load32((*m.memory)[int64(uint32(t87+v3<<6))+8:]))
						m._sqlite3_free(t88)
						v1 = v3
					}
					t89 := m._sqlite3_column_text(v8, i32(1))
					store32((*m.memory)[int64(uint32(v6))+16:], uint32(t89))
					t90 := m._sqlite3_mprintf(m.___memory_base+i32(100), v6+i32(16))
					v14 = t90
					v1 = v1 << 6
					t91 := int32(load32((*m.memory)[int64(uint32(v0))+48:]))
					store32((*m.memory)[int64(uint32(v1+t91))+8:], uint32(v14))
					if v14 == 0 {
						p70 = i32(7)
						goto l12
					}
					t92 := m._sqlite3_column_int64(v8, i32(0))
					v17 = t92
					t93 := int32(load32((*m.memory)[int64(uint32(v0))+48:]))
					v1 = t93 + v1
					store32((*m.memory)[int64(uint32(v1))+20:], uint32(v4))
					store32((*m.memory)[int64(uint32(v1))+16:], uint32(v5))
					store32((*m.memory)[int64(uint32(v1))+12:], uint32(v9))
					store64((*m.memory)[uint32(v1):], uint64(v17))
					t94 := int32(load32((*m.memory)[int64(uint32(v6))+60:]))
					store32((*m.memory)[int64(uint32(v1))+24:], uint32(t94))
					if v11 != 0 {
						memory_copy(*m.memory, uint32(v1+i32(28)), uint32(v6+i32(96)), uint32(v11))
					}
					t95 := int32(load32((*m.memory)[int64(uint32(v0))+16:]))
					v1 = t95
					t96 := int32(load32((*m.memory)[int64(uint32(v0))+20:]))
					t97 := v1
					v4 = t96
					if t97 < v4 {
						t98 := v0
						v1 = v1 + i32(1)
						store32((*m.memory)[int64(uint32(t98))+16:], uint32(v1))
					}
					if v1 != v4 {
						goto l11
					}
					v1 = i32(1)
					p99 := v4
					if v4 <= i32(1) {
						p99 = i32(1)
					}
					v9 = p99
					t100 := int32(load32((*m.memory)[int64(uint32(v0))+48:]))
					v3 = t100
					v4 = v3 + i32(84)
					t101 := int32(load32((*m.memory)[int64(uint32(v3))+20:]))
					v7 = t101
					v3 = i32(0)
				l15:
					{
						if v1 == v9 {
							goto l11
						}
						t102 := int32(load32((*m.memory)[uint32(v4):]))
						t103 := v1
						t104 := v3
						v5 = t102
						p105 := t104
						if v5 > v7 {
							p105 = t103
						}
						v3 = p105
						v4 = v4 - i32(-64)
						v1 = v1 + i32(1)
						p106 := v5
						if v5 < v7 {
							p106 = v7
						}
						v7 = p106
						goto l15
					}
				}
			l9:
				p70 = i32(0)
			l12:
				v1 = p70
				t107 := m._sqlite3_reset(v8)
				v3 = t107
				p108 := v1
				if v3 != 0 {
					p108 = v3
				}
				v4 = p108
			}
		l7:
			t109 := int32(load32((*m.memory)[int64(uint32(v0))+48:]))
			v8 = t109
			if v8 == 0 {
				goto l5
			}
			v10 = m.___table_base + i32(7)
			t110 := int32(load32((*m.memory)[int64(uint32(v0))+16:]))
			v7 = t110
			v11 = v7 << 6
		l16:
			if uint32(v7) >= uint32(i32(2)) {
				t111 := int64(uint64(int64(uint32(v7))*i64(5)-i64(1)) / uint64(i64(11)))
				p112 := int32(t111)
				if v7 == i32(2) {
					p112 = i32(1)
				}
				v7 = p112
				v12 = v7 << 6
				v3 = v12
			l20:
				if uint32(v3) >= uint32(v11) {
					goto l16
				}
				v1 = v3
			l19:
				{
					v2 = v1 - v12
					if uint32(v2) > uint32(v1) {
						goto l17
					}
					t113 := v12
					v1 = v2 + v8
					v5 = t113 + v1
					t114 := (*m.t0)[uint(v10)].(func(int32, int32) int32)(v1, v5)
					if t114 <= i32(0) {
						goto l17
					}
					v9 = i32(64)
				l18:
					{
						t115 := int32((*m.memory)[uint32(v1)])
						v14 = t115
						t116 := int32((*m.memory)[uint32(v5)])
						(*m.memory)[uint32(v1)] = byte(t116)
						(*m.memory)[uint32(v5)] = byte(v14)
						v5 = v5 + i32(1)
						v1 = v1 + i32(1)
						v9 = v9 - i32(1)
						if v9 != 0 {
							goto l18
						}
					}
					v1 = v2
					goto l19
				}
			l17:
				v3 = v3 - i32(-64)
				goto l20
			}
			store32((*m.memory)[int64(uint32(v0))+36:], uint32(i32(3)))
			store32((*m.memory)[int64(uint32(v0))+32:], uint32(v15))
			v2 = v4
		}
	l5:
		t117 := int32(load32((*m.memory)[int64(uint32(v6))+56:]))
		_ = m._sqlite3_finalize(t117)
		m._editDist3FromStringDelete(v13)
		goto l2
	}
l3:
	v2 = i32(0)
	goto l2
l1:
	v2 = i32(7)
l2:
	*m.___stack_pointer = v6 + i32(128)
	return v2
}
func (m *Module) _editDist3ConfigLoad(v0, v1, v2 int32) int32 {
	var v3, v4, v5, v6, v7, v8, v9, v10 int32
	t0 := *m.___stack_pointer
	v4 = t0 - i32(256)
	*m.___stack_pointer = v4
	store32((*m.memory)[uint32(v4):], uint32(v2))
	{
		t1 := m._sqlite3_mprintf(m.___memory_base+i32(128), v4)
		v2 = t1
		if v2 == 0 {
			v7 = i32(7)
			goto l0
		}
		t2 := m._sqlite3_prepare(v1, v2, i32(-1), v4+i32(12), i32(0))
		v7 = t2
		m._sqlite3_free(v2)
		if v7 != 0 {
			goto l0
		}
		m._editDist3ConfigClear(v0)
		v7 = i32(-9999)
		var p3 int32
	l2:
		{
			t4 := int32(load32((*m.memory)[int64(uint32(v4))+12:]))
			t5 := m._sqlite3_step(t4)
			v10 = t5
			if v10 != i32(100) {
				p3 = i32(0)
				goto l1
			}
			v1 = i32(0)
			t6 := int32(load32((*m.memory)[int64(uint32(v4))+12:]))
			t7 := m._sqlite3_column_int(t6, i32(0))
			v3 = t7
			v2 = i32(0)
			t8 := int32(load32((*m.memory)[int64(uint32(v4))+12:]))
			t9 := m._sqlite3_column_text(t8, i32(1))
			v9 = t9
			if v9 != 0 {
				t10 := int32(load32((*m.memory)[int64(uint32(v4))+12:]))
				t11 := m._sqlite3_column_bytes(t10, i32(1))
				v2 = t11
			}
			t12 := int32(load32((*m.memory)[int64(uint32(v4))+12:]))
			t13 := m._sqlite3_column_text(t12, i32(2))
			v8 = t13
			if v8 != 0 {
				t14 := int32(load32((*m.memory)[int64(uint32(v4))+12:]))
				t15 := m._sqlite3_column_bytes(t14, i32(2))
				v1 = t15
			}
			t16 := int32(load32((*m.memory)[int64(uint32(v4))+12:]))
			t17 := m._sqlite3_column_int(t16, i32(3))
			v6 = t17
			if v2 > i32(100) {
				goto l2
			}
			if v1 > i32(100) {
				goto l2
			}
			if uint32(v6) > uint32(i32(9999)) {
				goto l2
			}
			{
				var p18 int32
				if v3 == v7 {
					p18 = 1
				}
				var p19 int32
				if v5 != i32(0) {
					p19 = 1
				}
				if p18&p19 == 0 {
					t20 := int32(load32((*m.memory)[int64(uint32(v0))+4:]))
					t21 := int64(int32(load32((*m.memory)[uint32(v0):])))
					t22 := m._sqlite3_realloc64(t20, t21*i64(20)+i64(20))
					v5 = t22
					if v5 == 0 {
						goto l3
					}
					store32((*m.memory)[int64(uint32(v0))+4:], uint32(v5))
					t23 := int32(load32((*m.memory)[uint32(v0):]))
					t24 := v0
					v7 = t23
					store32((*m.memory)[uint32(t24):], uint32(v7+i32(1)))
					v5 = v5 + v7*i32(20)
					store64((*m.memory)[int64(uint32(v5))+12:], uint64(i64(150)))
					store64((*m.memory)[int64(uint32(v5))+4:], uint64(i64(0x6400000064)))
					store32((*m.memory)[uint32(v5):], uint32(v3))
					v7 = v3
				}
				{
					{
						if v2 == i32(1) {
							t25 := int32((*m.memory)[uint32(v9)])
							var p26 int32
							if t25 != i32(63) {
								p26 = 1
							}
							v3 = p26
							if v3 != 0 {
								goto l4
							}
							if v1 != 0 {
								goto l4
							}
							store32((*m.memory)[int64(uint32(v5))+8:], uint32(v6))
							goto l2
						}
						if v2 != 0 {
							goto l5
						}
						if v1 != i32(1) {
							goto l5
						}
						t27 := int32((*m.memory)[uint32(v8)])
						if t27 != i32(63) {
							goto l5
						}
						store32((*m.memory)[int64(uint32(v5))+4:], uint32(v6))
						goto l2
					}
				l4:
					if v1 != i32(1) {
						goto l5
					}
					if v3 != 0 {
						goto l5
					}
					t28 := int32((*m.memory)[uint32(v8)])
					if t28 != i32(63) {
						goto l5
					}
					store32((*m.memory)[int64(uint32(v5))+12:], uint32(v6))
					goto l2
				}
			l5:
				v3 = v1 + v2
				p29 := v3
				if v3 <= i32(4) {
					p29 = i32(4)
				}
				t30 := m._sqlite3_malloc64(int64(uint32(p29 + i32(8))))
				v3 = t30
				if v3 == 0 {
					goto l3
				}
				store16((*m.memory)[int64(uint32(v3))+6:], uint16(v6))
				(*m.memory)[int64(uint32(v3))+5] = byte(v1)
				(*m.memory)[int64(uint32(v3))+4] = byte(v2)
				v6 = v3 + i32(8)
				if v2 != 0 {
					memory_copy(*m.memory, uint32(v6), uint32(v9), uint32(v2))
				}
				if v1 != 0 {
					memory_copy(*m.memory, uint32(v2+v6), uint32(v8), uint32(v1))
				}
				t31 := int32(load32((*m.memory)[int64(uint32(v5))+16:]))
				store32((*m.memory)[uint32(v3):], uint32(t31))
				store32((*m.memory)[int64(uint32(v5))+16:], uint32(v3))
				goto l2
			}
		l3:
		}
		p3 = i32(7)
	l1:
		t32 := int32(load32((*m.memory)[int64(uint32(v4))+12:]))
		t33 := m._sqlite3_finalize(t32)
		p34 := t33
		if v10 == i32(100) {
			p34 = p3
		}
		v7 = p34
		if v7 != 0 {
			goto l0
		}
		v7 = i32(0)
		v8 = i32(0)
	l9:
		{
			t35 := int32(load32((*m.memory)[uint32(v0):]))
			if v8 >= t35 {
				goto l0
			}
			v9 = v8 * i32(20)
			t36 := int32(load32((*m.memory)[int64(uint32(v0))+4:]))
			t37 := int32(load32((*m.memory)[int64(uint32(v9+t36))+16:]))
			v1 = t37
			store64((*m.memory)[int64(uint32(v4))+16:], uint64(i64(0)))
			v5 = i32(0)
		l7:
			if v1 != 0 {
				t38 := int32(load32((*m.memory)[uint32(v1):]))
				v3 = i32(0)
				store32((*m.memory)[uint32(v1):], uint32(i32(0)))
				v2 = v4 + i32(16)
			l6:
				{
					t39 := int32(load32((*m.memory)[uint32(v2):]))
					v10 = t39
					if v10 != 0 {
						t40 := m._editDist3CostMerge(v10, v1)
						v1 = t40
						store32((*m.memory)[uint32(v2):], uint32(i32(0)))
						v2 = v2 + i32(4)
						v3 = v3 + i32(1)
						goto l6
					}
				}
				store32((*m.memory)[uint32(v2):], uint32(v1))
				v1 = t38
				if uint32(v3) <= uint32(v5) {
					goto l7
				}
				store32((*m.memory)[int64(uint32(v2))+4:], uint32(i32(0)))
				v5 = v3
				goto l7
			}
			v2 = i32(0)
			v1 = v4 + i32(16)
			v3 = i32(0)
		l8:
			if uint32(v2) <= uint32(v5) {
				t41 := int32(load32((*m.memory)[uint32(v1):]))
				v6 = t41
				if v6 != 0 {
					t42 := m._editDist3CostMerge(v3, v6)
					v3 = t42
				}
				v1 = v1 + i32(4)
				v2 = v2 + i32(1)
				goto l8
			}
			t43 := int32(load32((*m.memory)[int64(uint32(v0))+4:]))
			store32((*m.memory)[int64(uint32(t43+v9))+16:], uint32(v3))
			v8 = v8 + i32(1)
			goto l9
		}
	}
l0:
	*m.___stack_pointer = v4 + i32(256)
	return v7
}
func (m *Module) _editDist3FindLang(v0, v1 int32) int32 {
	var v2, v3, v4, _ int32
	t0 := int32(load32((*m.memory)[uint32(v0):]))
	v2 = t0
	p1 := i32(0)
	if v2 > i32(0) {
		p1 = v2
	}
	v2 = p1 + i32(1)
l0:
	{
		v2 = v2 - i32(1)
		if v2 == 0 {
			return m.___memory_base + i32(4032)
		}
		t2 := int32(load32((*m.memory)[int64(uint32(v0))+4:]))
		v4 = t2
		t3 := v4 + v3
		v3 = v3 + i32(20)
		t4 := int32(load32((*m.memory)[uint32(t3):]))
		if t4 != v1 {
			goto l0
		}
	}
	return v3 + v4 - i32(20)
}
func (m *Module) _editDist3FromStringNew(v0, v1, v2 int32) int32 {
	var v3, v4, v5, v6, v7, v8, v9, v10 int32
	{
		if v1 == 0 {
			goto l0
		}
		if v2 < i32(0) {
			t0 := m._strlen(v1)
			v2 = t0
		}
		t1 := int64(v2)
		v6 = v2 * i32(20)
		t2 := m._sqlite3_malloc64(t1 + int64(uint32(v6+i32(16))) + i64(1))
		v4 = t2
		if v4 == 0 {
			goto l0
		}
		t3 := v4
		v3 = v4 + i32(16)
		store32((*m.memory)[int64(uint32(t3))+12:], uint32(v3))
		if v6 != 0 {
			memory_zero(*m.memory, uint32(v3), uint32(v6))
		}
		t4 := v4
		v6 = v3 + v2*i32(20)
		store32((*m.memory)[uint32(t4):], uint32(v6))
		store32((*m.memory)[int64(uint32(v4))+4:], uint32(v2))
		v3 = v2 + i32(1)
		if v3 != 0 {
			memory_copy(*m.memory, uint32(v6), uint32(v1), uint32(v3))
		}
		{
			if v2 == 0 {
				goto l1
			}
			t5 := int32((*m.memory)[uint32(v1+v2-i32(1))])
			if t5 != i32(42) {
				goto l1
			}
			store32((*m.memory)[int64(uint32(v4))+8:], uint32(i32(1)))
			t6 := int32(load32((*m.memory)[int64(uint32(v4))+4:]))
			store32((*m.memory)[int64(uint32(v4))+4:], uint32(t6-i32(1)))
			v2 = v2 - i32(1)
			t7 := int32(load32((*m.memory)[uint32(v4):]))
			(*m.memory)[uint32(v2+t7)] = byte(i32(0))
			goto l2
		}
	l1:
		store32((*m.memory)[int64(uint32(v4))+8:], uint32(i32(0)))
	l2:
		p8 := i32(0)
		if v2 > i32(0) {
			p8 = v2
		}
		v10 = p8
		v6 = v0 + i32(16)
	l5:
		{
			if v7 == v10 {
				return v4
			}
			t9 := int32(load32((*m.memory)[int64(uint32(v4))+12:]))
			v3 = t9 + v7*i32(20)
			store32((*m.memory)[int64(uint32(v3))+16:], uint32(i32(0)))
			store64((*m.memory)[int64(uint32(v3))+8:], uint64(i64(0)))
			store64((*m.memory)[uint32(v3):], uint64(i64(0)))
			t10 := v3
			v9 = v1 + v7
			t11 := int32((*m.memory)[uint32(v9)])
			t12 := _utf8Len(t11, v2-v7)
			store32((*m.memory)[int64(uint32(t10))+8:], uint32(t12))
			v0 = v6
		l3:
			{
				t13 := int32(load32((*m.memory)[uint32(v0):]))
				v0 = t13
				if v0 != 0 {
					t14 := int32((*m.memory)[int64(uint32(v0))+4])
					v5 = t14
					if v5+v7 > v2 {
						goto l3
					}
					if v5 != 0 {
						t15 := int32((*m.memory)[int64(uint32(v0))+8])
						t16 := int32((*m.memory)[uint32(v9)])
						if t15 != t16 {
							goto l3
						}
						t17 := m._strncmp(v0+i32(8), v9, v5)
						if t17 != 0 {
							goto l3
						}
					}
					t18 := int32((*m.memory)[int64(uint32(v0))+5])
					if t18 == 0 {
						t19 := int32(load32((*m.memory)[int64(uint32(v3))+16:]))
						t20 := int64(int32(load32((*m.memory)[int64(uint32(v3))+4:])))
						t21 := m._sqlite3_realloc64(t19, t20<<2+i64(4))
						v5 = t21
						if v5 == 0 {
							goto l4
						}
						store32((*m.memory)[int64(uint32(v3))+16:], uint32(v5))
						t22 := int32(load32((*m.memory)[int64(uint32(v3))+4:]))
						t23 := v3
						v8 = t22
						store32((*m.memory)[int64(uint32(t23))+4:], uint32(v8+i32(1)))
						store32((*m.memory)[uint32(v5+v8<<2):], uint32(v0))
						goto l3
					}
					t24 := int32(load32((*m.memory)[int64(uint32(v3))+12:]))
					t25 := int64(int32(load32((*m.memory)[uint32(v3):])))
					t26 := m._sqlite3_realloc64(t24, t25<<2+i64(4))
					v5 = t26
					if v5 == 0 {
						goto l4
					}
					store32((*m.memory)[int64(uint32(v3))+12:], uint32(v5))
					t27 := int32(load32((*m.memory)[uint32(v3):]))
					t28 := v3
					v8 = t27
					store32((*m.memory)[uint32(t28):], uint32(v8+i32(1)))
					store32((*m.memory)[uint32(v5+v8<<2):], uint32(v0))
					goto l3
				}
			}
			v7 = v7 + i32(1)
			goto l5
		l4:
		}
		m._editDist3FromStringDelete(v4)
	}
l0:
	return i32(0)
}
func (m *Module) _editDist3Core(v0, v1, v2, v3, v4 int32) int32 {
	var v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27, v28, v29, v30, v31 int32
	t0 := *m.___stack_pointer
	v19 = t0 - i32(1024)
	*m.___stack_pointer = v19
	v5 = i32(-2)
	{
		if v2 > i32(10000) {
			goto l0
		}
		t1 := int32(load32((*m.memory)[int64(uint32(v0))+4:]))
		v14 = t1
		if v14 > i32(10000) {
			goto l0
		}
		t2 := int32(load32((*m.memory)[int64(uint32(v0))+12:]))
		v20 = t2
		t3 := int32(load32((*m.memory)[int64(uint32(v0))+8:]))
		v25 = t3
		t4 := int32(load32((*m.memory)[uint32(v0):]))
		v26 = t4
		v11 = v19
		{
			v15 = v14 + i32(1)
			v21 = v15 * (v2 + i32(1))
			v27 = v21 + i32(1)
			v5 = v27 & i32(-2) << 2
			t5 := v5
			v0 = v2 * i32(12)
			v9 = t5 + v0
			if uint32(v9) < uint32(i32(1025)) {
				goto l1
			}
			t6 := m._sqlite3_malloc64(int64(uint32(v9)))
			v28 = t6
			v11 = v28
			if v11 != 0 {
				goto l1
			}
			v5 = i32(-1)
			goto l0
		}
	l1:
		v16 = v5 + v11
		if v0 != 0 {
			memory_zero(*m.memory, uint32(v16), uint32(v0))
		}
		p7 := i32(0)
		if v2 > i32(0) {
			p7 = v2
		}
		v13 = p7
		v5 = v3 + i32(16)
	l5:
		if v6 != v13 {
			v9 = v16 + v6*i32(12)
			t8 := v9
			v8 = v1 + v6
			t9 := int32((*m.memory)[uint32(v8)])
			v10 = v2 - v6
			t10 := _utf8Len(t9, v10)
			store32((*m.memory)[int64(uint32(t8))+4:], uint32(t10))
			v0 = v5
		l3:
			{
				t11 := int32(load32((*m.memory)[uint32(v0):]))
				v0 = t11
				if v0 == 0 {
					goto l2
				}
				t12 := int32((*m.memory)[int64(uint32(v0))+4])
				if t12 != 0 {
					goto l2
				}
				t13 := int32((*m.memory)[int64(uint32(v0))+5])
				if v6+t13 > v2 {
					goto l3
				}
				t14 := int32(int8((*m.memory)[int64(uint32(v0))+8]))
				t15 := int32(int8((*m.memory)[uint32(v8)]))
				if t14 > t15 {
					goto l2
				}
				t16 := m._matchTo(v0, v8, v10)
				if t16 == 0 {
					goto l3
				}
				t17 := int32(load32((*m.memory)[uint32(v9):]))
				t18 := v9
				v7 = t17 + i32(1)
				store32((*m.memory)[uint32(t18):], uint32(v7))
				t19 := int32(load32((*m.memory)[int64(uint32(v9))+8:]))
				t20 := m._sqlite3_realloc64(t19, int64(uint32(v7<<2)))
				v7 = t20
				if v7 != 0 {
					store32((*m.memory)[int64(uint32(v9))+8:], uint32(v7))
					t21 := int32(load32((*m.memory)[uint32(v9):]))
					store32((*m.memory)[uint32(v7+t21<<2-i32(4)):], uint32(v0))
					goto l3
				} else {
					v5 = i32(-1)
					goto l4
				}
			}
		l2:
			v6 = v6 + i32(1)
			goto l5
		}
		v0 = v21 << 2
		if v0 != 0 {
			memory_fill(*m.memory, uint32(v11), i32(1), uint32(v0))
		}
		v6 = i32(0)
		store32((*m.memory)[uint32(v11):], uint32(i32(0)))
	l16:
		{
			if v6 >= v14 {
				v6 = i32(0)
			l6:
				if v2 > v6 {
					v23 = v11 + v6*v15<<2
					t22 := int32(load32((*m.memory)[uint32(v23):]))
					t23 := int32(load32((*m.memory)[int64(uint32(v3))+4:]))
					v0 = t22 + t23
					t24 := v0
					t25 := v11
					v8 = v16 + v6*i32(12)
					t26 := int32(load32((*m.memory)[int64(uint32(v8))+4:]))
					v9 = t26 + v6
					v22 = t25 + v9*v15<<2
					t27 := int32(load32((*m.memory)[uint32(v22):]))
					if uint32(t24) < uint32(t27) {
						store32((*m.memory)[uint32(v22):], uint32(v0))
					}
					v5 = i32(0)
					v0 = i32(0)
				l12:
					{
						t28 := int32(load32((*m.memory)[uint32(v8):]))
						if t28 <= v0 {
							v24 = v2 - v6
							v17 = v1 + v6
							v8 = i32(0)
						l11:
							{
								if v8 >= v14 {
									v6 = v9
									goto l6
								}
								v29 = v8 << 2
								v0 = v29 + v22
								t29 := int32(load32((*m.memory)[uint32(v0):]))
								t30 := int32(load32((*m.memory)[int64(uint32(v3))+8:]))
								v5 = t29 + t30
								t31 := v5
								t32 := v0
								v10 = v20 + v8*i32(20)
								t33 := int32(load32((*m.memory)[int64(uint32(v10))+8:]))
								v30 = t33
								v31 = v30 << 2
								v7 = t32 + v31
								t34 := int32(load32((*m.memory)[uint32(v7):]))
								if uint32(t31) < uint32(t34) {
									store32((*m.memory)[uint32(v7):], uint32(v5))
								}
								v6 = i32(0)
								v5 = i32(0)
							l7:
								{
									t35 := int32(load32((*m.memory)[int64(uint32(v10))+4:]))
									if t35 > v5 {
										t36 := int32(load32((*m.memory)[uint32(v0):]))
										t37 := int32(load32((*m.memory)[int64(uint32(v10))+16:]))
										t38 := int32(load32((*m.memory)[uint32(t37+v6):]))
										v18 = t38
										t39 := int32(load16((*m.memory)[int64(uint32(v18))+6:]))
										v12 = t36 + t39
										t40 := int32((*m.memory)[int64(uint32(v18))+4])
										t41 := v12
										v18 = v0 + t40<<2
										t42 := int32(load32((*m.memory)[uint32(v18):]))
										if uint32(t41) < uint32(t42) {
											store32((*m.memory)[uint32(v18):], uint32(v12))
										}
										v6 = v6 + i32(4)
										v5 = v5 + i32(1)
										goto l7
									}
								}
								t43 := int32(load32((*m.memory)[uint32(v7):]))
								v5 = t43
								t44 := v5
								v12 = v23 + v29
								t45 := int32(load32((*m.memory)[uint32(v12+v31):]))
								t46 := int32(load32((*m.memory)[int64(uint32(v3))+4:]))
								v0 = t45 + t46
								if uint32(t44) > uint32(v0) {
									store32((*m.memory)[uint32(v7):], uint32(v0))
									v5 = v0
								}
								{
									t47 := int32(load32((*m.memory)[int64(uint32(v10))+8:]))
									v0 = t47
									if v0 > v24 {
										goto l8
									}
									v6 = v8 + v26
									t48 := int32((*m.memory)[uint32(v6)])
									t49 := int32((*m.memory)[uint32(v17)])
									if t48 != t49 {
										goto l8
									}
									t50 := m._strncmp(v6, v17, v0)
									t51 := int32(load32((*m.memory)[uint32(v7):]))
									v5 = t51
									if t50 != 0 {
										goto l8
									}
									t52 := int32(load32((*m.memory)[uint32(v12):]))
									v0 = t52
									if uint32(v0) >= uint32(v5) {
										goto l8
									}
									store32((*m.memory)[uint32(v7):], uint32(v0))
									v5 = v0
								}
							l8:
								t53 := int32(load32((*m.memory)[uint32(v12):]))
								t54 := int32(load32((*m.memory)[int64(uint32(v3))+12:]))
								v0 = t53 + t54
								if uint32(v0) < uint32(v5) {
									store32((*m.memory)[uint32(v7):], uint32(v0))
								}
								v6 = i32(0)
								v5 = i32(0)
							l10:
								{
									t55 := int32(load32((*m.memory)[uint32(v10):]))
									if t55 > v5 {
										{
											t56 := int32(load32((*m.memory)[int64(uint32(v10))+12:]))
											t57 := int32(load32((*m.memory)[uint32(t56+v6):]))
											v0 = t57
											t58 := m._matchTo(v0, v17, v24)
											if t58 == 0 {
												goto l9
											}
											t59 := int32(load32((*m.memory)[uint32(v12):]))
											t60 := int32(load16((*m.memory)[int64(uint32(v0))+6:]))
											v7 = t59 + t60
											t61 := int32((*m.memory)[int64(uint32(v0))+4])
											t62 := int32((*m.memory)[int64(uint32(v0))+5])
											t63 := v7
											v0 = v12 + t61<<2 + v15*t62<<2
											t64 := int32(load32((*m.memory)[uint32(v0):]))
											if uint32(t63) >= uint32(t64) {
												goto l9
											}
											store32((*m.memory)[uint32(v0):], uint32(v7))
										}
									l9:
										v6 = v6 + i32(4)
										v5 = v5 + i32(1)
										goto l10
									}
								}
								v8 = v8 + v30
								goto l11
							}
						} else {
							t65 := int32(load32((*m.memory)[uint32(v23):]))
							t66 := int32(load32((*m.memory)[int64(uint32(v8))+8:]))
							t67 := int32(load32((*m.memory)[uint32(t66+v5):]))
							v10 = t67
							t68 := int32(load16((*m.memory)[int64(uint32(v10))+6:]))
							v7 = t65 + t68
							t69 := int32((*m.memory)[int64(uint32(v10))+5])
							t70 := v7
							v10 = v11 + (v6+t69)*v15<<2
							t71 := int32(load32((*m.memory)[uint32(v10):]))
							if uint32(t70) < uint32(t71) {
								store32((*m.memory)[uint32(v10):], uint32(v7))
							}
							v5 = v5 + i32(4)
							v0 = v0 + i32(1)
							goto l12
						}
					}
				}
				t72 := int32(load32((*m.memory)[uint32(v11+v21<<2-i32(4)):]))
				v5 = t72
				if v25 == 0 {
					goto l13
				}
				v0 = v14 << 2
				v8 = v0 + i32(4)
				v6 = v0 + v11
				v0 = v13
				v3 = i32(1)
			l14:
				{
					if v0 == 0 {
						goto l13
					}
					t73 := int32(load32((*m.memory)[uint32(v6):]))
					t74 := v2
					t75 := v3 - i32(1)
					v9 = t73
					p76 := t75
					if v9 > v5 {
						p76 = t74
					}
					v2 = p76
					p77 := v5
					if v5 > v9 {
						p77 = v9
					}
					v5 = p77
					v0 = v0 - i32(1)
					v6 = v6 + v8
					v3 = v3 + i32(1)
					goto l14
				}
			l13:
				if v4 == 0 {
					goto l4
				}
				v6 = i32(0)
				p78 := i32(0)
				if v2 > i32(0) {
					p78 = v2
				}
				v0 = p78
			l15:
				if v0 != 0 {
					v0 = v0 - i32(1)
					t79 := int32(int8((*m.memory)[uint32(v1)]))
					t80 := v6
					var p81 int32
					if t79 < i32(-64) {
						p81 = 1
					}
					v6 = t80 + p81
					v1 = v1 + i32(1)
					goto l15
				}
				store32((*m.memory)[uint32(v4):], uint32(v2-v6))
				goto l4
			}
			v9 = v11 + v6<<2
			t82 := int32(load32((*m.memory)[uint32(v9):]))
			t83 := int32(load32((*m.memory)[int64(uint32(v3))+8:]))
			v0 = t82 + t83
			t84 := v0
			t85 := v11
			v8 = v20 + v6*i32(20)
			t86 := int32(load32((*m.memory)[int64(uint32(v8))+8:]))
			v6 = t86 + v6
			v5 = t85 + v6<<2
			t87 := int32(load32((*m.memory)[uint32(v5):]))
			if uint32(t84) < uint32(t87) {
				store32((*m.memory)[uint32(v5):], uint32(v0))
			}
			v5 = i32(0)
			v0 = i32(0)
		l17:
			{
				t88 := int32(load32((*m.memory)[int64(uint32(v8))+4:]))
				if v0 >= t88 {
					goto l16
				}
				t89 := int32(load32((*m.memory)[uint32(v9):]))
				t90 := int32(load32((*m.memory)[int64(uint32(v8))+16:]))
				t91 := int32(load32((*m.memory)[uint32(t90+v5):]))
				v10 = t91
				t92 := int32(load16((*m.memory)[int64(uint32(v10))+6:]))
				v7 = t89 + t92
				t93 := int32((*m.memory)[int64(uint32(v10))+4])
				t94 := v7
				v10 = v9 + t93<<2
				t95 := int32(load32((*m.memory)[uint32(v10):]))
				if uint32(t94) < uint32(t95) {
					store32((*m.memory)[uint32(v10):], uint32(v7))
				}
				v5 = v5 + i32(4)
				v0 = v0 + i32(1)
				goto l17
			}
		}
	l4:
		v0 = v27<<2&i32(-8) + v11 + i32(8)
	l18:
		if v13 != 0 {
			t96 := int32(load32((*m.memory)[uint32(v0):]))
			m._sqlite3_free(t96)
			v13 = v13 - i32(1)
			v0 = v0 + i32(12)
			goto l18
		}
		m._sqlite3_free(v28)
	}
l0:
	*m.___stack_pointer = v19 + i32(1024)
	return v5
}
func (m *Module) _spellfix1RowCompare(v0, v1 int32) int32 {
	t0 := int32(load32((*m.memory)[int64(uint32(v0))+20:]))
	t1 := int32(load32((*m.memory)[int64(uint32(v1))+20:]))
	return t0 - t1
}
func (m *Module) _editDist3FromStringDelete(v0 int32) {
	var v1, v2 int32
	if v0 != 0 {
		v1 = i32(16)
	l0:
		{
			t0 := int32(load32((*m.memory)[int64(uint32(v0))+4:]))
			if t0 > v2 {
				t1 := int32(load32((*m.memory)[int64(uint32(v0))+12:]))
				t2 := int32(load32((*m.memory)[uint32(t1+v1):]))
				m._sqlite3_free(t2)
				t3 := int32(load32((*m.memory)[int64(uint32(v0))+12:]))
				t4 := int32(load32((*m.memory)[uint32(t3+v1-i32(4)):]))
				m._sqlite3_free(t4)
				v1 = v1 + i32(20)
				v2 = v2 + i32(1)
				goto l0
			}
		}
		m._sqlite3_free(v0)
	}
}
func (m *Module) _spellfix1Next(v0 int32) int32 {
	var v1, v2 int32
	t0 := int32(load32((*m.memory)[int64(uint32(v0))+24:]))
	v1 = t0
	t1 := int32(load32((*m.memory)[int64(uint32(v0))+16:]))
	if v1 < t1 {
		t2 := int32(load32((*m.memory)[int64(uint32(v0))+44:]))
		v2 = t2
		if v2 != 0 {
			t3 := m._sqlite3_step(v2)
			v1 = t3
			if v1 != i32(100) {
				t4 := int32(load32((*m.memory)[int64(uint32(v0))+16:]))
				store32((*m.memory)[int64(uint32(v0))+24:], uint32(t4))
			}
			p5 := i32(0)
			if v1&i32(-2) != i32(100) {
				p5 = v1
			}
			return p5
		}
		store32((*m.memory)[int64(uint32(v0))+24:], uint32(v1+i32(1)))
	}
	return i32(0)
}
func (m *Module) _spellfix1Eof(v0 int32) int32 {
	t0 := int32(load32((*m.memory)[int64(uint32(v0))+24:]))
	t1 := int32(load32((*m.memory)[int64(uint32(v0))+16:]))
	var p2 int32
	if t0 >= t1 {
		p2 = 1
	}
	return p2
}
func (m *Module) _spellfix1Column(v0, v1, v2 int32) int32 {
	var v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15 int32
	t0 := *m.___stack_pointer
	v4 = t0 - i32(16)
	*m.___stack_pointer = v4
	var p1 int32
	{
		t2 := int32(load32((*m.memory)[int64(uint32(v0))+44:]))
		v3 = t2
		if v3 != 0 {
			if v2 > i32(3) {
				goto l0
			}
			t3 := m._sqlite3_column_value(v3, v2)
			m._sqlite3_result_value(v1, t3)
			goto l1
		}
		{
			{
				{
					{
						{
							{
								{
									{
										{
											switch v2 {
											case 0:
												goto l2
											case 1:
												goto l3
											case 2:
												goto l4
											case 3:
												goto l5
											case 4:
												goto l6
											case 5:
												goto l7
											case 6:
												goto l8
											case 7:
												goto l9
											case 8:
												goto l10
											case 9:
												goto l11
											default:
												goto l0
											}
										l2:
											t4 := int32(load32((*m.memory)[int64(uint32(v0))+48:]))
											t5 := int32(load32((*m.memory)[int64(uint32(v0))+24:]))
											t6 := int32(load32((*m.memory)[int64(uint32(t4+t5<<6))+8:]))
											m._sqlite3_result_text(v1, t6, i32(-1), i32(0))
											p1 = i32(0)
											goto l12
										}
									l3:
										t7 := int32(load32((*m.memory)[int64(uint32(v0))+48:]))
										t8 := int32(load32((*m.memory)[int64(uint32(v0))+24:]))
										t9 := int32(load32((*m.memory)[int64(uint32(t7+t8<<6))+12:]))
										m._sqlite3_result_int(v1, t9)
										goto l1
									}
								l4:
									t10 := int32(load32((*m.memory)[int64(uint32(v0))+48:]))
									t11 := int32(load32((*m.memory)[int64(uint32(v0))+24:]))
									t12 := int32(load32((*m.memory)[int64(uint32(t10+t11<<6))+16:]))
									m._sqlite3_result_int(v1, t12)
									goto l1
								}
							l5:
								t13 := int32(load32((*m.memory)[int64(uint32(v0))+28:]))
								m._sqlite3_result_int(v1, t13)
								goto l1
							}
						l6:
							t14 := int32(load32((*m.memory)[int64(uint32(v0))+48:]))
							t15 := int32(load32((*m.memory)[int64(uint32(v0))+24:]))
							t16 := int32(load32((*m.memory)[int64(uint32(t14+t15<<6))+20:]))
							m._sqlite3_result_int(v1, t16)
							goto l1
						}
					l7:
						t17 := int32(load32((*m.memory)[int64(uint32(v0))+48:]))
						t18 := int32(load32((*m.memory)[int64(uint32(v0))+24:]))
						t19 := int32(load32((*m.memory)[int64(uint32(t17+t18<<6))+24:]))
						t20 := v4
						v5 = t19
						store32((*m.memory)[int64(uint32(t20))+4:], uint32(v5))
						if v5 >= i32(0) {
							goto l13
						}
						v5 = i32(0)
						t21 := int32(load32((*m.memory)[int64(uint32(v0))+8:]))
						t22 := m._strlen(t21)
						v2 = t22
						t23 := int32(load32((*m.memory)[int64(uint32(v0))+48:]))
						t24 := int32(load32((*m.memory)[int64(uint32(v0))+24:]))
						t25 := int32(load32((*m.memory)[int64(uint32(t23+t24<<6))+8:]))
						v9 = t25
						t26 := m._strlen(v9)
						v6 = t26
						if v2 <= i32(0) {
							goto l14
						}
						t27 := int32(load32((*m.memory)[int64(uint32(v0))+8:]))
						t28 := int32((*m.memory)[uint32(t27+v2-i32(1))])
						if t28 != i32(42) {
							goto l14
						}
						t29 := m._transliterate(v9, v6)
						v3 = t29
						if v3 == 0 {
							p1 = i32(7)
							goto l12
						}
						t30 := int32(load32((*m.memory)[int64(uint32(v0))+8:]))
						t31 := m._editdist1(t30, v3, v4+i32(4))
						v0 = t31
						m._sqlite3_free(v3)
						p32 := i32(7)
						if v0 == i32(-4) {
							p32 = i32(18)
						}
						if v0 < i32(0) {
							p1 = p32
							goto l12
						}
						t33 := int32(load32((*m.memory)[int64(uint32(v4))+4:]))
						v13 = t33
						v3 = i32(0)
					l19:
						{
							if v6 <= v8 {
								goto l13
							}
							t34 := v13
							v10 = v3
							if t34 <= v10 {
								goto l13
							}
							t35 := m._utf8Read(v8+v9, v6-v8, v4+i32(8))
							v11 = t35
							v3 = v3 + i32(1)
							t36 := int32(load32((*m.memory)[int64(uint32(v4))+8:]))
							v14 = t36
							if v11 < i32(128) {
								goto l15
							}
							v0 = i32(0)
							v2 = i32(388)
						l18:
							if v0 > v2 {
								goto l15
							}
							{
								t37 := m.___memory_base + i32(1440)
								v7 = int32(uint32(v0+v2) >> 1)
								v12 = t37 + v7*i32(6)
								t38 := int32(load16((*m.memory)[uint32(v12):]))
								v15 = t38
								if v15 == v11 {
									t39 := int32((*m.memory)[int64(uint32(v12))+3])
									if t39 == 0 {
										goto l15
									}
									{
										var p40 int32
										if v7 == i32(339) {
											p40 = 1
										}
										v0 = p40
										if v0 != 0 {
											goto l16
										}
										if v7 == i32(307) {
											goto l16
										}
										v3 = v10 + i32(2)
										goto l15
									}
								l16:
									if v0 != 0 {
										goto l17
									}
									if v7 == i32(307) {
										goto l17
									}
									v3 = v10 + i32(3)
									goto l15
								}
								t41 := v0
								t42 := v7 + i32(1)
								var p43 int32
								if v11 < v15 {
									p43 = 1
								}
								v12 = p43
								p44 := t42
								if v12 != 0 {
									p44 = t41
								}
								v0 = p44
								p45 := v2
								if v12 != 0 {
									p45 = v7 - i32(1)
								}
								v2 = p45
								goto l18
							}
						l17:
							v3 = v10 + i32(4)
						l15:
							v8 = v8 + v14
							v5 = v5 + i32(1)
							goto l19
						}
					}
				l8:
					t46 := int32(load32((*m.memory)[int64(uint32(v0))+48:]))
					t47 := int32(load32((*m.memory)[int64(uint32(v0))+24:]))
					m._sqlite3_result_text(v1, t46+t47<<6+i32(28), i32(-1), i32(0))
					p1 = i32(0)
					goto l12
				}
			l9:
				t48 := int32(load32((*m.memory)[int64(uint32(v0))+32:]))
				m._sqlite3_result_int(v1, t48)
				goto l1
			}
		l10:
			t49 := int32(load32((*m.memory)[int64(uint32(v0))+36:]))
			m._sqlite3_result_int(v1, t49)
			goto l1
		}
	l11:
		t50 := int32(load32((*m.memory)[int64(uint32(v0))+40:]))
		m._sqlite3_result_int(v1, t50)
		goto l1
	}
l0:
	m._sqlite3_result_null(v1)
	goto l1
l14:
	v0 = i32(0)
l20:
	{
		if v0 >= v6 {
			goto l13
		}
		_ = m._utf8Read(v0+v9, v6-v0, v4+i32(12))
		v5 = v5 + i32(1)
		t52 := int32(load32((*m.memory)[int64(uint32(v4))+12:]))
		v0 = t52 + v0
		goto l20
	}
l13:
	m._sqlite3_result_int(v1, v5)
l1:
	p1 = i32(0)
l12:
	*m.___stack_pointer = v4 + i32(16)
	return p1
}
func (m *Module) _spellfix1Rowid(v0, v1 int32) int32 {
	t1 := v1
	var p0 int64
	{
		t2 := int32(load32((*m.memory)[int64(uint32(v0))+44:]))
		v1 = t2
		if v1 != 0 {
			t3 := m._sqlite3_column_int64(v1, i32(4))
			p0 = t3
			goto l0
		}
		t4 := int32(load32((*m.memory)[int64(uint32(v0))+48:]))
		t5 := int32(load32((*m.memory)[int64(uint32(v0))+24:]))
		t6 := int64(load64((*m.memory)[uint32(t4+t5<<6):]))
		p0 = t6
	}
l0:
	store64((*m.memory)[uint32(t1):], uint64(p0))
	return i32(0)
}
func (m *Module) _spellfix1Update(v0, v1, v2, v3 int32) int32 {
	var v4, v5, v6, v7, v8, v9, v10, v11, v12, v13 int32
	var v14, v15, v16 int64
	t0 := *m.___stack_pointer
	v4 = t0 - i32(192)
	*m.___stack_pointer = v4
	store32((*m.memory)[int64(uint32(v4))+188:], uint32(i32(0)))
	t1 := int32(load32((*m.memory)[int64(uint32(v0))+12:]))
	v8 = t1
	{
		{
			if v1 == i32(1) {
				t2 := int32(load32((*m.memory)[uint32(v2):]))
				t3 := m._sqlite3_value_int64(t2)
				t4 := v3
				v14 = t3
				store64((*m.memory)[uint32(t4):], uint64(v14))
				t5 := int64(load64((*m.memory)[int64(uint32(v0))+16:]))
				v15 = t5
				store64((*m.memory)[int64(uint32(v4))+8:], uint64(v14))
				store64((*m.memory)[uint32(v4):], uint64(v15))
				m._spellfix1DbExec(v4+i32(188), v8, m.___memory_base+i32(366), v4)
				goto l0
			}
			t6 := int32(load32((*m.memory)[int64(uint32(v2))+8:]))
			t7 := m._sqlite3_value_text(t6)
			v7 = t7
			t8 := int32(load32((*m.memory)[int64(uint32(v2))+8:]))
			t9 := m._sqlite3_value_bytes(t8)
			v6 = t9
			t10 := int32(load32((*m.memory)[int64(uint32(v2))+20:]))
			t11 := m._sqlite3_value_int(t10)
			v11 = t11
			t12 := int32(load32((*m.memory)[int64(uint32(v2))+12:]))
			t13 := m._sqlite3_value_int(t12)
			v1 = t13
			t14 := int32(load32((*m.memory)[int64(uint32(v2))+48:]))
			t15 := m._sqlite3_value_text(t14)
			v5 = t15
			t16 := int32(load32((*m.memory)[int64(uint32(v2))+48:]))
			t17 := m._sqlite3_value_bytes(t16)
			v9 = t17
			t18 := m._sqlite3_vtab_on_conflict(v8)
			v10 = t18
			if v7 == 0 {
				t19 := int32(load32((*m.memory)[int64(uint32(v2))+52:]))
				t20 := m._sqlite3_value_text(t19)
				v1 = t20
				if v1 == 0 {
					t21 := int32(load32((*m.memory)[int64(uint32(v0))+20:]))
					store32((*m.memory)[int64(uint32(v4))+16:], uint32(t21))
					t22 := m._sqlite3_mprintf(m.___memory_base+i32(221), v4+i32(16))
					store32((*m.memory)[int64(uint32(v0))+8:], uint32(t22))
					v6 = i32(1299)
					goto l1
				}
				t23 := m._strcmp(v1, m.___memory_base+i32(38))
				if t23 == 0 {
					t24 := int32(load32((*m.memory)[int64(uint32(v0))+28:]))
					m._editDist3ConfigDelete(t24)
					v6 = i32(0)
					store32((*m.memory)[int64(uint32(v0))+28:], uint32(i32(0)))
					goto l1
				}
				t25 := m._strncmp(v1, m.___memory_base+i32(468), i32(16))
				if t25 == 0 {
					t26 := int32(load32((*m.memory)[int64(uint32(v0))+28:]))
					m._editDist3ConfigDelete(t26)
					store32((*m.memory)[int64(uint32(v0))+28:], uint32(i32(0)))
					t27 := int32(load32((*m.memory)[int64(uint32(v0))+24:]))
					m._sqlite3_free(t27)
					t28 := m._spellfix1Dequote(v1 + i32(16))
					t29 := v0
					v1 = t28
					store32((*m.memory)[int64(uint32(t29))+24:], uint32(v1))
					if v1 == 0 {
						v6 = i32(7)
						goto l1
					}
					t30 := int32((*m.memory)[uint32(v1)])
					if t30 != 0 {
						t31 := m._sqlite3_stricmp(v1, m.___memory_base+i32(103))
						if t31 != 0 {
							v6 = i32(0)
							goto l1
						}
						t32 := int32(load32((*m.memory)[int64(uint32(v0))+24:]))
						v1 = t32
					}
					m._sqlite3_free(v1)
					v6 = i32(0)
					store32((*m.memory)[int64(uint32(v0))+24:], uint32(i32(0)))
					goto l1
				}
				t33 := int32(load32((*m.memory)[int64(uint32(v0))+20:]))
				v2 = t33
				store32((*m.memory)[int64(uint32(v4))+36:], uint32(v1))
				store32((*m.memory)[int64(uint32(v4))+32:], uint32(v2))
				t34 := m._sqlite3_mprintf(m.___memory_base+i32(1085), v4+i32(32))
				store32((*m.memory)[int64(uint32(v0))+8:], uint32(t34))
				v6 = i32(1)
				goto l1
			}
			t35 := int32(load32((*m.memory)[uint32(m.___memory_base+v10<<2+i32(4172)):]))
			v10 = t35
			var p36 int32
			{
				if v5 != 0 {
					t37 := m._transliterate(v5, v9)
					p36 = t37
					goto l2
				}
				t38 := m._transliterate(v7, v6)
				p36 = t38
			}
		l2:
			v5 = p36
			v6 = i32(7)
			if v5 == 0 {
				goto l1
			}
			p39 := v1
			if v1 <= i32(1) {
				p39 = i32(1)
			}
			v9 = p39
			v1 = i32(0)
		l3:
			{
				v13 = v1 + v5
				t40 := int32((*m.memory)[uint32(v13)])
				v12 = t40
				if v12 != 0 {
					if uint32((v12-i32(65))&i32(255)) <= uint32(i32(25)) {
						(*m.memory)[uint32(v13)] = byte(v12 | i32(32))
					}
					v1 = v1 + i32(1)
					goto l3
				}
			}
			t41 := m._phoneticHash(v5, v1)
			v1 = t41
			if v1 == 0 {
				m._sqlite3_free(v5)
				goto l1
			}
			{
				t42 := int32(load32((*m.memory)[uint32(v2):]))
				t43 := m._sqlite3_value_type(t42)
				if t43 == i32(5) {
					{
						t44 := int32(load32((*m.memory)[int64(uint32(v2))+4:]))
						t45 := m._sqlite3_value_type(t44)
						if t45 == i32(5) {
							t46 := int64(load64((*m.memory)[int64(uint32(v0))+16:]))
							v14 = t46
							store32((*m.memory)[int64(uint32(v4))+76:], uint32(v1))
							store32((*m.memory)[int64(uint32(v4))+72:], uint32(v7))
							store32((*m.memory)[int64(uint32(v4))+68:], uint32(v5))
							store32((*m.memory)[uint32(v4-i32(-64)):], uint32(v7))
							store32((*m.memory)[int64(uint32(v4))+60:], uint32(v11))
							store32((*m.memory)[int64(uint32(v4))+56:], uint32(v9))
							store64((*m.memory)[int64(uint32(v4))+48:], uint64(v14))
							m._spellfix1DbExec(v4+i32(188), v8, m.___memory_base+i32(790), v4+i32(48))
							goto l4
						}
						t47 := int32(load32((*m.memory)[int64(uint32(v2))+4:]))
						t48 := m._sqlite3_value_int64(t47)
						v14 = t48
						t49 := int64(load64((*m.memory)[int64(uint32(v0))+16:]))
						v15 = t49
						store32((*m.memory)[int64(uint32(v4))+124:], uint32(v1))
						store32((*m.memory)[int64(uint32(v4))+120:], uint32(v7))
						store32((*m.memory)[int64(uint32(v4))+116:], uint32(v5))
						store32((*m.memory)[int64(uint32(v4))+112:], uint32(v7))
						store32((*m.memory)[int64(uint32(v4))+108:], uint32(v11))
						store32((*m.memory)[int64(uint32(v4))+104:], uint32(v9))
						store64((*m.memory)[int64(uint32(v4))+96:], uint64(v14))
						store64((*m.memory)[int64(uint32(v4))+84:], uint64(v15))
						store32((*m.memory)[int64(uint32(v4))+80:], uint32(v10))
						m._spellfix1DbExec(v4+i32(188), v8, m.___memory_base+i32(690), v4+i32(80))
					}
				l4:
					t50 := m._sqlite3_last_insert_rowid(v8)
					store64((*m.memory)[uint32(v3):], uint64(t50))
					goto l5
				}
				t51 := int32(load32((*m.memory)[uint32(v2):]))
				t52 := m._sqlite3_value_int64(t51)
				v14 = t52
				t53 := int32(load32((*m.memory)[int64(uint32(v2))+4:]))
				t54 := m._sqlite3_value_int64(t53)
				t55 := v3
				v15 = t54
				store64((*m.memory)[uint32(t55):], uint64(v15))
				t56 := int64(load64((*m.memory)[int64(uint32(v0))+16:]))
				v16 = t56
				store64((*m.memory)[int64(uint32(v4))+176:], uint64(v14))
				store32((*m.memory)[int64(uint32(v4))+172:], uint32(v1))
				store32((*m.memory)[int64(uint32(v4))+168:], uint32(v7))
				store32((*m.memory)[int64(uint32(v4))+164:], uint32(v5))
				store32((*m.memory)[int64(uint32(v4))+160:], uint32(v7))
				store32((*m.memory)[int64(uint32(v4))+156:], uint32(v11))
				store32((*m.memory)[int64(uint32(v4))+152:], uint32(v9))
				store64((*m.memory)[int64(uint32(v4))+144:], uint64(v15))
				store64((*m.memory)[int64(uint32(v4))+132:], uint64(v16))
				store32((*m.memory)[int64(uint32(v4))+128:], uint32(v10))
				m._spellfix1DbExec(v4+i32(188), v8, m.___memory_base+i32(257), v4+i32(128))
			}
		l5:
			m._sqlite3_free(v5)
			m._sqlite3_free(v1)
		}
	l0:
		t57 := int32(load32((*m.memory)[int64(uint32(v4))+188:]))
		v6 = t57
	}
l1:
	*m.___stack_pointer = v4 + i32(192)
	return v6
}
func (m *Module) _spellfix1DbExec(v0, v1, v2, v3 int32) {
	var v4 int32
	t0 := *m.___stack_pointer
	v4 = t0 - i32(16)
	*m.___stack_pointer = v4
	{
		t1 := int32(load32((*m.memory)[uint32(v0):]))
		if t1 != 0 {
			goto l0
		}
		store32((*m.memory)[int64(uint32(v4))+12:], uint32(v3))
		t2 := m._sqlite3_vmprintf(v2, v3)
		v2 = t2
		if v2 == 0 {
			store32((*m.memory)[uint32(v0):], uint32(i32(7)))
			goto l0
		}
		t3 := m._sqlite3_exec(v1, v2, i32(0), i32(0), i32(0))
		store32((*m.memory)[uint32(v0):], uint32(t3))
		m._sqlite3_free(v2)
	}
l0:
	*m.___stack_pointer = v4 + i32(16)
}
func (m *Module) _spellfix1Dequote(v0 int32) int32 {
	var v1, v2, v3, v4, v5 int32
	t0 := *m.___stack_pointer
	v3 = t0 - i32(16)
	*m.___stack_pointer = v3
l1:
	{
		t1 := int32((*m.memory)[uint32(v0)])
		v2 = t1 - i32(9)
		if uint32(v2) > uint32(i32(23)) {
			goto l0
		}
		if i32_shl(i32(1), v2)&i32(8388639) == 0 {
			goto l0
		}
		v0 = v0 + i32(1)
		goto l1
	}
l0:
	store32((*m.memory)[uint32(v3):], uint32(v0))
	{
		t2 := m._sqlite3_mprintf(m.___memory_base+i32(100), v3)
		v1 = t2
		if v1 == 0 {
			goto l2
		}
		t3 := m._strlen(v1)
		(*m.memory)[uint32(t3+v1)] = byte(i32(0))
		t4 := int32((*m.memory)[uint32(v1)])
		v4 = t4
		var p5 int32
		if v4 != i32(39) {
			p5 = 1
		}
		var p6 int32
		if v4 != i32(34) {
			p6 = 1
		}
		if p5&p6 != 0 {
			goto l2
		}
		v2 = v1
		v0 = i32(1)
	l4:
		{
			t7 := int32((*m.memory)[uint32(v0+v1)])
			t8 := v2
			v5 = t7
			(*m.memory)[uint32(t8)] = byte(v5)
			{
				if v4 != v5 {
					goto l3
				}
				t9 := v1
				v0 = v0 + i32(1)
				t10 := int32((*m.memory)[uint32(t9+v0)])
				if t10 == v4 {
					goto l3
				}
				(*m.memory)[uint32(v2)] = byte(i32(0))
				goto l2
			}
		l3:
			v2 = v2 + i32(1)
			v0 = v0 + i32(1)
			goto l4
		}
	}
l2:
	*m.___stack_pointer = v3 + i32(16)
	return v1
}
func (m *Module) _spellfix1Rename(v0, v1 int32) int32 {
	var v2, v3 int32
	var v4 int64
	t0 := *m.___stack_pointer
	v2 = t0 - i32(32)
	*m.___stack_pointer = v2
	t1 := int32(load32((*m.memory)[int64(uint32(v0))+12:]))
	v3 = t1
	store32((*m.memory)[int64(uint32(v2))+16:], uint32(v1))
	store32((*m.memory)[int64(uint32(v2))+28:], uint32(i32(0)))
	{
		t2 := m._sqlite3_mprintf(m.___memory_base+i32(100), v2+i32(16))
		v1 = t2
		if v1 == 0 {
			v3 = i32(7)
			goto l0
		}
		t3 := int64(load64((*m.memory)[int64(uint32(v0))+16:]))
		v4 = t3
		store32((*m.memory)[int64(uint32(v2))+8:], uint32(v1))
		store64((*m.memory)[uint32(v2):], uint64(v4))
		m._spellfix1DbExec(v2+i32(28), v3, m.___memory_base+i32(1191), v2)
		t4 := int32(load32((*m.memory)[int64(uint32(v2))+28:]))
		v3 = t4
		if v3 == 0 {
			t5 := int32(load32((*m.memory)[int64(uint32(v0))+20:]))
			m._sqlite3_free(t5)
			store32((*m.memory)[int64(uint32(v0))+20:], uint32(v1))
			v3 = i32(0)
			goto l0
		}
		m._sqlite3_free(v1)
	}
l0:
	*m.___stack_pointer = v2 + i32(32)
	return v3
}
func (m *Module) _editDist3ConfigClear(v0 int32) {
	var v1, v2, v3 int32
	if v0 != 0 {
	l1:
		{
			t0 := int32(load32((*m.memory)[int64(uint32(v0))+4:]))
			v1 = t0
			t1 := int32(load32((*m.memory)[uint32(v0):]))
			if t1 > v3 {
				t2 := int32(load32((*m.memory)[int64(uint32(v1+v3*i32(20)))+16:]))
				v2 = t2
			l0:
				if v2 != 0 {
					t3 := int32(load32((*m.memory)[uint32(v2):]))
					m._sqlite3_free(v2)
					v2 = t3
					goto l0
				}
				v3 = v3 + i32(1)
				goto l1
			}
		}
		m._sqlite3_free(v1)
		store64((*m.memory)[uint32(v0):], uint64(i64(0)))
	}
}
func (m *Module) _editDist3CostMerge(v0, v1 int32) int32 {
	var v2, v3, v4, v5 int32
	t0 := *m.___stack_pointer
	v3 = t0 - i32(16)
	*m.___stack_pointer = v3
	store32((*m.memory)[int64(uint32(v3))+12:], uint32(i32(0)))
	v4 = v3 + i32(12)
l2:
	{
		if v0 == 0 {
			goto l0
		}
		if v1 == 0 {
			goto l0
		}
		t1 := int32((*m.memory)[int64(uint32(v0))+4])
		t2 := v0 + i32(8)
		t3 := v1 + i32(8)
		v2 = t1
		t4 := int32((*m.memory)[int64(uint32(v1))+4])
		t5 := v2
		v5 = t4
		p6 := v5
		if uint32(v2) < uint32(v5) {
			p6 = t5
		}
		t7 := m._strncmp(t2, t3, p6)
		v2 = t7
		if v2 == 0 {
			t8 := int32((*m.memory)[int64(uint32(v0))+4])
			t9 := int32((*m.memory)[int64(uint32(v1))+4])
			v2 = t8 - t9
		}
		{
			if v2 <= i32(0) {
				v2 = v0
				t10 := int32(load32((*m.memory)[uint32(v2):]))
				v0 = t10
				goto l1
			}
			v2 = v1
			t11 := int32(load32((*m.memory)[uint32(v2):]))
			v1 = t11
		}
	l1:
		store32((*m.memory)[uint32(v4):], uint32(v2))
		v4 = v2
		goto l2
	}
l0:
	t13 := v4
	p12 := v1
	if v0 != 0 {
		p12 = v0
	}
	store32((*m.memory)[uint32(t13):], uint32(p12))
	t14 := int32(load32((*m.memory)[int64(uint32(v3))+12:]))
	*m.___stack_pointer = v3 + i32(16)
	return t14
}
func _utf8Len(v0, v1 int32) int32 {
	var p0 int32
	{
		if int32(int8(v0)) >= i32(0) {
			p0 = i32(1)
			goto l0
		}
		if v0&i32(224) == i32(192) {
			p0 = i32(2)
			goto l0
		}
		p1 := i32(4)
		if v0&i32(240) == i32(224) {
			p1 = i32(3)
		}
		p0 = p1
	}
l0:
	v0 = p0
	p2 := v1
	if v0 < v1 {
		p2 = v0
	}
	return p2
}
func (m *Module) _matchTo(v0, v1, v2 int32) int32 {
	var v3, v4 int32
	{
		t0 := int32((*m.memory)[int64(uint32(v0))+4])
		v3 = v0 + t0
		t1 := int32((*m.memory)[int64(uint32(v3))+8])
		t2 := int32((*m.memory)[uint32(v1)])
		if t1 != t2 {
			goto l0
		}
		t3 := int32((*m.memory)[int64(uint32(v0))+5])
		v0 = t3
		if v0 > v2 {
			goto l0
		}
		t4 := m._strncmp(v3+i32(8), v1, v0)
		var p5 int32
		if t4 == 0 {
			p5 = 1
		}
		v4 = p5
	}
l0:
	return v4
}
func DylinkInfo() (memorySize, memoryAlignment, tableSize, tableAlignment int64) {
	return 4196, 16, 22, 1
}

// Compiler error if endianess is unknown.
var _ = map[bool]struct{}{big: {}, little: {}}

// go.dev/src/cmd/compile/internal/ssa/config.go
const (
	big = false ||
		runtime.GOARCH == "ppc64" || runtime.GOARCH == "s390x" ||
		runtime.GOARCH == "mips" || runtime.GOARCH == "mips64"

	little = false ||
		runtime.GOARCH == "386" || runtime.GOARCH == "amd64" ||
		runtime.GOARCH == "arm" || runtime.GOARCH == "arm64" ||
		runtime.GOARCH == "riscv64" || runtime.GOARCH == "wasm" ||
		runtime.GOARCH == "ppc64le" || runtime.GOARCH == "loong64" ||
		runtime.GOARCH == "mipsle" || runtime.GOARCH == "mips64le"

	unalignedOK = false ||
		runtime.GOARCH == "386" || runtime.GOARCH == "amd64" ||
		runtime.GOARCH == "arm64" || runtime.GOARCH == "loong64" ||
		runtime.GOARCH == "ppc64" || runtime.GOARCH == "ppc64le" ||
		runtime.GOARCH == "s390x" || runtime.GOARCH == "wasm"
)

//go:nosplit
func load16(b []byte) uint16 {
	if !unalignedOK {
		return binary.LittleEndian.Uint16(b)
	}
	v := *(*uint16)(unsafe.Pointer((*[2]byte)(b)))
	if big {
		return bits.ReverseBytes16(v)
	}
	return v
}

//go:nosplit
func store16(b []byte, v uint16) {
	if !unalignedOK {
		binary.LittleEndian.PutUint16(b, v)
		return
	}
	if big {
		v = bits.ReverseBytes16(v)
	}
	*(*uint16)(unsafe.Pointer((*[2]byte)(b))) = v
}

//go:nosplit
func load32(b []byte) uint32 {
	if !unalignedOK {
		return binary.LittleEndian.Uint32(b)
	}
	v := *(*uint32)(unsafe.Pointer((*[4]byte)(b)))
	if big {
		return bits.ReverseBytes32(v)
	}
	return v
}

//go:nosplit
func store32(b []byte, v uint32) {
	if !unalignedOK {
		binary.LittleEndian.PutUint32(b, v)
		return
	}
	if big {
		v = bits.ReverseBytes32(v)
	}
	*(*uint32)(unsafe.Pointer((*[4]byte)(b))) = v
}

//go:nosplit
func load64(b []byte) uint64 {
	if !unalignedOK {
		return binary.LittleEndian.Uint64(b)
	}
	v := *(*uint64)(unsafe.Pointer((*[8]byte)(b)))
	if big {
		return bits.ReverseBytes64(v)
	}
	return v
}

//go:nosplit
func store64(b []byte, v uint64) {
	if !unalignedOK {
		binary.LittleEndian.PutUint64(b, v)
		return
	}
	if big {
		v = bits.ReverseBytes64(v)
	}
	*(*uint64)(unsafe.Pointer((*[8]byte)(b))) = v
}

//go:nosplit
func i32(x int32) int32 { return x }

//go:nosplit
func i64(x int64) int64 { return x }

//go:nosplit
func i32_shl(x, y int32) int32 {
	return x << (y & 31)
}

func memory_copy[T uint32 | uint64](mem []byte, dest, src, n T) {
	x := uint(min(uint64(dest), math.MaxUint))
	z := uint(min(uint64(src), math.MaxUint))
	c := uint(min(uint64(n), math.MaxUint))
	y := x + c
	w := z + c
	copy(mem[x:y], mem[z:w])
}

func memory_fill[T uint32 | uint64](mem []byte, dest T, val int32, n T) {
	x := uint(min(uint64(dest), math.MaxUint))
	y := x + uint(min(uint64(n), math.MaxUint))
	buf := mem[x:y]
	if len(buf) > 0 {
		buf[0] = byte(val)
		for i := 1; i < len(buf); {
			chunk := min(i, 8192)
			i += copy(buf[i:], buf[:chunk])
		}
	}
}

func memory_zero[T uint32 | uint64](mem []byte, dest, n T) {
	x := uint(min(uint64(dest), math.MaxUint))
	y := x + uint(min(uint64(n), math.MaxUint))
	clear(mem[x:y])
}
//go:embed spellfix.dat
var data string
