// Code generated by wasm2go. DO NOT EDIT.

package sql3parse_table

import (
	"encoding/binary"
	"math"
	"math/bits"
)

type Module struct {
	memory           []byte
	maxMem           int64
	___stack_pointer int32
}

func New() *Module {
	m := &Module{}
	m.maxMem = 65536
	m.memory = make([]byte, 131072)
	copy(m.memory[uint32(i32(65536)):], data0)
	copy(m.memory[uint32(i32(65950)):], data1)
	m.___stack_pointer = i32(65536)
	return m
}

type Memory = interface {
	Slice() *[]byte
	Grow(delta, max int64) int64
}
type wasmMemory []byte

func (m *wasmMemory) Slice() *[]byte {
	return (*[]byte)(m)
}
func (m *wasmMemory) Grow(delta, max int64) int64 {
	return memory_grow((*[]byte)(m), delta, max)
}
func (m *Module) Xmalloc(v0 int32) int32 {
	var v1, v2, v3 int32
	{
		if v0 == 0 {
			goto l0
		}
		v0 = (v0 + i32(15)) & i32(-16)
		t0 := v0
		v3 = int32(binary.LittleEndian.Uint32(m.memory[uint32(i32(65948)):]))
		t1 := v3
		v2 = int32(binary.LittleEndian.Uint32(m.memory[uint32(i32(65952)):]))
		v1 = t1 - v2
		if uint32(t0) > uint32(v1) {
			v1 = v0 - v1 + i32(0xffff)
			if int32(memory_grow(&m.memory, int64(int32(uint32(v1)>>16)), m.maxMem)) == i32(-1) {
				goto l0
			}
			binary.LittleEndian.PutUint32(m.memory[uint32(i32(65948)):], uint32(v3+v1&i32(-65536)))
		}
		binary.LittleEndian.PutUint32(m.memory[uint32(i32(65952)):], uint32(v0+v2))
		return v2
	}
l0:
	return i32(0)
}
func (m *Module) Xsql3parse_table(v0, v1, v2 int32) int32 {
	var v3, v4, v5, v6, v7, v8, v9, v10, v11 int32
	var v12 int64
	v3 = m.___stack_pointer + i32(-64)
	m.___stack_pointer = v3
	{
		if v0 == 0 {
			v0 = i32(0)
			if v2 == 0 {
				goto l0
			}
			binary.LittleEndian.PutUint32(m.memory[uint32(v2):], uint32(i32(2)))
			goto l0
		}
		if v1 != 0 {
			goto l1
		}
		v1 = i32(0)
	l2:
		{
			t0 := v0 + v1
			v1 = v1 + i32(1)
			if int32(m.memory[uint32(t0)]) != 0 {
				goto l2
			}
		}
		v1 = v1 - i32(1)
		if v1 != 0 {
			goto l1
		}
		v0 = i32(0)
		if v2 == 0 {
			goto l0
		}
		binary.LittleEndian.PutUint32(m.memory[uint32(v2):], uint32(i32(2)))
		goto l0
	l1:
		if v2 != 0 {
			binary.LittleEndian.PutUint32(m.memory[uint32(v2):], uint32(i32(0)))
		}
		{
			var p1 int32
			v8 = m.Xmalloc(i32(64))
			if v8 != 0 {
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(v3))+28:], uint32(i32(0)))
				binary.LittleEndian.PutUint64(m.memory[int64(uint32(v3))+20:], uint64(i64(0)))
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(v3))+16:], uint32(v1))
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(v3))+12:], uint32(v0))
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(v3))+36:], uint32(v8))
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(v3))+32:], uint32(v8+i32(16)))
				v0 = i32(3)
				v5 = v3 + i32(12)
				v1 = m._sql3lexer_next(v5)
				if v1 != i32(57) {
					if v1 != i32(6) {
						goto l3
					}
					v4 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v3))+36:]))
					binary.LittleEndian.PutUint32(m.memory[int64(uint32(v4))+44:], uint32(i32(1)))
					v1 = m._sql3lexer_next(v5)
					if v1 == i32(7) {
						m.memory[int64(uint32(v4))+24] = byte(i32(1))
						v1 = m._sql3lexer_next(v5)
					}
					if v1 != i32(8) {
						goto l3
					}
					v1 = v3 + i32(12)
					if m._sql3lexer_peek(v1) == i32(9) {
						_ = m._sql3lexer_next(v1)
						v0 = i32(2)
						if m._sql3lexer_next(v1) != i32(10) {
							goto l3
						}
						if m._sql3lexer_next(v1) != i32(11) {
							goto l3
						}
						m.memory[int64(uint32(v4))+25] = byte(i32(1))
					}
					v1 = v3 + i32(12)
					v0 = m._sql3parse_schema_identifier(v1)
					if v0 != 0 {
						goto l3
					}
					v0 = i32(3)
					switch m._sql3lexer_next(v1) - i32(15) {
					case 0:
						goto l3
					case 4:
						goto l8
					default:
						goto l4
					}
				l8:
					{
						v0 = i32(2)
						v1 = v3 + i32(12)
						if m._sql3lexer_peek(v1) != i32(2) {
							goto l3
						}
						v5 = m._sql3parse_column(v1)
						if v5 == 0 {
							goto l3
						}
						t2 := v4
						v0 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v4))+28:])) + i32(1)
						binary.LittleEndian.PutUint32(m.memory[int64(uint32(t2))+28:], uint32(v0))
						v1 = m._sql3_array_grow(int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v4))+32:])), v0, i32(4))
						if v1 == 0 {
							t3 := v4
							binary.LittleEndian.PutUint32(m.memory[int64(uint32(t3))+28:], uint32(int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v4))+28:]))-i32(1)))
							v0 = i32(1)
							goto l3
						}
						binary.LittleEndian.PutUint32(m.memory[int64(uint32(v4))+32:], uint32(v1))
						v0 = i32(2)
						t4 := v1
						binary.LittleEndian.PutUint32(m.memory[uint32(t4+int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v4))+28:]))<<2-i32(4)):], uint32(v5))
						switch m._sql3lexer_peek(v3+i32(12)) - i32(18) {
						case 0:
							goto l6
						case 2:
							goto l7
						default:
							goto l3
						}
					l6:
						v0 = v3 + i32(12)
						_ = m._sql3lexer_next(v0)
						v0 = m._sql3lexer_peek(v0) - i32(21)
						if uint32(v0) > uint32(i32(5)) {
							goto l8
						}
						if i32_shr_u(i32(59), v0)&i32(1) == 0 {
							goto l8
						}
					}
					t5 := int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0<<2))+65904:]))
					p1 = t5
					goto l9
				}
				v1 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v3))+36:]))
				v4 = v3 + i32(12)
				if m._sql3lexer_next(v4) != i32(8) {
					goto l3
				}
				v0 = m._sql3parse_schema_identifier(v4)
				if v0 != 0 {
					goto l3
				}
				v5 = m._sql3lexer_next(v4)
				v4 = m._sql3lexer_peek(v4)
				v0 = i32(3)
				{
					{
						{
							switch v5 - i32(58) {
							case 0:
								goto l10
							case 1:
								goto l11
							case 2:
								goto l12
							default:
								goto l3
							}
						l10:
							{
								switch v4 - i32(61) {
								case 0:
									goto l13
								case 1:
									goto l14
								default:
									goto l15
								}
							l14:
								v4 = v3 + i32(12)
								_ = m._sql3lexer_next(v4)
								v0 = i32(2)
								binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+44:], uint32(i32(2)))
								if m._sql3lexer_next(v4) != i32(2) {
									goto l3
								}
								t6 := v1
								binary.LittleEndian.PutUint64(m.memory[int64(uint32(t6))+56:], uint64(int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v3))+24:]))))
								goto l16
							}
						l13:
							_ = m._sql3lexer_next(v3 + i32(12))
						l15:
							binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+44:], uint32(i32(3)))
							v0 = i32(2)
							v4 = v3 + i32(12)
							if m._sql3lexer_next(v4) != i32(2) {
								goto l3
							}
							t7 := v1
							binary.LittleEndian.PutUint64(m.memory[int64(uint32(t7))+48:], uint64(int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v3))+24:]))))
							if m._sql3lexer_next(v4) != i32(62) {
								goto l3
							}
							if m._sql3lexer_next(v4) != i32(2) {
								goto l3
							}
							t8 := v1
							binary.LittleEndian.PutUint64(m.memory[int64(uint32(t8))+56:], uint64(int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v3))+24:]))))
							goto l16
						}
					l11:
						if v4 == i32(61) {
							_ = m._sql3lexer_next(v3 + i32(12))
						}
						binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+44:], uint32(i32(4)))
						v0 = i32(2)
						v4 = v3 + i32(12)
						if m._sql3lexer_peek(v4) != i32(2) {
							goto l3
						}
						v5 = m._sql3parse_column(v4)
						if v5 == 0 {
							goto l3
						}
						v0 = i32(1)
						t9 := v1
						v4 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v1))+28:])) + i32(1)
						binary.LittleEndian.PutUint32(m.memory[int64(uint32(t9))+28:], uint32(v4))
						v4 = m._sql3_array_grow(int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v1))+32:])), v4, i32(4))
						if v4 == 0 {
							t10 := v1
							binary.LittleEndian.PutUint32(m.memory[int64(uint32(t10))+28:], uint32(int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v1))+28:]))-i32(1)))
							goto l3
						}
						binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+32:], uint32(v4))
						t11 := v4
						binary.LittleEndian.PutUint32(m.memory[uint32(t11+int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v1))+28:]))<<2-i32(4)):], uint32(v5))
						goto l16
					}
				l12:
					if v4 == i32(61) {
						_ = m._sql3lexer_next(v3 + i32(12))
					}
					binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+44:], uint32(i32(5)))
					v0 = i32(2)
					if m._sql3lexer_next(v3+i32(12)) != i32(2) {
						goto l3
					}
					t12 := v1
					binary.LittleEndian.PutUint64(m.memory[int64(uint32(t12))+48:], uint64(int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v3))+24:]))))
				}
			l16:
				v0 = i32(0)
				v1 = v3 + i32(12)
				if m._sql3lexer_peek(v1) != i32(17) {
					goto l3
				}
				_ = m._sql3lexer_next(v1)
				goto l3
			}
			v0 = i32(0)
			if v2 == 0 {
				goto l0
			}
			binary.LittleEndian.PutUint32(m.memory[uint32(v2):], uint32(i32(1)))
			goto l0
		l7:
			p1 = m._sql3lexer_peek(v3 + i32(12))
		l9:
			v0 = p1
			v9 = v4 + i32(16)
			v10 = v3 + i32(56)
		l25:
			{
				if uint32(v0) > uint32(i32(26)) {
					goto l17
				}
				if i32_shl(i32(1), v0)&i32(0x7600000) == 0 {
					goto l17
				}
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(v3))+32:], uint32(v9))
				v5 = v3 + i32(12)
				v0 = m._sql3lexer_peek(v5)
				v1 = m.Xmalloc(i32(48))
				if v1 == 0 {
					goto l4
				}
				if v0 == i32(21) {
					_ = m._sql3lexer_next(v5)
					v0 = i32(2)
					if m._sql3lexer_next(v5) != i32(2) {
						goto l3
					}
					t13 := v1
					binary.LittleEndian.PutUint64(m.memory[int64(uint32(t13))+4:], uint64(int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v3))+24:]))))
					v5 = m._sql3lexer_peek(v5) - i32(22)
					if uint32(v5) > uint32(i32(4)) {
						goto l3
					}
					if i32_shr_u(i32(29), v5)&i32(1) == 0 {
						goto l3
					}
					v0 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v5<<2))+65928:]))
				}
				{
					{
						switch v0 - i32(22) {
						case 0, 2:
							goto l18
						case 3:
							goto l20
						case 4:
							goto l21
						default:
							goto l19
						}
					l20:
						v5 = v3 + i32(12)
						_ = m._sql3lexer_next(v5)
						v0 = i32(2)
						binary.LittleEndian.PutUint32(m.memory[uint32(v1):], uint32(i32(2)))
						m._sql3parse_expression(v3+i32(40), v5)
						t14 := v1
						v12 = int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v3))+40:]))
						binary.LittleEndian.PutUint64(m.memory[int64(uint32(t14))+28:], uint64(v12))
						if int32(v12) != 0 {
							goto l19
						}
						goto l3
					}
				l18:
					t15 := v1
					var p16 int32
					if m._sql3lexer_next(v3+i32(12)) != i32(22) {
						p16 = 1
					}
					v7 = p16
					var p17 int32
					if v7 != 0 {
						p17 = i32(1)
					} else {
						if m._sql3lexer_next(v3+i32(12)) != i32(23) {
							goto l4
						}
						p17 = i32(0)
					}
					binary.LittleEndian.PutUint32(m.memory[uint32(t15):], uint32(p17))
					if m._sql3lexer_next(v3+i32(12)) != i32(19) {
						goto l4
					}
				l22:
					{
						binary.LittleEndian.PutUint64(m.memory[int64(uint32(v3))+48:], uint64(i64(0)))
						v0 = v3 + i32(12)
						if m._sql3lexer_next(v0) != i32(2) {
							goto l4
						}
						t18 := v3
						binary.LittleEndian.PutUint64(m.memory[int64(uint32(t18))+40:], uint64(int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v3))+24:]))))
						if m._sql3lexer_peek(v0) == i32(34) {
							_ = m._sql3lexer_next(v0)
							if m._sql3lexer_next(v0) != i32(2) {
								goto l4
							}
							t19 := v3
							binary.LittleEndian.PutUint64(m.memory[int64(uint32(t19))+48:], uint64(int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v3))+24:]))))
						}
						v5 = v3 + i32(12)
						m._sql3parse_optionalorder(v5, v10)
						t20 := v1
						v11 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v1))+12:]))
						v0 = v11 + i32(1)
						binary.LittleEndian.PutUint32(m.memory[int64(uint32(t20))+12:], uint32(v0))
						v6 = m._sql3_array_grow(int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v1))+16:])), v0, i32(20))
						if v6 == 0 {
							goto l4
						}
						binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+16:], uint32(v6))
						v0 = v6 + v0*i32(20) - i32(20)
						t21 := v0
						binary.LittleEndian.PutUint32(m.memory[int64(uint32(t21))+16:], uint32(int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v3))+56:]))))
						t22 := v0
						binary.LittleEndian.PutUint64(m.memory[int64(uint32(t22))+8:], uint64(int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v3))+48:]))))
						t23 := v0
						binary.LittleEndian.PutUint64(m.memory[uint32(t23):], uint64(int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v3))+40:]))))
						v0 = m._sql3lexer_peek(v5)
						if v0 == i32(37) {
							_ = m._sql3lexer_next(v5)
							if v7 != 0 {
								goto l4
							}
							m.memory[int64(uint32(v1))+24] = byte(i32(1))
							v0 = m._sql3lexer_peek(v5)
						}
						if v0 == i32(18) {
							_ = m._sql3lexer_next(v3 + i32(12))
							goto l22
						}
					}
					if v11 != 0 {
						if int32(m.memory[int64(uint32(v1))+24])&i32(1) != 0 {
							goto l4
						}
					}
					v5 = v3 + i32(12)
					if m._sql3lexer_next(v5) != i32(20) {
						goto l4
					}
					v0 = i32(2)
					if m._sql3parse_optionalconflitclause(v5, v1+i32(20)) == 0 {
						goto l19
					}
					goto l3
				}
			l21:
				v5 = v3 + i32(12)
				_ = m._sql3lexer_next(v5)
				if m._sql3lexer_next(v5) != i32(23) {
					goto l4
				}
				v0 = i32(2)
				if m._sql3lexer_next(v5) != i32(19) {
					goto l3
				}
				binary.LittleEndian.PutUint32(m.memory[uint32(v1):], uint32(i32(3)))
			l23:
				{
					v5 = v3 + i32(12)
					if m._sql3lexer_next(v5) != i32(2) {
						goto l3
					}
					t24 := v1
					v6 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v1))+36:])) + i32(1)
					binary.LittleEndian.PutUint32(m.memory[int64(uint32(t24))+36:], uint32(v6))
					v7 = m._sql3_array_grow(int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v1))+40:])), v6, i32(8))
					if v7 == 0 {
						goto l3
					}
					binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+40:], uint32(v7))
					t25 := v7 + v6<<3 - i32(8)
					binary.LittleEndian.PutUint64(m.memory[uint32(t25):], uint64(int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v3))+24:]))))
					t26 := m._sql3lexer_peek(v5)
					v7 = m._sql3lexer_next(v5)
					if t26 == i32(18) {
						goto l23
					}
				}
				if v7 != i32(20) {
					goto l3
				}
				if m._sql3lexer_next(v5) != i32(42) {
					goto l3
				}
				v5 = m._sql3parse_foreignkey_clause(v5)
				if v5 == 0 {
					goto l3
				}
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+44:], uint32(v5))
			l19:
				t27 := v4
				v0 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v4))+36:])) + i32(1)
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(t27))+36:], uint32(v0))
				v5 = m._sql3_array_grow(int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v4))+40:])), v0, i32(4))
				if v5 == 0 {
					t28 := v4
					binary.LittleEndian.PutUint32(m.memory[int64(uint32(t28))+36:], uint32(int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v4))+36:]))-i32(1)))
					v0 = i32(1)
					goto l3
				}
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(v4))+40:], uint32(v5))
				v0 = i32(2)
				t29 := v5
				binary.LittleEndian.PutUint32(m.memory[uint32(t29+int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v4))+36:]))<<2-i32(4)):], uint32(v1))
				switch m._sql3lexer_peek(v3+i32(12)) - i32(18) {
				case 0:
					goto l24
				case 2:
					goto l17
				default:
					goto l3
				}
			l24:
				v0 = v3 + i32(12)
				_ = m._sql3lexer_next(v0)
				v0 = m._sql3lexer_peek(v0)
				goto l25
			}
		l17:
			v0 = i32(2)
			if m._sql3lexer_next(v3+i32(12)) != i32(20) {
				goto l3
			}
			binary.LittleEndian.PutUint32(m.memory[int64(uint32(v3))+32:], uint32(v9))
		l30:
			switch m._sql3lexer_peek(v3+i32(12)) - i32(12) {
			case 0:
				goto l26
			case 2:
				goto l28
			default:
				goto l27
			}
		l26:
			v1 = v3 + i32(12)
			_ = m._sql3lexer_next(v1)
			if m._sql3lexer_next(v1) != i32(13) {
				goto l3
			}
			m.memory[int64(uint32(int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v3))+36:]))))+26] = byte(i32(1))
			goto l29
		l28:
			_ = m._sql3lexer_next(v3 + i32(12))
			m.memory[int64(uint32(int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v3))+36:]))))+27] = byte(i32(1))
		l29:
			v1 = v3 + i32(12)
			if m._sql3lexer_peek(v1) != i32(18) {
				goto l27
			}
			_ = m._sql3lexer_next(v1)
			goto l30
		l27:
			v0 = i32(0)
			v1 = v3 + i32(12)
			if m._sql3lexer_peek(v1) != i32(17) {
				goto l3
			}
			_ = m._sql3lexer_next(v1)
			goto l3
		}
	l4:
		v0 = i32(2)
	l3:
		if v2 != 0 {
			binary.LittleEndian.PutUint32(m.memory[uint32(v2):], uint32(v0))
		}
		p30 := v8
		if v0 != 0 {
			p30 = i32(0)
		}
		v0 = p30
	}
l0:
	m.___stack_pointer = v3 - i32(-64)
	return v0
}
func (m *Module) _sql3lexer_next(v0 int32) int32 {
	var v1, v2, v3, v4, v5, v6, v7, v8, v9 int32
l4:
	{
		v4 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+8:]))
		t0 := v4
		v8 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+4:]))
		if uint32(t0) >= uint32(v8) {
			return i32(0)
		}
		v5 = int32(binary.LittleEndian.Uint32(m.memory[uint32(v0):]))
		v1 = v5 + v4
		v2 = int32(m.memory[uint32(v1)])
		switch v2 {
		case 0:
			goto l0
		case 1, 2, 3, 4, 5, 6, 7, 8:
			goto l1
		case 9, 10, 11, 12, 13:
			goto l2
		default:
			goto l3
		}
	l3:
		if v2 != i32(32) {
			goto l1
		}
	l2:
		binary.LittleEndian.PutUint32(m.memory[int64(uint32(v0))+8:], uint32(v4+i32(1)))
		goto l4
	l1:
		if m._symbol_is_comment(v2, v0) != 0 {
			m._sql3lexer_comment(v0)
			goto l4
		}
	}
	v3 = v2 - i32(40)
	if uint32(v3) > uint32(i32(19)) {
		goto l5
	}
	if i32_shl(i32(1), v3)&i32(524371) == 0 {
		goto l5
	}
	binary.LittleEndian.PutUint32(m.memory[int64(uint32(v0))+8:], uint32(v4+i32(1)))
	v2 = i32(18)
	v0 = int32(m.memory[uint32(v1)])
	switch v0 - i32(40) {
	case 0:
		goto l6
	case 1:
		goto l7
	case 2, 3, 5:
		goto l8
	case 4:
		goto l0
	case 6:
		goto l9
	default:
		goto l10
	}
l9:
	return i32(16)
l6:
	return i32(19)
l7:
	return i32(20)
l10:
	if v0 == i32(59) {
		goto l11
	}
	goto l8
l5:
	{
		if v2 != i32(95) {
			if uint32((v2|i32(32)-i32(97))&i32(255)) > uint32(i32(25)) {
				goto l12
			}
		}
		v3 = i32(0)
	l15:
		v2 = i32(0)
		v5 = v3 + v4
		if uint32(v5) < uint32(v8) {
			v2 = int32(m.memory[uint32(v1+v3)])
		}
		v6 = v2 - i32(48)
		v7 = v2 | i32(32)
		if v2&i32(255) == i32(95) {
			goto l13
		}
		if uint32(v6&i32(255)) < uint32(i32(10)) {
			goto l13
		}
		if uint32((v7-i32(97))&i32(255)) > uint32(i32(25)) {
			goto l14
		}
	l13:
		binary.LittleEndian.PutUint32(m.memory[int64(uint32(v0))+8:], uint32(v5+i32(1)))
		v3 = v3 + i32(1)
		goto l15
	l14:
		switch v3 - i32(2) {
		case 0:
			goto l16
		case 1:
			goto l17
		case 2:
			goto l18
		case 3:
			goto l19
		case 4:
			goto l20
		case 5:
			goto l21
		case 6:
			goto l22
		case 7:
			goto l23
		case 8:
			goto l24
		case 11:
			goto l26
		default:
			goto l25
		}
	l16:
		if m._str_nocasencmp(v1, i32(65752), i32(2)) == 0 {
			return i32(9)
		}
		if m._str_nocasencmp(v1, i32(65695), i32(2)) == 0 {
			return i32(27)
		}
		if m._str_nocasencmp(v1, i32(65688), i32(2)) == 0 {
			return i32(50)
		}
		if m._str_nocasencmp(v1, i32(65666), i32(2)) == 0 {
			return i32(15)
		}
		if m._str_nocasencmp(v1, i32(65685), i32(2)) != 0 {
			goto l25
		}
		return i32(62)
	l17:
		if m._str_nocasencmp(v1, i32(65582), i32(3)) == 0 {
			return i32(10)
		}
		if m._str_nocasencmp(v1, i32(65564), i32(3)) == 0 {
			return i32(23)
		}
		if m._str_nocasencmp(v1, i32(65889), i32(3)) == 0 {
			return i32(35)
		}
		if m._str_nocasencmp(v1, i32(65619), i32(3)) == 0 {
			return i32(45)
		}
		if m._str_nocasencmp(v1, i32(65880), i32(3)) != 0 {
			goto l25
		}
		return i32(59)
	l18:
		if m._str_nocasencmp(v1, i32(65680), i32(4)) == 0 {
			goto l27
		}
		if m._str_nocasencmp(v1, i32(65884), i32(4)) == 0 {
			return i32(36)
		}
		if m._str_nocasencmp(v1, i32(65713), i32(4)) == 0 {
			return i32(46)
		}
		if m._str_nocasencmp(v1, i32(65718), i32(4)) == 0 {
			return i32(31)
		}
		if m._str_nocasencmp(v1, i32(65675), i32(4)) != 0 {
			goto l25
		}
		return i32(60)
	l19:
		if m._str_nocasencmp(v1, i32(65815), i32(5)) == 0 {
			return i32(8)
		}
		if m._str_nocasencmp(v1, i32(65848), i32(5)) == 0 {
			return i32(13)
		}
		if m._str_nocasencmp(v1, i32(65731), i32(5)) == 0 {
			return i32(25)
		}
		if m._str_nocasencmp(v1, i32(65576), i32(5)) == 0 {
			return i32(30)
		}
		if m._str_nocasencmp(v1, i32(65746), i32(5)) == 0 {
			return i32(52)
		}
		if m._str_nocasencmp(v1, i32(65669), i32(5)) != 0 {
			goto l25
		}
		return i32(57)
	l20:
		v2 = i32(6)
		if m._str_nocasencmp(v1, i32(65787), i32(6)) == 0 {
			goto l0
		}
		if m._str_nocasencmp(v1, i32(65648), i32(6)) == 0 {
			return i32(11)
		}
		if m._str_nocasencmp(v1, i32(65755), i32(6)) == 0 {
			return i32(24)
		}
		if m._str_nocasencmp(v1, i32(65801), i32(6)) == 0 {
			return i32(32)
		}
		if m._str_nocasencmp(v1, i32(65762), i32(6)) == 0 {
			return i32(43)
		}
		if m._str_nocasencmp(v1, i32(65794), i32(6)) == 0 {
			return i32(44)
		}
		if m._str_nocasencmp(v1, i32(65691), i32(6)) == 0 {
			return i32(51)
		}
		if m._str_nocasencmp(v1, i32(65625), i32(6)) == 0 {
			return i32(14)
		}
		if m._str_nocasencmp(v1, i32(65808), i32(6)) == 0 {
			return i32(58)
		}
		if m._str_nocasencmp(v1, i32(65698), i32(6)) == 0 {
			return i32(61)
		}
		if m._str_nocasencmp(v1, i32(65641), i32(6)) == 0 {
			return i32(39)
		}
		if m._str_nocasencmp(v1, i32(65873), i32(6)) != 0 {
			goto l25
		}
		return i32(40)
	l21:
		if m._str_nocasencmp(v1, i32(65568), i32(7)) == 0 {
			return i32(12)
		}
		if m._str_nocasencmp(v1, i32(65546), i32(7)) == 0 {
			return i32(22)
		}
		if m._str_nocasencmp(v1, i32(65611), i32(7)) == 0 {
			return i32(47)
		}
		if m._str_nocasencmp(v1, i32(65769), i32(7)) == 0 {
			return i32(34)
		}
		if m._str_nocasencmp(v1, i32(65840), i32(7)) == 0 {
			return i32(33)
		}
		if m._str_nocasencmp(v1, i32(65832), i32(7)) == 0 {
			return i32(48)
		}
		if m._str_nocasencmp(v1, i32(65705), i32(7)) == 0 {
			return i32(26)
		}
		if m._str_nocasencmp(v1, i32(65723), i32(7)) != 0 {
			goto l25
		}
		return i32(41)
	l22:
		if m._str_nocasencmp(v1, i32(65632), i32(8)) == 0 {
			return i32(28)
		}
		if m._str_nocasencmp(v1, i32(65737), i32(8)) == 0 {
			return i32(29)
		}
		if m._str_nocasencmp(v1, i32(65623), i32(8)) == 0 {
			return i32(49)
		}
		if m._str_nocasencmp(v1, i32(65864), i32(8)) != 0 {
			goto l25
		}
		return i32(55)
	l23:
		if m._str_nocasencmp(v1, i32(65536), i32(9)) == 0 {
			goto l27
		}
		if m._str_nocasencmp(v1, i32(65554), i32(9)) == 0 {
			return i32(54)
		}
		if m._str_nocasencmp(v1, i32(65777), i32(9)) == 0 {
			return i32(56)
		}
		if m._str_nocasencmp(v1, i32(65854), i32(9)) != 0 {
			goto l25
		}
		return i32(38)
	l24:
		if m._str_nocasencmp(v1, i32(65586), i32(10)) == 0 {
			return i32(21)
		}
		if m._str_nocasencmp(v1, i32(65655), i32(10)) == 0 {
			return i32(42)
		}
		if m._str_nocasencmp(v1, i32(65821), i32(10)) != 0 {
			goto l25
		}
		return i32(53)
	l26:
		if m._str_nocasencmp(v1, i32(65597), i32(13)) != 0 {
			goto l25
		}
		return i32(37)
	l25:
		binary.LittleEndian.PutUint32(m.memory[int64(uint32(v0))+16:], uint32(v3))
		binary.LittleEndian.PutUint32(m.memory[int64(uint32(v0))+12:], uint32(v1))
		goto l28
	l12:
		if v2 == i32(34) {
			goto l29
		}
		if v2 == i32(39) {
			goto l29
		}
		if v2 == i32(96) {
			goto l29
		}
		if v2 != i32(91) {
			goto l8
		}
	l29:
		t1 := v0
		v3 = v4 + i32(1)
		binary.LittleEndian.PutUint32(m.memory[int64(uint32(t1))+8:], uint32(v3))
		v2 = int32(m.memory[uint32(v1)])
		p2 := v2
		if v2 == i32(91) {
			p2 = i32(93)
		}
		v7 = p2
		v2 = v3
	l32:
		{
			{
				t3 := v8
				v1 = v2
				var p4 int32
				if uint32(t3) > uint32(v1) {
					t5 := v0
					v2 = v1 + i32(1)
					binary.LittleEndian.PutUint32(m.memory[int64(uint32(t5))+8:], uint32(v2))
					v6 = int32(m.memory[uint32(v1+v5)])
					if v6 != 0 {
						goto l30
					}
					p4 = i32(0)
				} else {
					p4 = v6
				}
				if p4 != v7&i32(255) {
					goto l8
				}
				goto l31
			}
		l30:
			v9 = v7 & i32(255)
			if v9 != v6 {
				goto l32
			}
			if uint32(v2) >= uint32(v8) {
				goto l31
			}
			if int32(m.memory[uint32(v2+v5)]) != v9 {
				goto l31
			}
			t6 := v0
			v2 = v1 + i32(2)
			binary.LittleEndian.PutUint32(m.memory[int64(uint32(t6))+8:], uint32(v2))
			goto l32
		}
	l31:
		binary.LittleEndian.PutUint32(m.memory[int64(uint32(v0))+12:], uint32(v3+v5))
		binary.LittleEndian.PutUint32(m.memory[int64(uint32(v0))+16:], uint32(v2-v4-i32(2)))
	}
l28:
	return i32(2)
l27:
	return i32(7)
l8:
	return i32(1)
l11:
	v2 = i32(17)
l0:
	return v2
}
func (m *Module) _sql3lexer_peek(v0 int32) int32 {
	var v1, v2, v3 int32
	var v4, v5 int64
	_ = v3
	v4 = int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v0))+12:]))
	v2 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+8:]))
	v1 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+20:]))
	var p0 int64
	if v1 != 0 {
		p0 = int64(binary.LittleEndian.Uint64(m.memory[uint32(v1):]))
	} else {
		p0 = i64(0)
	}
	v5 = p0
	t1 := m._sql3lexer_next(v0)
	binary.LittleEndian.PutUint32(m.memory[int64(uint32(v0))+20:], uint32(v1))
	binary.LittleEndian.PutUint64(m.memory[int64(uint32(v0))+12:], uint64(v4))
	binary.LittleEndian.PutUint32(m.memory[int64(uint32(v0))+8:], uint32(v2))
	if v1 != 0 {
		binary.LittleEndian.PutUint64(m.memory[uint32(v1):], uint64(v5))
	}
	return t1
}
func (m *Module) _sql3parse_schema_identifier(v0 int32) int32 {
	var v1, v2, v3, v4 int32
	v4 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+24:]))
	{
		v1 = m._sql3lexer_next(v0)
		if v1 != i32(7) {
			v2 = i32(2)
			if v1 != i32(2) {
				goto l0
			}
		}
		v2 = i32(2)
		if v1 == i32(2) {
			if int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+12:])) == 0 {
				goto l0
			}
		}
		{
			if m._sql3lexer_peek(v0) == i32(16) {
				_ = m._sql3lexer_next(v0)
				t0 := v4
				v3 = v0 + i32(12)
				p1 := v3
				if v1 != i32(2) {
					p1 = i32(65896)
				}
				binary.LittleEndian.PutUint64(m.memory[int64(uint32(t0))+8:], uint64(int64(binary.LittleEndian.Uint64(m.memory[uint32(p1):]))))
				if m._sql3lexer_next(v0) != i32(2) {
					goto l0
				}
				if int32(binary.LittleEndian.Uint32(m.memory[uint32(v3):])) != 0 {
					goto l1
				}
				goto l0
			}
			p2 := v0 + i32(12)
			if v1 != i32(2) {
				p2 = i32(65896)
			}
			v3 = p2
		}
	l1:
		t3 := v4
		binary.LittleEndian.PutUint64(m.memory[uint32(t3):], uint64(int64(binary.LittleEndian.Uint64(m.memory[uint32(v3):]))))
		v2 = i32(0)
	}
l0:
	return v2
}
func (m *Module) _sql3parse_column(v0 int32) int32 {
	var v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13 int32
	var v14 int64
	v7 = m.___stack_pointer - i32(16)
	m.___stack_pointer = v7
	{
		v2 = m.Xmalloc(i32(148))
		if v2 == 0 {
			goto l0
		}
		binary.LittleEndian.PutUint32(m.memory[int64(uint32(v0))+20:], uint32(v2+i32(24)))
		if m._sql3lexer_next(v0) != i32(2) {
			goto l0
		}
		t0 := v2
		binary.LittleEndian.PutUint64(m.memory[uint32(t0):], uint64(int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v0))+12:]))))
		{
			if m._sql3lexer_peek(v0) != i32(2) {
				goto l1
			}
		l2:
			if m._sql3lexer_peek(v0) == i32(2) {
				_ = m._sql3lexer_next(v0)
				if v1 != 0 {
					goto l2
				}
				t1 := int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+8:]))
				v1 = t1 - int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+16:]))
				goto l2
			}
			t2 := v2
			binary.LittleEndian.PutUint32(m.memory[int64(uint32(t2))+12:], uint32(int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+8:]))-v1))
			t3 := v2
			binary.LittleEndian.PutUint32(m.memory[int64(uint32(t3))+8:], uint32(int32(binary.LittleEndian.Uint32(m.memory[uint32(v0):]))+v1))
			if m._sql3lexer_peek(v0) != i32(19) {
				goto l1
			}
			_ = m._sql3lexer_next(v0)
			v5 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+8:]))
			t4 := v5
			t5 := v5
			v1 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+4:]))
			p6 := v1
			if uint32(v1) < uint32(v5) {
				p6 = t5
			}
			v3 = t4 - p6
			v1 = i32(0)
		l3:
			{
				if v1+v3 == 0 {
					goto l0
				}
				t7 := v0
				v6 = v1 + v5
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(t7))+8:], uint32(v6+i32(1)))
				t8 := v6
				v6 = int32(binary.LittleEndian.Uint32(m.memory[uint32(v0):]))
				v8 = int32(m.memory[uint32(t8+v6)])
				if v8 == 0 {
					goto l0
				}
				v1 = v1 + i32(1)
				if v8 != i32(41) {
					goto l3
				}
			}
			binary.LittleEndian.PutUint32(m.memory[int64(uint32(v2))+20:], uint32(v1-i32(1)))
			binary.LittleEndian.PutUint32(m.memory[int64(uint32(v2))+16:], uint32(v5+v6))
		}
	l1:
		{
			v1 = m._sql3lexer_peek(v0)
			t9 := int32(i64_shr_u(i64(0x844403608400), int64(uint32(v1))))
			var p10 int32
			if uint32(v1) < uint32(i32(48)) {
				p10 = 1
			}
			if t9&p10 == 0 {
				goto l4
			}
			v9 = v2 + i32(48)
			v10 = v2 + i32(44)
			v11 = v2 + i32(60)
			v12 = v2 + i32(72)
		l15:
			{
				v1 = m._sql3lexer_peek(v0)
				t11 := int32(i64_shr_u(i64(0x844403608400), int64(uint32(v1))))
				var p12 int32
				if uint32(v1) < uint32(i32(48)) {
					p12 = 1
				}
				if t11&p12 == 0 {
					goto l4
				}
				v14 = i64(0)
				v1 = m._sql3lexer_next(v0)
				if v1 == i32(21) {
					if m._sql3lexer_next(v0) != i32(2) {
						v4 = i32(0)
						goto l0
					}
					v14 = int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v0))+12:]))
					v1 = m._sql3lexer_next(v0)
				}
				v4 = i32(0)
				var p13 int32
				{
					{
						{
							{
								{
									switch v1 - i32(22) {
									case 0:
										goto l5
									case 1:
										goto l0
									case 2:
										goto l6
									case 3:
										goto l7
									default:
										goto l8
									}
								l8:
									switch v1 - i32(38) {
									case 0:
										goto l9
									case 1, 2, 3:
										goto l0
									case 4:
										goto l10
									default:
										goto l11
									}
								l11:
									if v1 == i32(10) {
										goto l12
									}
									if v1 == i32(15) {
										goto l9
									}
									if v1 == i32(34) {
										goto l13
									}
									if v1 != i32(47) {
										goto l0
									}
									binary.LittleEndian.PutUint64(m.memory[int64(uint32(v2))+84:], uint64(v14))
									if m._sql3lexer_peek(v0) != i32(19) {
										goto l14
									}
									m._sql3parse_expression(v7+i32(8), v0)
									t14 := v2
									v14 = int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v7))+8:]))
									binary.LittleEndian.PutUint64(m.memory[int64(uint32(t14))+92:], uint64(v14))
									if int32(v14) != 0 {
										goto l15
									}
									goto l0
								}
							l5:
								binary.LittleEndian.PutUint64(m.memory[int64(uint32(v2))+36:], uint64(v14))
								if m._sql3lexer_next(v0) != i32(23) {
									goto l0
								}
								m.memory[int64(uint32(v2))+32] = byte(i32(1))
								m._sql3parse_optionalorder(v0, v10)
								if m._sql3parse_optionalconflitclause(v0, v9) != 0 {
									goto l0
								}
								if m._sql3lexer_peek(v0) != i32(37) {
									goto l15
								}
								_ = m._sql3lexer_next(v0)
								m.memory[int64(uint32(v2))+33] = byte(i32(1))
								goto l15
							l12:
								binary.LittleEndian.PutUint64(m.memory[int64(uint32(v2))+52:], uint64(v14))
								if m._sql3lexer_next(v0) != i32(46) {
									goto l0
								}
								m.memory[int64(uint32(v2))+34] = byte(i32(1))
								if m._sql3parse_optionalconflitclause(v0, v11) == 0 {
									goto l15
								}
								goto l0
							l7:
								t15 := v2
								v1 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v2))+76:])) + i32(1)
								binary.LittleEndian.PutUint32(m.memory[int64(uint32(t15))+76:], uint32(v1))
								v1 = m._sql3_array_grow(int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v2))+80:])), v1, i32(16))
								if v1 == 0 {
									goto l0
								}
								binary.LittleEndian.PutUint32(m.memory[int64(uint32(v2))+80:], uint32(v1))
								t16 := v1
								v1 = t16 + int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v2))+76:]))<<4
								binary.LittleEndian.PutUint64(m.memory[uint32(v1-i32(16)):], uint64(v14))
								m._sql3parse_expression(v7+i32(8), v0)
								t17 := v1 - i32(8)
								v14 = int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v7))+8:]))
								binary.LittleEndian.PutUint64(m.memory[uint32(t17):], uint64(v14))
								if int32(v14) != 0 {
									goto l15
								}
								goto l0
							}
						l14:
							m._sql3lexer_checkskip(v0)
							v5 = int32(binary.LittleEndian.Uint32(m.memory[uint32(v0):]))
							v8 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+8:]))
							v1 = v8
							t18 := v1
							v3 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+4:]))
							if uint32(t18) < uint32(v3) {
								t19 := v0
								v1 = v1 + i32(1)
								binary.LittleEndian.PutUint32(m.memory[int64(uint32(t19))+8:], uint32(v1))
								v6 = int32(m.memory[uint32(v5+v8)])
								if v6 == i32(39) {
									goto l22
								}
								if v6 == i32(34) {
									goto l22
								}
							}
							p20 := v3
							if uint32(v1) > uint32(v3) {
								p20 = v1
							}
							v4 = p20
						l20:
							{
								if v1 == v4 {
									v1 = v4
									goto l17
								}
								v3 = int32(m.memory[uint32(v1+v5)])
								v6 = v3 - i32(9)
								var p22 int32
								if uint32(v6) <= uint32(i32(23)) {
									p22 = 1
								}
								p21 := i32(0)
								if i32_shl(i32(1), v6)&i32(8388639) != 0 {
									p21 = p22
								}
								if p21 != 0 {
									goto l17
								}
								switch v3 - i32(41) {
								case 0, 3:
									goto l17
								case 1, 2:
									goto l18
								default:
									goto l19
								}
							l19:
								if v3 == 0 {
									goto l17
								}
								if v3 == i32(59) {
									goto l17
								}
							l18:
								t23 := v0
								v1 = v1 + i32(1)
								binary.LittleEndian.PutUint32(m.memory[int64(uint32(t23))+8:], uint32(v1))
								goto l20
							}
						}
					l6:
						m.memory[int64(uint32(v2))+35] = byte(i32(1))
						binary.LittleEndian.PutUint64(m.memory[int64(uint32(v2))+64:], uint64(v14))
						if m._sql3parse_optionalconflitclause(v0, v12) == 0 {
							goto l15
						}
						goto l0
					l9:
						binary.LittleEndian.PutUint64(m.memory[int64(uint32(v2))+128:], uint64(v14))
						if v1 == i32(38) {
							v1 = m._sql3lexer_next(v0)
							if v1 == i32(39) {
								v1 = m._sql3lexer_next(v0)
							}
							if v1 != i32(15) {
								goto l0
							}
						}
						if m._sql3lexer_peek(v0) != i32(19) {
							goto l0
						}
						m._sql3parse_expression(v7+i32(8), v0)
						t24 := v2
						v14 = int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v7))+8:]))
						binary.LittleEndian.PutUint64(m.memory[int64(uint32(t24))+136:], uint64(v14))
						if int32(v14) == 0 {
							goto l0
						}
						v1 = m._sql3lexer_peek(v0)
						binary.LittleEndian.PutUint32(m.memory[int64(uint32(v2))+144:], uint32(i32(0)))
						if v1&i32(62) != i32(40) {
							goto l15
						}
						_ = m._sql3lexer_next(v0)
						t26 := v2
						p25 := i32(2)
						if v1 == i32(40) {
							p25 = i32(1)
						}
						binary.LittleEndian.PutUint32(m.memory[int64(uint32(t26))+144:], uint32(p25))
						goto l15
					}
				l10:
					binary.LittleEndian.PutUint64(m.memory[int64(uint32(v2))+116:], uint64(v14))
					v1 = m._sql3parse_foreignkey_clause(v0)
					if v1 == 0 {
						goto l0
					}
					binary.LittleEndian.PutUint32(m.memory[int64(uint32(v2))+124:], uint32(v1))
					goto l15
				l13:
					binary.LittleEndian.PutUint64(m.memory[int64(uint32(v2))+100:], uint64(v14))
					if m._sql3lexer_next(v0) != i32(2) {
						goto l0
					}
					t27 := v2
					binary.LittleEndian.PutUint64(m.memory[int64(uint32(t27))+108:], uint64(int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v0))+12:]))))
					goto l15
				}
			l22:
				{
					if uint32(v1) >= uint32(v3) {
						goto l21
					}
					t28 := v0
					v4 = v1
					v1 = v4 + i32(1)
					binary.LittleEndian.PutUint32(m.memory[int64(uint32(t28))+8:], uint32(v1))
					v13 = int32(m.memory[uint32(v4+v5)])
					if v13 == 0 {
						goto l21
					}
					if v6 != v13 {
						goto l22
					}
					if uint32(v1) >= uint32(v3) {
						goto l17
					}
					t29 := v6
					if t29 != int32(m.memory[uint32(v1+v5)]) {
						goto l17
					}
					t30 := v0
					v1 = v4 + i32(2)
					binary.LittleEndian.PutUint32(m.memory[int64(uint32(t30))+8:], uint32(v1))
					goto l22
				}
			l21:
				v3 = i32(0)
				if v6 != 0 {
					p13 = i32(0)
					goto l23
				}
				_ = i32(0)
			l17:
				v3 = v1 - v8
				p13 = v5 + v8
			l23:
				v4 = p13
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(v2))+96:], uint32(v3))
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(v2))+92:], uint32(v4))
				goto l15
			}
		}
	l4:
		v4 = v2
	}
l0:
	m.___stack_pointer = v7 + i32(16)
	return v4
}
func (m *Module) _sql3_array_grow(v0, v1, v2 int32) int32 {
	var v3 int32
	if int32(bits.OnesCount32(uint32(v1))) == i32(1) {
		{
			p0 := v1 << 1
			if v1 == i32(1) {
				p0 = i32(1)
			}
			v2 = p0 * v2
			if v0 == 0 {
				v0 = m.Xmalloc(v2)
				goto l0
			}
			if uint32(v2) < uint32(i32(17)) {
				goto l0
			}
			t1 := int32(binary.LittleEndian.Uint32(m.memory[uint32(i32(65952)):]))
			v1 = m.Xmalloc(v2)
			v3 = t1 - v0
			p2 := v2
			if uint32(v2) > uint32(v3) {
				p2 = v3
			}
			v2 = p2
			if v2 != 0 {
				memory_copy(m.memory, uint32(v1), uint32(v0), uint32(v2))
			}
			v0 = v1
		}
	l0:
	}
	return v0
}
func (m *Module) _sql3parse_expression(v0, v1 int32) {
	var v2, v3, v4, v5, v6, v7, v8, v9, v10, v11 int32
	m._sql3lexer_checkskip(v1)
	{
		v4 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v1))+4:]))
		t0 := v4
		v8 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v1))+8:]))
		if uint32(t0) <= uint32(v8) {
			goto l0
		}
		t1 := v1
		v2 = v8 + i32(1)
		binary.LittleEndian.PutUint32(m.memory[int64(uint32(t1))+8:], uint32(v2))
		t2 := v8
		v5 = int32(binary.LittleEndian.Uint32(m.memory[uint32(v1):]))
		v10 = t2 + v5
		if int32(m.memory[uint32(v10)]) != i32(40) {
			goto l0
		}
		v11 = i32(2) - v4
		v7 = i32(1)
	l2:
		v3 = v2
		if uint32(v2) < uint32(v4) {
			t3 := v1
			v2 = v2 + i32(1)
			binary.LittleEndian.PutUint32(m.memory[int64(uint32(t3))+8:], uint32(v2))
			v6 = int32(m.memory[uint32(v3+v5)])
			switch v6 - i32(34) {
			case 0, 5:
				goto l8
			case 1, 2, 3, 4, 8, 9, 10, 12:
				goto l2
			case 6:
				goto l3
			case 7:
				goto l4
			case 11:
				goto l5
			case 13:
				goto l6
			default:
				goto l7
			}
		l8:
			{
				if uint32(v2) >= uint32(v4) {
					goto l2
				}
				t4 := v1
				v3 = v2
				v2 = v3 + i32(1)
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(t4))+8:], uint32(v2))
				v9 = int32(m.memory[uint32(v3+v5)])
				if v9 == 0 {
					goto l2
				}
				if v6 != v9 {
					goto l8
				}
				if uint32(v2) >= uint32(v4) {
					goto l2
				}
				if int32(m.memory[uint32(v2+v5)]) != v6 {
					goto l2
				}
				t5 := v1
				v2 = v3 + i32(2)
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(t5))+8:], uint32(v2))
				goto l8
			}
		l5:
			if uint32(v2) >= uint32(v4) {
				goto l2
			}
			if int32(m.memory[uint32(v2+v5)]) != i32(45) {
				goto l2
			}
		l11:
			{
				if v2 == v4 {
					goto l9
				}
				t6 := v1
				v3 = v2 + i32(1)
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(t6))+8:], uint32(v3))
				v6 = v2 + v5
				v2 = v3
				v3 = int32(m.memory[uint32(v6)])
				switch v3 - i32(10) {
				case 0, 3:
					goto l10
				case 1, 2:
					goto l11
				default:
					goto l12
				}
			l12:
				if v3 != 0 {
					goto l11
				}
			l10:
			}
			goto l2
		l6:
			if uint32(v2) >= uint32(v4) {
				goto l2
			}
			if int32(m.memory[uint32(v2+v5)]) != i32(42) {
				goto l2
			}
			binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+8:], uint32(v3+i32(2)))
			v2 = v3 + i32(4)
		l14:
			{
				if v2+v11 == i32(4) {
					goto l9
				}
				t7 := v1
				v3 = v2 - i32(1)
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(t7))+8:], uint32(v3))
				v6 = v2 + v5
				v9 = int32(m.memory[uint32(v6-i32(2))])
				if v9 != i32(42) {
					if v9 != 0 {
						goto l13
					}
					v2 = v3
					goto l2
				}
				if uint32(v3) >= uint32(v4) {
					goto l13
				}
				if int32(m.memory[uint32(v6-i32(1))]) != i32(47) {
					goto l13
				}
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+8:], uint32(v2))
				goto l2
			l13:
				v2 = v2 + i32(1)
				goto l14
			}
		l4:
			v7 = v7 - i32(1)
			if v7 != 0 {
				goto l2
			}
			goto l15
		l7:
			if v6 != 0 {
				goto l2
			}
		}
		if v7 == 0 {
			goto l15
		}
		binary.LittleEndian.PutUint64(m.memory[uint32(v0):], uint64(i64(0)))
		return
	l15:
		binary.LittleEndian.PutUint32(m.memory[uint32(v0):], uint32(v10))
		binary.LittleEndian.PutUint32(m.memory[int64(uint32(v0))+4:], uint32(v2-v8))
		return
	l3:
		v7 = v7 + i32(1)
		goto l2
	l9:
		v2 = v4
		goto l2
	}
l0:
	binary.LittleEndian.PutUint64(m.memory[uint32(v0):], uint64(i64(0)))
}
func (m *Module) _sql3parse_optionalorder(v0, v1 int32) {
	var v2 int32
	v2 = m._sql3lexer_peek(v0)
	binary.LittleEndian.PutUint32(m.memory[uint32(v1):], uint32(i32(0)))
	if uint32(v2-i32(35)) <= uint32(i32(1)) {
		_ = m._sql3lexer_next(v0)
		t1 := v1
		p0 := i32(2)
		if v2 == i32(35) {
			p0 = i32(1)
		}
		binary.LittleEndian.PutUint32(m.memory[uint32(t1):], uint32(p0))
	}
}
func (m *Module) _sql3parse_optionalconflitclause(v0, v1 int32) int32 {
	var v2, v3 int32
	v3 = m._sql3lexer_peek(v0)
	binary.LittleEndian.PutUint32(m.memory[uint32(v1):], uint32(i32(0)))
	if v3 != i32(27) {
		goto l0
	}
	_ = m._sql3lexer_next(v0)
	v2 = i32(2)
	if m._sql3lexer_next(v0) != i32(28) {
		goto l0
	}
	v0 = m._sql3lexer_next(v0)
	if uint32(v0-i32(29)) > uint32(i32(4)) {
		goto l0
	}
	binary.LittleEndian.PutUint32(m.memory[uint32(v1):], uint32(v0-i32(28)))
	v2 = i32(0)
l0:
	return v2
}
func (m *Module) _sql3parse_foreignkey_clause(v0 int32) int32 {
	var v1, v2, v3 int32
	{
		v1 = m.Xmalloc(i32(36))
		if v1 == 0 {
			goto l0
		}
		if m._sql3lexer_next(v0) != i32(2) {
			goto l0
		}
		t0 := v1
		binary.LittleEndian.PutUint64(m.memory[uint32(t0):], uint64(int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v0))+12:]))))
		if m._sql3lexer_peek(v0) == i32(19) {
			_ = m._sql3lexer_next(v0)
		l1:
			{
				if m._sql3lexer_next(v0) != i32(2) {
					goto l0
				}
				t1 := v1
				v2 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v1))+8:])) + i32(1)
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(t1))+8:], uint32(v2))
				v3 = m._sql3_array_grow(int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v1))+12:])), v2, i32(8))
				if v3 == 0 {
					goto l0
				}
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+12:], uint32(v3))
				t2 := v3 + v2<<3 - i32(8)
				binary.LittleEndian.PutUint64(m.memory[uint32(t2):], uint64(int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v0))+12:]))))
				t3 := m._sql3lexer_peek(v0)
				v3 = m._sql3lexer_next(v0)
				if t3 == i32(18) {
					goto l1
				}
			}
			if v3 != i32(20) {
				goto l0
			}
		}
	l4:
		{
			{
				v3 = m._sql3lexer_peek(v0)
				v2 = v3 - i32(27)
				var p5 int32
				if uint32(v2) <= uint32(i32(26)) {
					p5 = 1
				}
				p4 := i32(0)
				if i32_shl(i32(1), v2)&i32(0x6000001) != 0 {
					p4 = p5
				}
				if p4 != 0 {
					goto l2
				}
				if v3 == i32(10) {
					goto l2
				}
				return v1
			}
		l2:
			_ = m._sql3lexer_next(v0)
			var p6 int32
			if v3 != i32(10) {
				if v3 != i32(27) {
					if v3 != i32(52) {
						p6 = i32(0)
						goto l3
					}
					_ = i32(0)
					if m._sql3lexer_next(v0) != i32(2) {
						goto l0
					}
					t7 := v1
					binary.LittleEndian.PutUint64(m.memory[int64(uint32(t7))+24:], uint64(int64(binary.LittleEndian.Uint64(m.memory[int64(uint32(v0))+12:]))))
					goto l4
				}
				v2 = m._sql3lexer_next(v0)
				if uint32(v2-i32(45)) < uint32(i32(-2)) {
					goto l0
				}
				switch m._sql3lexer_next(v0) - i32(45) {
				case 0:
					goto l5
				case 3:
					goto l6
				case 4:
					goto l7
				case 5:
					goto l8
				default:
					goto l0
				}
			l6:
				if v2 == i32(44) {
					binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+20:], uint32(i32(3)))
					goto l4
				}
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+16:], uint32(i32(3)))
				goto l4
			l7:
				if v2 == i32(44) {
					binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+20:], uint32(i32(4)))
					goto l4
				}
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+16:], uint32(i32(4)))
				goto l4
			l5:
				v3 = m._sql3lexer_next(v0)
				if uint32(v3-i32(48)) < uint32(i32(-2)) {
					goto l0
				}
				if v3 == i32(46) {
					if v2 == i32(44) {
						binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+20:], uint32(i32(1)))
						goto l4
					}
					binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+16:], uint32(i32(1)))
					goto l4
				}
				if v2 == i32(44) {
					binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+20:], uint32(i32(2)))
					goto l4
				}
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+16:], uint32(i32(2)))
				goto l4
			l8:
				if m._sql3lexer_next(v0) != i32(51) {
					goto l0
				}
				if v2 == i32(44) {
					binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+20:], uint32(i32(5)))
					goto l4
				}
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(v1))+16:], uint32(i32(5)))
				goto l4
			}
			v3 = m._sql3lexer_next(v0)
			p6 = i32(1)
		l3:
			v2 = p6
			if v3 != i32(53) {
				goto l0
			}
			t9 := v1
			p8 := i32(1)
			if v2 != 0 {
				p8 = i32(4)
			}
			binary.LittleEndian.PutUint32(m.memory[int64(uint32(t9))+32:], uint32(p8))
			if m._sql3lexer_peek(v0) != i32(54) {
				goto l4
			}
			_ = m._sql3lexer_next(v0)
			{
				switch m._sql3lexer_next(v0) - i32(55) {
				case 0:
					goto l9
				case 1:
					goto l10
				default:
					goto l0
				}
			l9:
				t11 := v1
				p10 := i32(2)
				if v2 != 0 {
					p10 = i32(5)
				}
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(t11))+32:], uint32(p10))
				goto l4
			}
		l10:
			t13 := v1
			p12 := i32(3)
			if v2 != 0 {
				p12 = i32(6)
			}
			binary.LittleEndian.PutUint32(m.memory[int64(uint32(t13))+32:], uint32(p12))
			goto l4
		}
	}
l0:
	return i32(0)
}
func (m *Module) _symbol_is_comment(v0, v1 int32) int32 {
	var v2 int32
	{
		{
			switch v0 - i32(45) {
			case 0:
				goto l0
			case 2:
				goto l2
			default:
				goto l1
			}
		l0:
			v0 = i32(1)
			v2 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v1))+8:])) + i32(1)
			t0 := v2
			if uint32(t0) >= uint32(int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v1))+4:]))) {
				goto l1
			}
			if int32(m.memory[uint32(int32(binary.LittleEndian.Uint32(m.memory[uint32(v1):]))+v2)]) != i32(45) {
				goto l1
			}
			goto l3
		}
	l2:
		v0 = i32(1)
		v2 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v1))+8:])) + i32(1)
		t1 := v2
		if uint32(t1) >= uint32(int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v1))+4:]))) {
			goto l1
		}
		if int32(m.memory[uint32(int32(binary.LittleEndian.Uint32(m.memory[uint32(v1):]))+v2)]) == i32(42) {
			goto l3
		}
	}
l1:
	v0 = i32(0)
l3:
	return v0
}
func (m *Module) _sql3lexer_comment(v0 int32) {
	var v1, v2, v3, v4, v5, v6, v7, v8, v9, v10 int32
	v6 = int32(binary.LittleEndian.Uint32(m.memory[uint32(v0):]))
	var p0 int32
	{
		v7 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+4:]))
		t1 := v7
		v1 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+8:]))
		if uint32(t1) <= uint32(v1) {
			v3 = v1
			p0 = i32(0)
			goto l0
		}
		t2 := v0
		v3 = v1 + i32(1)
		binary.LittleEndian.PutUint32(m.memory[int64(uint32(t2))+8:], uint32(v3))
		var p3 int32
		if int32(m.memory[uint32(v1+v6)]) == i32(47) {
			p3 = 1
		}
		p0 = p3
	}
l0:
	v4 = p0
	{
		if uint32(v3) >= uint32(v7) {
			v1 = v3
			goto l1
		}
		t4 := v0
		v1 = v3 + i32(1)
		binary.LittleEndian.PutUint32(m.memory[int64(uint32(t4))+8:], uint32(v1))
		var p5 int32
		if int32(m.memory[uint32(v3+v6)]) == i32(42) {
			p5 = 1
		}
		v2 = p5
	}
l1:
	p6 := v7
	if uint32(v1) > uint32(v7) {
		p6 = v1
	}
	v3 = p6
	v10 = v1 + v6
	v8 = v2 & v4
	v2 = v1
l3:
	{
		t7 := v3
		v4 = v2
		if t7 == v4 {
			v2 = v3
			v5 = i32(1)
			goto l2
		}
		t8 := v0
		v2 = v4 + i32(1)
		binary.LittleEndian.PutUint32(m.memory[int64(uint32(t8))+8:], uint32(v2))
		v5 = v4 + v6
		v9 = int32(m.memory[uint32(v5)])
		if v9 != 0 {
			if v8 != 0 {
				if uint32(v2) >= uint32(v7) {
					goto l3
				}
				if v9 != i32(42) {
					goto l3
				}
				if int32(m.memory[int64(uint32(v5))+1]) != i32(47) {
					goto l3
				}
				t9 := v0
				v2 = v4 + i32(2)
				binary.LittleEndian.PutUint32(m.memory[int64(uint32(t9))+8:], uint32(v2))
				v5 = i32(0)
				goto l2
			}
			v5 = i32(0)
			switch v9 - i32(10) {
			case 0, 3:
				goto l2
			default:
				goto l3
			}
		}
	}
	v5 = i32(1)
	v2 = v4 + i32(1)
l2:
	v0 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+20:]))
	if v0 != 0 {
		binary.LittleEndian.PutUint32(m.memory[uint32(v0):], uint32(v10))
		t11 := v0
		p10 := i32(-1)
		if v8 != 0 {
			p10 = i32(-2)
		}
		p12 := p10
		if v5 != 0 {
			p12 = i32(0)
		}
		binary.LittleEndian.PutUint32(m.memory[int64(uint32(t11))+4:], uint32(p12-v1+v2))
	}
}
func (m *Module) _str_nocasencmp(v0, v1, v2 int32) int32 {
	var v3, v4, v5, v6 int32
l1:
	{
		if v2 == 0 {
			goto l0
		}
		v4 = int32(m.memory[uint32(v0)])
		p0 := v4
		if uint32((v4-i32(65))&i32(255)) < uint32(i32(26)) {
			p0 = v4 | i32(32)
		}
		v5 = p0
		t1 := v5
		v3 = int32(m.memory[uint32(v1)])
		p2 := v3
		if uint32((v3-i32(65))&i32(255)) < uint32(i32(26)) {
			p2 = v3 | i32(32)
		}
		v3 = p2
		if t1 == v3 {
			if v4 == 0 {
				goto l0
			}
			v2 = v2 - i32(1)
			v1 = v1 + i32(1)
			v0 = v0 + i32(1)
			goto l1
		}
	}
	v6 = v5 - v3
l0:
	return v6
}
func (m *Module) _sql3lexer_checkskip(v0 int32) {
	var v1, v2, v3 int32
l1:
	v1 = i32(0)
	{
		v2 = int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+8:]))
		t0 := v2
		if uint32(t0) >= uint32(int32(binary.LittleEndian.Uint32(m.memory[int64(uint32(v0))+4:]))) {
			goto l0
		}
		v1 = int32(m.memory[uint32(int32(binary.LittleEndian.Uint32(m.memory[uint32(v0):]))+v2)])
		v3 = v1 - i32(9)
		if uint32(v3) > uint32(i32(23)) {
			goto l0
		}
		if i32_shl(i32(1), v3)&i32(8388639) == 0 {
			goto l0
		}
		binary.LittleEndian.PutUint32(m.memory[int64(uint32(v0))+8:], uint32(v2+i32(1)))
		goto l1
	}
l0:
	if m._symbol_is_comment(v1, v0) != 0 {
		m._sql3lexer_comment(v0)
		goto l1
	}
}
func (m *Module) Xmemory() Memory {
	return (*wasmMemory)(&m.memory)
}

//go:nosplit
func i32(x int32) int32 { return x }

//go:nosplit
func i64(x int64) int64 { return x }

//go:nosplit
func i32_shl(x, y int32) int32 {
	return x << (y & 31)
}

//go:nosplit
func i32_shr_u(x, y int32) int32 {
	return int32(uint32(x) >> (y & 31))
}

//go:nosplit
func i64_shr_u(x, y int64) int64 {
	return int64(uint64(x) >> (y & 63))
}

func memory_grow(mem *[]byte, delta, max int64) int64 {
	buf := *mem
	len := len(buf)
	old := int64(len) >> 16
	if delta == 0 {
		return old
	}
	new := old + delta
	add := int(new)<<16 - len
	if new > max || add < 0 {
		return -1
	}
	*mem = append(buf, make([]byte, add)...)
	return old
}

func memory_copy[T uint32 | uint64](mem []byte, dest, src, n T) {
	x := uint(min(uint64(dest), math.MaxUint))
	z := uint(min(uint64(src), math.MaxUint))
	c := uint(min(uint64(n), math.MaxUint))
	y := x + c
	w := z + c
	copy(mem[x:y], mem[z:w])
}

const (
	data0 = "temporary\x00primary\x00initially\x00key\x00without\x00abort\x00not\x00constraint\x00autoincrement\x00default\x00set\x00restrict\x00conflict\x00always\x00exists\x00references\x00as\x00alter\x00drop\x00temp\x00to\x00no\x00action\x00column\x00foreign\x00null\x00fail\x00virtual\x00check\x00rollback\x00match\x00if\x00unique\x00delete\x00collate\x00immediate\x00create\x00update\x00ignore\x00rename\x00table\x00deferrable\x00cascade\x00replace\x00rowid\x00generated\x00deferred\x00stored\x00add\x00desc\x00asc\x00\x00\x00\x00\x90\x00\x01\x00\x04\x00\x00\x00\x15\x00\x00\x00\x16\x00\x00\x00\x00\x00\x00\x00\x18\x00\x00\x00\x19\x00\x00\x00\x1a\x00\x00\x00\x16\x00\x00\x00\x00\x00\x00\x00\x18\x00\x00\x00\x19\x00\x00\x00\x1a"
	data1 = "\x02\x00\xb0\x01\x01"
)
