// Code generated by wasm2go. DO NOT EDIT.

package sql3parse_table

import (
	"encoding/binary"
	"math"
	"math/bits"
)

type Module struct {
	memory           []byte
	maxMem           int64
	___stack_pointer int32
}

func New() *Module {
	m := new(Module)
	m.maxMem = 65536
	m.memory = make([]byte, 0x20000)
	memory_init(m.memory, data0, uint32(i32(65536)), 0, len(data0))
	m.___stack_pointer = i32(65536)
	return m
}

type Memory = interface {
	Slice() *[]byte
	Grow(delta, max int64) int64
}
type wasmMemory []byte

func (m *wasmMemory) Slice() *[]byte {
	return (*[]byte)(m)
}
func (m *wasmMemory) Grow(delta, max int64) int64 {
	return memory_grow((*[]byte)(m), delta, max)
}
func (m *Module) Xmalloc(v0 int32) int32 {
	var v1, v2, v3, v4, v5, v6 int32
	{
		if v0 == 0 {
			goto l0
		}
		v2 = (v0 + i32(15)) & i32(-16)
		t0 := int32(load32(m.memory[uint32(i32(65948)):]))
		v1 = t0
		t1 := int32(load32(m.memory[uint32(i32(65952)):]))
		v3 = t1
		v0 = v3
	l2:
		v0 = v1 - v0
		if uint32(v0) < uint32(v2) {
			v5 = v2 - v0 + i32(0xffff)
			v6 = int32(uint32(v5) >> 16)
			t2 := int32(memory_grow(&m.memory, int64(v6), m.maxMem))
			v4 = t2
			if v4 == i32(-1) {
				goto l0
			}
			t3 := v1
			v0 = v4 << 16
			if t3 != v0 {
				goto l1
			}
			store32(m.memory[uint32(i32(65948)):], uint32(v1+v5&i32(-65536)))
		}
		store32(m.memory[uint32(i32(65952)):], uint32(v2+v3))
		return v3
	l1:
		store32(m.memory[uint32(i32(65952)):], uint32(v0))
		v1 = (v4 + v6) << 16
		store32(m.memory[uint32(i32(65948)):], uint32(v1))
		v3 = v0
		goto l2
	}
l0:
	return i32(0)
}
func (m *Module) Xsql3parse_table(v0, v1, v2 int32) int32 {
	var v3, v4, v5, v6, v7, v8, v9, v10, v11 int32
	var v12 int64
	t0 := m.___stack_pointer
	v3 = t0 + i32(-64)
	m.___stack_pointer = v3
	{
		if v0 == 0 {
			v0 = i32(0)
			if v2 == 0 {
				goto l0
			}
			store32(m.memory[uint32(v2):], uint32(i32(2)))
			goto l0
		}
		{
			if v1 != 0 {
				goto l1
			}
			t1 := m._strlen(v0)
			v1 = t1
			if v1 != 0 {
				goto l1
			}
			v0 = i32(0)
			if v2 == 0 {
				goto l0
			}
			store32(m.memory[uint32(v2):], uint32(i32(2)))
			goto l0
		}
	l1:
		if v2 != 0 {
			store32(m.memory[uint32(v2):], uint32(i32(0)))
		}
		{
			var p2 int32
			{
				{
					t3 := m.Xmalloc(i32(64))
					v8 = t3
					if v8 != 0 {
						store32(m.memory[int64(uint32(v3))+28:], uint32(i32(0)))
						store64(m.memory[int64(uint32(v3))+20:], uint64(i64(0)))
						store32(m.memory[int64(uint32(v3))+16:], uint32(v1))
						store32(m.memory[int64(uint32(v3))+12:], uint32(v0))
						store32(m.memory[int64(uint32(v3))+36:], uint32(v8))
						store32(m.memory[int64(uint32(v3))+32:], uint32(v8+i32(16)))
						v0 = i32(3)
						v5 = v3 + i32(12)
						t4 := m._sql3lexer_next(v5)
						v1 = t4
						if v1 != i32(57) {
							if v1 != i32(6) {
								goto l2
							}
							t5 := int32(load32(m.memory[int64(uint32(v3))+36:]))
							v4 = t5
							store32(m.memory[int64(uint32(v4))+44:], uint32(i32(1)))
							t6 := m._sql3lexer_next(v5)
							v1 = t6
							var p7 int32
							if v1 == i32(7) {
								m.memory[int64(uint32(v4))+24] = byte(i32(1))
								t8 := m._sql3lexer_next(v5)
								p7 = t8
							} else {
								p7 = v1
							}
							if p7 != i32(8) {
								goto l2
							}
							v1 = v3 + i32(12)
							t9 := m._sql3lexer_peek(v1)
							if t9 == i32(9) {
								_ = m._sql3lexer_next(v1)
								v0 = i32(2)
								t11 := m._sql3lexer_next(v1)
								if t11 != i32(10) {
									goto l2
								}
								t12 := m._sql3lexer_next(v1)
								if t12 != i32(11) {
									goto l2
								}
								m.memory[int64(uint32(v4))+25] = byte(i32(1))
							}
							v1 = v3 + i32(12)
							t13 := m._sql3parse_schema_identifier(v1)
							v0 = t13
							if v0 != 0 {
								goto l2
							}
							v0 = i32(3)
							{
								t14 := m._sql3lexer_next(v1)
								switch t14 - i32(15) {
								case 0:
									goto l2
								case 4:
									goto l7
								default:
									goto l3
								}
							}
						l7:
							{
								v0 = i32(2)
								v1 = v3 + i32(12)
								t15 := m._sql3lexer_peek(v1)
								if t15 != i32(2) {
									goto l2
								}
								t16 := m._sql3parse_column(v1)
								v5 = t16
								if v5 == 0 {
									goto l2
								}
								t17 := int32(load32(m.memory[int64(uint32(v4))+28:]))
								t18 := v4
								v0 = t17 + i32(1)
								store32(m.memory[int64(uint32(t18))+28:], uint32(v0))
								t19 := int32(load32(m.memory[int64(uint32(v4))+32:]))
								t20 := m._sql3_array_grow(t19, v0, i32(4))
								v1 = t20
								if v1 == 0 {
									t21 := int32(load32(m.memory[int64(uint32(v4))+28:]))
									store32(m.memory[int64(uint32(v4))+28:], uint32(t21-i32(1)))
									v0 = i32(1)
									goto l2
								}
								store32(m.memory[int64(uint32(v4))+32:], uint32(v1))
								v0 = i32(2)
								t22 := int32(load32(m.memory[int64(uint32(v4))+28:]))
								store32(m.memory[uint32(v1+t22<<2-i32(4)):], uint32(v5))
								{
									t23 := m._sql3lexer_peek(v3 + i32(12))
									switch t23 - i32(18) {
									case 0:
										goto l5
									case 2:
										goto l6
									default:
										goto l2
									}
								}
							l5:
								v0 = v3 + i32(12)
								_ = m._sql3lexer_next(v0)
								t25 := m._sql3lexer_peek(v0)
								v0 = t25 - i32(21)
								if uint32(v0) > uint32(i32(5)) {
									goto l7
								}
								if i32_shr_u(i32(59), v0)&i32(1) == 0 {
									goto l7
								}
							}
							t26 := int32(load32(m.memory[int64(uint32(v0<<2))+65904:]))
							p2 = t26
							goto l8
						}
						t27 := int32(load32(m.memory[int64(uint32(v3))+36:]))
						v1 = t27
						v4 = v3 + i32(12)
						t28 := m._sql3lexer_next(v4)
						if t28 != i32(8) {
							goto l2
						}
						t29 := m._sql3parse_schema_identifier(v4)
						v0 = t29
						if v0 != 0 {
							goto l2
						}
						t30 := m._sql3lexer_next(v4)
						v5 = t30
						t31 := m._sql3lexer_peek(v4)
						v4 = t31
						v0 = i32(3)
						{
							{
								{
									switch v5 - i32(58) {
									case 0:
										goto l9
									case 1:
										goto l10
									case 2:
										goto l11
									default:
										goto l2
									}
								l9:
									{
										switch v4 - i32(61) {
										case 0:
											goto l12
										case 1:
											goto l13
										default:
											goto l14
										}
									l13:
										v4 = v3 + i32(12)
										_ = m._sql3lexer_next(v4)
										v0 = i32(2)
										store32(m.memory[int64(uint32(v1))+44:], uint32(i32(2)))
										t33 := m._sql3lexer_next(v4)
										if t33 != i32(2) {
											goto l2
										}
										t34 := int64(load64(m.memory[int64(uint32(v3))+24:]))
										store64(m.memory[int64(uint32(v1))+56:], uint64(t34))
										goto l15
									}
								l12:
									_ = m._sql3lexer_next(v3 + i32(12))
								l14:
									store32(m.memory[int64(uint32(v1))+44:], uint32(i32(3)))
									v0 = i32(2)
									v4 = v3 + i32(12)
									t36 := m._sql3lexer_next(v4)
									if t36 != i32(2) {
										goto l2
									}
									t37 := int64(load64(m.memory[int64(uint32(v3))+24:]))
									store64(m.memory[int64(uint32(v1))+48:], uint64(t37))
									t38 := m._sql3lexer_next(v4)
									if t38 != i32(62) {
										goto l2
									}
									t39 := m._sql3lexer_next(v4)
									if t39 != i32(2) {
										goto l2
									}
									t40 := int64(load64(m.memory[int64(uint32(v3))+24:]))
									store64(m.memory[int64(uint32(v1))+56:], uint64(t40))
									goto l15
								}
							l10:
								if v4 == i32(61) {
									_ = m._sql3lexer_next(v3 + i32(12))
								}
								store32(m.memory[int64(uint32(v1))+44:], uint32(i32(4)))
								v0 = i32(2)
								v4 = v3 + i32(12)
								t42 := m._sql3lexer_peek(v4)
								if t42 != i32(2) {
									goto l2
								}
								t43 := m._sql3parse_column(v4)
								v5 = t43
								if v5 == 0 {
									goto l2
								}
								v0 = i32(1)
								t44 := int32(load32(m.memory[int64(uint32(v1))+28:]))
								t45 := v1
								v4 = t44 + i32(1)
								store32(m.memory[int64(uint32(t45))+28:], uint32(v4))
								t46 := int32(load32(m.memory[int64(uint32(v1))+32:]))
								t47 := m._sql3_array_grow(t46, v4, i32(4))
								v4 = t47
								if v4 == 0 {
									t48 := int32(load32(m.memory[int64(uint32(v1))+28:]))
									store32(m.memory[int64(uint32(v1))+28:], uint32(t48-i32(1)))
									goto l2
								}
								store32(m.memory[int64(uint32(v1))+32:], uint32(v4))
								t49 := int32(load32(m.memory[int64(uint32(v1))+28:]))
								store32(m.memory[uint32(v4+t49<<2-i32(4)):], uint32(v5))
								goto l15
							}
						l11:
							if v4 == i32(61) {
								_ = m._sql3lexer_next(v3 + i32(12))
							}
							store32(m.memory[int64(uint32(v1))+44:], uint32(i32(5)))
							v0 = i32(2)
							t51 := m._sql3lexer_next(v3 + i32(12))
							if t51 != i32(2) {
								goto l2
							}
							t52 := int64(load64(m.memory[int64(uint32(v3))+24:]))
							store64(m.memory[int64(uint32(v1))+48:], uint64(t52))
						}
					l15:
						v0 = i32(0)
						v1 = v3 + i32(12)
						t53 := m._sql3lexer_peek(v1)
						if t53 != i32(17) {
							goto l2
						}
						_ = m._sql3lexer_next(v1)
						goto l2
					}
					v0 = i32(0)
					if v2 == 0 {
						goto l0
					}
					store32(m.memory[uint32(v2):], uint32(i32(1)))
					goto l0
				}
			l6:
				t55 := m._sql3lexer_peek(v3 + i32(12))
				p2 = t55
			}
		l8:
			v0 = p2
			v9 = v4 + i32(16)
			v10 = v3 + i32(56)
		l24:
			{
				if uint32(v0) > uint32(i32(26)) {
					goto l16
				}
				if i32_shl(i32(1), v0)&i32(0x7600000) == 0 {
					goto l16
				}
				store32(m.memory[int64(uint32(v3))+32:], uint32(v9))
				v5 = v3 + i32(12)
				t56 := m._sql3lexer_peek(v5)
				v0 = t56
				t57 := m.Xmalloc(i32(48))
				v1 = t57
				if v1 == 0 {
					goto l3
				}
				{
					{
						{
							{
								var p58 int32
								if v0 == i32(21) {
									_ = m._sql3lexer_next(v5)
									v0 = i32(2)
									t60 := m._sql3lexer_next(v5)
									if t60 != i32(2) {
										goto l2
									}
									t61 := int64(load64(m.memory[int64(uint32(v3))+24:]))
									store64(m.memory[int64(uint32(v1))+4:], uint64(t61))
									t62 := m._sql3lexer_peek(v5)
									v5 = t62 - i32(22)
									if uint32(v5) > uint32(i32(4)) {
										goto l2
									}
									if i32_shr_u(i32(29), v5)&i32(1) == 0 {
										goto l2
									}
									t63 := int32(load32(m.memory[int64(uint32(v5<<2))+65928:]))
									p58 = t63
								} else {
									p58 = v0
								}
								switch p58 - i32(22) {
								case 0, 2:
									goto l17
								case 3:
									goto l19
								case 4:
									goto l20
								default:
									goto l18
								}
							}
						l19:
							v5 = v3 + i32(12)
							_ = m._sql3lexer_next(v5)
							v0 = i32(2)
							store32(m.memory[uint32(v1):], uint32(i32(2)))
							m._sql3parse_expression(v3+i32(40), v5)
							t65 := int64(load64(m.memory[int64(uint32(v3))+40:]))
							t66 := v1
							v12 = t65
							store64(m.memory[int64(uint32(t66))+28:], uint64(v12))
							if int32(v12) != 0 {
								goto l18
							}
							goto l2
						}
					l17:
						t67 := m._sql3lexer_next(v3 + i32(12))
						t68 := v1
						var p69 int32
						if t67 != i32(22) {
							p69 = 1
						}
						v7 = p69
						var p70 int32
						if v7 != 0 {
							p70 = i32(1)
						} else {
							t71 := m._sql3lexer_next(v3 + i32(12))
							if t71 != i32(23) {
								goto l3
							}
							p70 = i32(0)
						}
						store32(m.memory[uint32(t68):], uint32(p70))
						t72 := m._sql3lexer_next(v3 + i32(12))
						if t72 != i32(19) {
							goto l3
						}
					l21:
						{
							store64(m.memory[int64(uint32(v3))+48:], uint64(i64(0)))
							v0 = v3 + i32(12)
							t73 := m._sql3lexer_next(v0)
							if t73 != i32(2) {
								goto l3
							}
							t74 := int64(load64(m.memory[int64(uint32(v3))+24:]))
							store64(m.memory[int64(uint32(v3))+40:], uint64(t74))
							t75 := m._sql3lexer_peek(v0)
							if t75 == i32(34) {
								_ = m._sql3lexer_next(v0)
								t77 := m._sql3lexer_next(v0)
								if t77 != i32(2) {
									goto l3
								}
								t78 := int64(load64(m.memory[int64(uint32(v3))+24:]))
								store64(m.memory[int64(uint32(v3))+48:], uint64(t78))
							}
							v5 = v3 + i32(12)
							m._sql3parse_optionalorder(v5, v10)
							t79 := int32(load32(m.memory[int64(uint32(v1))+12:]))
							t80 := v1
							v11 = t79
							v0 = v11 + i32(1)
							store32(m.memory[int64(uint32(t80))+12:], uint32(v0))
							t81 := int32(load32(m.memory[int64(uint32(v1))+16:]))
							t82 := m._sql3_array_grow(t81, v0, i32(20))
							v6 = t82
							if v6 == 0 {
								goto l3
							}
							store32(m.memory[int64(uint32(v1))+16:], uint32(v6))
							v0 = v6 + v0*i32(20) - i32(20)
							t83 := int32(load32(m.memory[int64(uint32(v3))+56:]))
							store32(m.memory[int64(uint32(v0))+16:], uint32(t83))
							t84 := int64(load64(m.memory[int64(uint32(v3))+48:]))
							store64(m.memory[int64(uint32(v0))+8:], uint64(t84))
							t85 := int64(load64(m.memory[int64(uint32(v3))+40:]))
							store64(m.memory[uint32(v0):], uint64(t85))
							t86 := m._sql3lexer_peek(v5)
							v0 = t86
							var p87 int32
							if v0 == i32(37) {
								_ = m._sql3lexer_next(v5)
								if v7 != 0 {
									goto l3
								}
								m.memory[int64(uint32(v1))+24] = byte(i32(1))
								t89 := m._sql3lexer_peek(v5)
								p87 = t89
							} else {
								p87 = v0
							}
							if p87 == i32(18) {
								_ = m._sql3lexer_next(v3 + i32(12))
								goto l21
							}
						}
						if v11 != 0 {
							t91 := int32(m.memory[int64(uint32(v1))+24])
							if t91&i32(1) != 0 {
								goto l3
							}
						}
						v5 = v3 + i32(12)
						t92 := m._sql3lexer_next(v5)
						if t92 != i32(20) {
							goto l3
						}
						v0 = i32(2)
						t93 := m._sql3parse_optionalconflitclause(v5, v1+i32(20))
						if t93 == 0 {
							goto l18
						}
						goto l2
					}
				l20:
					v5 = v3 + i32(12)
					_ = m._sql3lexer_next(v5)
					t95 := m._sql3lexer_next(v5)
					if t95 != i32(23) {
						goto l3
					}
					v0 = i32(2)
					t96 := m._sql3lexer_next(v5)
					if t96 != i32(19) {
						goto l2
					}
					store32(m.memory[uint32(v1):], uint32(i32(3)))
				l22:
					{
						v5 = v3 + i32(12)
						t97 := m._sql3lexer_next(v5)
						if t97 != i32(2) {
							goto l2
						}
						t98 := int32(load32(m.memory[int64(uint32(v1))+36:]))
						t99 := v1
						v6 = t98 + i32(1)
						store32(m.memory[int64(uint32(t99))+36:], uint32(v6))
						t100 := int32(load32(m.memory[int64(uint32(v1))+40:]))
						t101 := m._sql3_array_grow(t100, v6, i32(8))
						v7 = t101
						if v7 == 0 {
							goto l2
						}
						store32(m.memory[int64(uint32(v1))+40:], uint32(v7))
						t102 := int64(load64(m.memory[int64(uint32(v3))+24:]))
						store64(m.memory[uint32(v7+v6<<3-i32(8)):], uint64(t102))
						t103 := m._sql3lexer_peek(v5)
						t104 := m._sql3lexer_next(v5)
						v7 = t104
						if t103 == i32(18) {
							goto l22
						}
					}
					if v7 != i32(20) {
						goto l2
					}
					t105 := m._sql3lexer_next(v5)
					if t105 != i32(42) {
						goto l2
					}
					t106 := m._sql3parse_foreignkey_clause(v5)
					v5 = t106
					if v5 == 0 {
						goto l2
					}
					store32(m.memory[int64(uint32(v1))+44:], uint32(v5))
				}
			l18:
				t107 := int32(load32(m.memory[int64(uint32(v4))+36:]))
				t108 := v4
				v0 = t107 + i32(1)
				store32(m.memory[int64(uint32(t108))+36:], uint32(v0))
				t109 := int32(load32(m.memory[int64(uint32(v4))+40:]))
				t110 := m._sql3_array_grow(t109, v0, i32(4))
				v5 = t110
				if v5 == 0 {
					t111 := int32(load32(m.memory[int64(uint32(v4))+36:]))
					store32(m.memory[int64(uint32(v4))+36:], uint32(t111-i32(1)))
					v0 = i32(1)
					goto l2
				}
				store32(m.memory[int64(uint32(v4))+40:], uint32(v5))
				v0 = i32(2)
				t112 := int32(load32(m.memory[int64(uint32(v4))+36:]))
				store32(m.memory[uint32(v5+t112<<2-i32(4)):], uint32(v1))
				{
					t113 := m._sql3lexer_peek(v3 + i32(12))
					switch t113 - i32(18) {
					case 0:
						goto l23
					case 2:
						goto l16
					default:
						goto l2
					}
				}
			l23:
				v0 = v3 + i32(12)
				_ = m._sql3lexer_next(v0)
				t115 := m._sql3lexer_peek(v0)
				v0 = t115
				goto l24
			}
		l16:
			v0 = i32(2)
			t116 := m._sql3lexer_next(v3 + i32(12))
			if t116 != i32(20) {
				goto l2
			}
			store32(m.memory[int64(uint32(v3))+32:], uint32(v9))
		l29:
			{
				{
					{
						{
							t117 := m._sql3lexer_peek(v3 + i32(12))
							switch t117 - i32(12) {
							case 0:
								goto l25
							case 2:
								goto l27
							default:
								goto l26
							}
						}
					l25:
						v1 = v3 + i32(12)
						_ = m._sql3lexer_next(v1)
						t119 := m._sql3lexer_next(v1)
						if t119 != i32(13) {
							goto l2
						}
						t120 := int32(load32(m.memory[int64(uint32(v3))+36:]))
						m.memory[int64(uint32(t120))+26] = byte(i32(1))
						goto l28
					}
				l27:
					_ = m._sql3lexer_next(v3 + i32(12))
					t122 := int32(load32(m.memory[int64(uint32(v3))+36:]))
					m.memory[int64(uint32(t122))+27] = byte(i32(1))
				}
			l28:
				v1 = v3 + i32(12)
				t123 := m._sql3lexer_peek(v1)
				if t123 != i32(18) {
					goto l26
				}
				_ = m._sql3lexer_next(v1)
				goto l29
			}
		l26:
			v0 = i32(0)
			v1 = v3 + i32(12)
			t125 := m._sql3lexer_peek(v1)
			if t125 != i32(17) {
				goto l2
			}
			_ = m._sql3lexer_next(v1)
			goto l2
		}
	l3:
		v0 = i32(2)
	l2:
		if v2 != 0 {
			store32(m.memory[uint32(v2):], uint32(v0))
		}
		p127 := v8
		if v0 != 0 {
			p127 = i32(0)
		}
		v0 = p127
	}
l0:
	m.___stack_pointer = v3 - i32(-64)
	return v0
}
func (m *Module) _sql3lexer_next(v0 int32) int32 {
	var v1, v2, v3, v4, v5, v6, v7, v8, v9 int32
l4:
	{
		t0 := int32(load32(m.memory[int64(uint32(v0))+8:]))
		v4 = t0
		t1 := int32(load32(m.memory[int64(uint32(v0))+4:]))
		t2 := v4
		v8 = t1
		if uint32(t2) >= uint32(v8) {
			return i32(0)
		}
		{
			t3 := int32(load32(m.memory[uint32(v0):]))
			v5 = t3
			v1 = v5 + v4
			t4 := int32(m.memory[uint32(v1)])
			v2 = t4
			switch v2 {
			case 0:
				goto l0
			case 1, 2, 3, 4, 5, 6, 7, 8:
				goto l1
			case 9, 10, 11, 12, 13:
				goto l2
			default:
				goto l3
			}
		}
	l3:
		if v2 != i32(32) {
			goto l1
		}
	l2:
		store32(m.memory[int64(uint32(v0))+8:], uint32(v4+i32(1)))
		goto l4
	l1:
		t5 := m._symbol_is_comment(v2, v0)
		if t5 != 0 {
			m._sql3lexer_comment(v0)
			goto l4
		}
	}
	v3 = v2 - i32(40)
	if uint32(v3) > uint32(i32(19)) {
		goto l5
	}
	if i32_shl(i32(1), v3)&i32(524371) == 0 {
		goto l5
	}
	store32(m.memory[int64(uint32(v0))+8:], uint32(v4+i32(1)))
	v2 = i32(18)
	{
		t6 := int32(m.memory[uint32(v1)])
		v0 = t6
		switch v0 - i32(40) {
		case 0:
			goto l6
		case 1:
			goto l7
		case 2, 3, 5:
			goto l8
		case 4:
			goto l0
		case 6:
			goto l9
		default:
			goto l10
		}
	}
l9:
	return i32(16)
l6:
	return i32(19)
l7:
	return i32(20)
l10:
	if v0 == i32(59) {
		goto l11
	}
	goto l8
l5:
	{
		if v2 != i32(95) {
			if uint32((v2|i32(32)-i32(97))&i32(255)) > uint32(i32(25)) {
				goto l12
			}
		}
		v3 = i32(0)
	l15:
		v2 = i32(0)
		v5 = v3 + v4
		if uint32(v5) < uint32(v8) {
			t7 := int32(m.memory[uint32(v1+v3)])
			v2 = t7
		}
		v6 = v2 - i32(48)
		v7 = v2 | i32(32)
		if v2&i32(255) == i32(95) {
			goto l13
		}
		if uint32(v6&i32(255)) < uint32(i32(10)) {
			goto l13
		}
		if uint32((v7-i32(97))&i32(255)) > uint32(i32(25)) {
			goto l14
		}
	l13:
		store32(m.memory[int64(uint32(v0))+8:], uint32(v5+i32(1)))
		v3 = v3 + i32(1)
		goto l15
	l14:
		{
			{
				{
					{
						{
							{
								{
									{
										{
											{
												switch v3 - i32(2) {
												case 0:
													goto l16
												case 1:
													goto l17
												case 2:
													goto l18
												case 3:
													goto l19
												case 4:
													goto l20
												case 5:
													goto l21
												case 6:
													goto l22
												case 7:
													goto l23
												case 8:
													goto l24
												case 11:
													goto l26
												default:
													goto l25
												}
											l16:
												t8 := m._str_nocasencmp(v1, i32(65752), i32(2))
												if t8 == 0 {
													return i32(9)
												}
												t9 := m._str_nocasencmp(v1, i32(65695), i32(2))
												if t9 == 0 {
													return i32(27)
												}
												t10 := m._str_nocasencmp(v1, i32(65688), i32(2))
												if t10 == 0 {
													return i32(50)
												}
												t11 := m._str_nocasencmp(v1, i32(65666), i32(2))
												if t11 == 0 {
													return i32(15)
												}
												t12 := m._str_nocasencmp(v1, i32(65685), i32(2))
												if t12 != 0 {
													goto l25
												}
												return i32(62)
											}
										l17:
											t13 := m._str_nocasencmp(v1, i32(65582), i32(3))
											if t13 == 0 {
												return i32(10)
											}
											t14 := m._str_nocasencmp(v1, i32(65564), i32(3))
											if t14 == 0 {
												return i32(23)
											}
											t15 := m._str_nocasencmp(v1, i32(65889), i32(3))
											if t15 == 0 {
												return i32(35)
											}
											t16 := m._str_nocasencmp(v1, i32(65619), i32(3))
											if t16 == 0 {
												return i32(45)
											}
											t17 := m._str_nocasencmp(v1, i32(65880), i32(3))
											if t17 != 0 {
												goto l25
											}
											return i32(59)
										}
									l18:
										t18 := m._str_nocasencmp(v1, i32(65680), i32(4))
										if t18 == 0 {
											goto l27
										}
										t19 := m._str_nocasencmp(v1, i32(65884), i32(4))
										if t19 == 0 {
											return i32(36)
										}
										t20 := m._str_nocasencmp(v1, i32(65713), i32(4))
										if t20 == 0 {
											return i32(46)
										}
										t21 := m._str_nocasencmp(v1, i32(65718), i32(4))
										if t21 == 0 {
											return i32(31)
										}
										t22 := m._str_nocasencmp(v1, i32(65675), i32(4))
										if t22 != 0 {
											goto l25
										}
										return i32(60)
									}
								l19:
									t23 := m._str_nocasencmp(v1, i32(65815), i32(5))
									if t23 == 0 {
										return i32(8)
									}
									t24 := m._str_nocasencmp(v1, i32(65848), i32(5))
									if t24 == 0 {
										return i32(13)
									}
									t25 := m._str_nocasencmp(v1, i32(65731), i32(5))
									if t25 == 0 {
										return i32(25)
									}
									t26 := m._str_nocasencmp(v1, i32(65576), i32(5))
									if t26 == 0 {
										return i32(30)
									}
									t27 := m._str_nocasencmp(v1, i32(65746), i32(5))
									if t27 == 0 {
										return i32(52)
									}
									t28 := m._str_nocasencmp(v1, i32(65669), i32(5))
									if t28 != 0 {
										goto l25
									}
									return i32(57)
								}
							l20:
								v2 = i32(6)
								t29 := m._str_nocasencmp(v1, i32(65787), i32(6))
								if t29 == 0 {
									goto l0
								}
								t30 := m._str_nocasencmp(v1, i32(65648), i32(6))
								if t30 == 0 {
									return i32(11)
								}
								t31 := m._str_nocasencmp(v1, i32(65755), i32(6))
								if t31 == 0 {
									return i32(24)
								}
								t32 := m._str_nocasencmp(v1, i32(65801), i32(6))
								if t32 == 0 {
									return i32(32)
								}
								t33 := m._str_nocasencmp(v1, i32(65762), i32(6))
								if t33 == 0 {
									return i32(43)
								}
								t34 := m._str_nocasencmp(v1, i32(65794), i32(6))
								if t34 == 0 {
									return i32(44)
								}
								t35 := m._str_nocasencmp(v1, i32(65691), i32(6))
								if t35 == 0 {
									return i32(51)
								}
								t36 := m._str_nocasencmp(v1, i32(65625), i32(6))
								if t36 == 0 {
									return i32(14)
								}
								t37 := m._str_nocasencmp(v1, i32(65808), i32(6))
								if t37 == 0 {
									return i32(58)
								}
								t38 := m._str_nocasencmp(v1, i32(65698), i32(6))
								if t38 == 0 {
									return i32(61)
								}
								t39 := m._str_nocasencmp(v1, i32(65641), i32(6))
								if t39 == 0 {
									return i32(39)
								}
								t40 := m._str_nocasencmp(v1, i32(65873), i32(6))
								if t40 != 0 {
									goto l25
								}
								return i32(40)
							}
						l21:
							t41 := m._str_nocasencmp(v1, i32(65568), i32(7))
							if t41 == 0 {
								return i32(12)
							}
							t42 := m._str_nocasencmp(v1, i32(65546), i32(7))
							if t42 == 0 {
								return i32(22)
							}
							t43 := m._str_nocasencmp(v1, i32(65611), i32(7))
							if t43 == 0 {
								return i32(47)
							}
							t44 := m._str_nocasencmp(v1, i32(65769), i32(7))
							if t44 == 0 {
								return i32(34)
							}
							t45 := m._str_nocasencmp(v1, i32(65840), i32(7))
							if t45 == 0 {
								return i32(33)
							}
							t46 := m._str_nocasencmp(v1, i32(65832), i32(7))
							if t46 == 0 {
								return i32(48)
							}
							t47 := m._str_nocasencmp(v1, i32(65705), i32(7))
							if t47 == 0 {
								return i32(26)
							}
							t48 := m._str_nocasencmp(v1, i32(65723), i32(7))
							if t48 != 0 {
								goto l25
							}
							return i32(41)
						}
					l22:
						t49 := m._str_nocasencmp(v1, i32(65632), i32(8))
						if t49 == 0 {
							return i32(28)
						}
						t50 := m._str_nocasencmp(v1, i32(65737), i32(8))
						if t50 == 0 {
							return i32(29)
						}
						t51 := m._str_nocasencmp(v1, i32(65623), i32(8))
						if t51 == 0 {
							return i32(49)
						}
						t52 := m._str_nocasencmp(v1, i32(65864), i32(8))
						if t52 != 0 {
							goto l25
						}
						return i32(55)
					}
				l23:
					t53 := m._str_nocasencmp(v1, i32(65536), i32(9))
					if t53 == 0 {
						goto l27
					}
					t54 := m._str_nocasencmp(v1, i32(65554), i32(9))
					if t54 == 0 {
						return i32(54)
					}
					t55 := m._str_nocasencmp(v1, i32(65777), i32(9))
					if t55 == 0 {
						return i32(56)
					}
					t56 := m._str_nocasencmp(v1, i32(65854), i32(9))
					if t56 != 0 {
						goto l25
					}
					return i32(38)
				}
			l24:
				t57 := m._str_nocasencmp(v1, i32(65586), i32(10))
				if t57 == 0 {
					return i32(21)
				}
				t58 := m._str_nocasencmp(v1, i32(65655), i32(10))
				if t58 == 0 {
					return i32(42)
				}
				t59 := m._str_nocasencmp(v1, i32(65821), i32(10))
				if t59 != 0 {
					goto l25
				}
				return i32(53)
			}
		l26:
			t60 := m._str_nocasencmp(v1, i32(65597), i32(13))
			if t60 != 0 {
				goto l25
			}
			return i32(37)
		}
	l25:
		store32(m.memory[int64(uint32(v0))+16:], uint32(v3))
		store32(m.memory[int64(uint32(v0))+12:], uint32(v1))
		goto l28
	l12:
		if v2 == i32(34) {
			goto l29
		}
		if v2 == i32(39) {
			goto l29
		}
		if v2 == i32(96) {
			goto l29
		}
		if v2 != i32(91) {
			goto l8
		}
	l29:
		t61 := v0
		v3 = v4 + i32(1)
		store32(m.memory[int64(uint32(t61))+8:], uint32(v3))
		t62 := int32(m.memory[uint32(v1)])
		v2 = t62
		p63 := v2
		if v2 == i32(91) {
			p63 = i32(93)
		}
		v7 = p63
		v2 = v3
	l32:
		{
			{
				t64 := v8
				v1 = v2
				var p65 int32
				if uint32(t64) > uint32(v1) {
					t66 := v0
					v2 = v1 + i32(1)
					store32(m.memory[int64(uint32(t66))+8:], uint32(v2))
					t67 := int32(m.memory[uint32(v1+v5)])
					v6 = t67
					if v6 != 0 {
						goto l30
					}
					p65 = i32(0)
				} else {
					p65 = v6
				}
				if p65 != v7&i32(255) {
					goto l8
				}
				goto l31
			}
		l30:
			v9 = v7 & i32(255)
			if v9 != v6 {
				goto l32
			}
			if uint32(v2) >= uint32(v8) {
				goto l31
			}
			t68 := int32(m.memory[uint32(v2+v5)])
			if t68 != v9 {
				goto l31
			}
			t69 := v0
			v2 = v1 + i32(2)
			store32(m.memory[int64(uint32(t69))+8:], uint32(v2))
			goto l32
		}
	l31:
		store32(m.memory[int64(uint32(v0))+12:], uint32(v3+v5))
		store32(m.memory[int64(uint32(v0))+16:], uint32(v2-v4-i32(2)))
	}
l28:
	return i32(2)
l27:
	return i32(7)
l8:
	return i32(1)
l11:
	v2 = i32(17)
l0:
	return v2
}
func (m *Module) _sql3lexer_peek(v0 int32) int32 {
	var v1, v2, _ int32
	var v4, v5 int64
	t0 := int64(load64(m.memory[int64(uint32(v0))+12:]))
	v4 = t0
	t1 := int32(load32(m.memory[int64(uint32(v0))+8:]))
	v2 = t1
	t2 := int32(load32(m.memory[int64(uint32(v0))+20:]))
	v1 = t2
	var p3 int64
	if v1 != 0 {
		t4 := int64(load64(m.memory[uint32(v1):]))
		p3 = t4
	} else {
		p3 = i64(0)
	}
	v5 = p3
	t5 := m._sql3lexer_next(v0)
	store32(m.memory[int64(uint32(v0))+20:], uint32(v1))
	store64(m.memory[int64(uint32(v0))+12:], uint64(v4))
	store32(m.memory[int64(uint32(v0))+8:], uint32(v2))
	if v1 != 0 {
		store64(m.memory[uint32(v1):], uint64(v5))
	}
	return t5
}
func (m *Module) _sql3parse_schema_identifier(v0 int32) int32 {
	var v1, v2, v3, v4 int32
	t0 := int32(load32(m.memory[int64(uint32(v0))+24:]))
	v4 = t0
	{
		t1 := m._sql3lexer_next(v0)
		v1 = t1
		if v1 != i32(7) {
			v2 = i32(2)
			if v1 != i32(2) {
				goto l0
			}
		}
		v2 = i32(2)
		if v1 == i32(2) {
			t2 := int32(load32(m.memory[int64(uint32(v0))+12:]))
			if t2 == 0 {
				goto l0
			}
		}
		{
			t3 := m._sql3lexer_peek(v0)
			if t3 == i32(16) {
				_ = m._sql3lexer_next(v0)
				t5 := v4
				v3 = v0 + i32(12)
				p6 := v3
				if v1 != i32(2) {
					p6 = i32(65896)
				}
				t7 := int64(load64(m.memory[uint32(p6):]))
				store64(m.memory[int64(uint32(t5))+8:], uint64(t7))
				t8 := m._sql3lexer_next(v0)
				if t8 != i32(2) {
					goto l0
				}
				t9 := int32(load32(m.memory[uint32(v3):]))
				if t9 != 0 {
					goto l1
				}
				goto l0
			}
			p10 := v0 + i32(12)
			if v1 != i32(2) {
				p10 = i32(65896)
			}
			v3 = p10
		}
	l1:
		t11 := int64(load64(m.memory[uint32(v3):]))
		store64(m.memory[uint32(v4):], uint64(t11))
		v2 = i32(0)
	}
l0:
	return v2
}
func (m *Module) _sql3parse_column(v0 int32) int32 {
	var v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13 int32
	var v14 int64
	t0 := m.___stack_pointer
	v7 = t0 - i32(16)
	m.___stack_pointer = v7
	{
		t1 := m.Xmalloc(i32(148))
		v2 = t1
		if v2 == 0 {
			goto l0
		}
		store32(m.memory[int64(uint32(v0))+20:], uint32(v2+i32(24)))
		t2 := m._sql3lexer_next(v0)
		if t2 != i32(2) {
			goto l0
		}
		t3 := int64(load64(m.memory[int64(uint32(v0))+12:]))
		store64(m.memory[uint32(v2):], uint64(t3))
		{
			t4 := m._sql3lexer_peek(v0)
			if t4 != i32(2) {
				goto l1
			}
		l2:
			{
				t5 := m._sql3lexer_peek(v0)
				if t5 == i32(2) {
					_ = m._sql3lexer_next(v0)
					if v1 != 0 {
						goto l2
					}
					t7 := int32(load32(m.memory[int64(uint32(v0))+8:]))
					t8 := int32(load32(m.memory[int64(uint32(v0))+16:]))
					v1 = t7 - t8
					goto l2
				}
			}
			t9 := int32(load32(m.memory[int64(uint32(v0))+8:]))
			store32(m.memory[int64(uint32(v2))+12:], uint32(t9-v1))
			t10 := int32(load32(m.memory[uint32(v0):]))
			store32(m.memory[int64(uint32(v2))+8:], uint32(t10+v1))
			t11 := m._sql3lexer_peek(v0)
			if t11 != i32(19) {
				goto l1
			}
			_ = m._sql3lexer_next(v0)
			t13 := int32(load32(m.memory[int64(uint32(v0))+8:]))
			v5 = t13
			t14 := int32(load32(m.memory[int64(uint32(v0))+4:]))
			t15 := v5
			t16 := v5
			v1 = t14
			p17 := v1
			if uint32(v1) < uint32(v5) {
				p17 = t16
			}
			v3 = t15 - p17
			v1 = i32(0)
		l3:
			{
				if v1+v3 == 0 {
					goto l0
				}
				t18 := v0
				v6 = v1 + v5
				store32(m.memory[int64(uint32(t18))+8:], uint32(v6+i32(1)))
				t19 := int32(load32(m.memory[uint32(v0):]))
				t20 := v6
				v6 = t19
				t21 := int32(m.memory[uint32(t20+v6)])
				v8 = t21
				if v8 == 0 {
					goto l0
				}
				v1 = v1 + i32(1)
				if v8 != i32(41) {
					goto l3
				}
			}
			store32(m.memory[int64(uint32(v2))+20:], uint32(v1-i32(1)))
			store32(m.memory[int64(uint32(v2))+16:], uint32(v5+v6))
		}
	l1:
		{
			t22 := m._sql3lexer_peek(v0)
			v1 = t22
			t23 := int32(i64_shr_u(i64(0x844403608400), int64(uint32(v1))))
			var p24 int32
			if uint32(v1) < uint32(i32(48)) {
				p24 = 1
			}
			if t23&p24 == 0 {
				goto l4
			}
			v9 = v2 + i32(48)
			v10 = v2 + i32(44)
			v11 = v2 + i32(60)
			v12 = v2 + i32(72)
		l15:
			{
				t25 := m._sql3lexer_peek(v0)
				v1 = t25
				t26 := int32(i64_shr_u(i64(0x844403608400), int64(uint32(v1))))
				var p27 int32
				if uint32(v1) < uint32(i32(48)) {
					p27 = 1
				}
				if t26&p27 == 0 {
					goto l4
				}
				v14 = i64(0)
				t28 := m._sql3lexer_next(v0)
				v1 = t28
				if v1 == i32(21) {
					t29 := m._sql3lexer_next(v0)
					if t29 != i32(2) {
						v4 = i32(0)
						goto l0
					}
					t30 := int64(load64(m.memory[int64(uint32(v0))+12:]))
					v14 = t30
					t31 := m._sql3lexer_next(v0)
					v1 = t31
				}
				v4 = i32(0)
				var p32 int32
				{
					{
						{
							{
								{
									{
										{
											{
												{
													switch v1 - i32(22) {
													case 0:
														goto l5
													case 1:
														goto l0
													case 2:
														goto l6
													case 3:
														goto l7
													default:
														goto l8
													}
												l8:
													switch v1 - i32(38) {
													case 0:
														goto l9
													case 1, 2, 3:
														goto l0
													case 4:
														goto l10
													default:
														goto l11
													}
												l11:
													if v1 == i32(10) {
														goto l12
													}
													if v1 == i32(15) {
														goto l9
													}
													if v1 == i32(34) {
														goto l13
													}
													if v1 != i32(47) {
														goto l0
													}
													store64(m.memory[int64(uint32(v2))+84:], uint64(v14))
													t33 := m._sql3lexer_peek(v0)
													if t33 != i32(19) {
														goto l14
													}
													m._sql3parse_expression(v7+i32(8), v0)
													t34 := int64(load64(m.memory[int64(uint32(v7))+8:]))
													t35 := v2
													v14 = t34
													store64(m.memory[int64(uint32(t35))+92:], uint64(v14))
													if int32(v14) != 0 {
														goto l15
													}
													goto l0
												}
											l5:
												store64(m.memory[int64(uint32(v2))+36:], uint64(v14))
												t36 := m._sql3lexer_next(v0)
												if t36 != i32(23) {
													goto l0
												}
												m.memory[int64(uint32(v2))+32] = byte(i32(1))
												m._sql3parse_optionalorder(v0, v10)
												t37 := m._sql3parse_optionalconflitclause(v0, v9)
												if t37 != 0 {
													goto l0
												}
												t38 := m._sql3lexer_peek(v0)
												if t38 != i32(37) {
													goto l15
												}
												_ = m._sql3lexer_next(v0)
												m.memory[int64(uint32(v2))+33] = byte(i32(1))
												goto l15
											}
										l12:
											store64(m.memory[int64(uint32(v2))+52:], uint64(v14))
											t40 := m._sql3lexer_next(v0)
											if t40 != i32(46) {
												goto l0
											}
											m.memory[int64(uint32(v2))+34] = byte(i32(1))
											t41 := m._sql3parse_optionalconflitclause(v0, v11)
											if t41 == 0 {
												goto l15
											}
											goto l0
										}
									l7:
										t42 := int32(load32(m.memory[int64(uint32(v2))+76:]))
										t43 := v2
										v1 = t42 + i32(1)
										store32(m.memory[int64(uint32(t43))+76:], uint32(v1))
										t44 := int32(load32(m.memory[int64(uint32(v2))+80:]))
										t45 := m._sql3_array_grow(t44, v1, i32(16))
										v1 = t45
										if v1 == 0 {
											goto l0
										}
										store32(m.memory[int64(uint32(v2))+80:], uint32(v1))
										t46 := int32(load32(m.memory[int64(uint32(v2))+76:]))
										v1 = v1 + t46<<4
										store64(m.memory[uint32(v1-i32(16)):], uint64(v14))
										m._sql3parse_expression(v7+i32(8), v0)
										t47 := int64(load64(m.memory[int64(uint32(v7))+8:]))
										t48 := v1 - i32(8)
										v14 = t47
										store64(m.memory[uint32(t48):], uint64(v14))
										if int32(v14) != 0 {
											goto l15
										}
										goto l0
									}
								l14:
									m._sql3lexer_checkskip(v0)
									t49 := int32(load32(m.memory[uint32(v0):]))
									v5 = t49
									t50 := int32(load32(m.memory[int64(uint32(v0))+8:]))
									v8 = t50
									v1 = v8
									t51 := int32(load32(m.memory[int64(uint32(v0))+4:]))
									t52 := v1
									v3 = t51
									if uint32(t52) < uint32(v3) {
										t53 := v0
										v1 = v1 + i32(1)
										store32(m.memory[int64(uint32(t53))+8:], uint32(v1))
										t54 := int32(m.memory[uint32(v5+v8)])
										v6 = t54
										if v6 == i32(39) {
											goto l22
										}
										if v6 == i32(34) {
											goto l22
										}
									}
									p55 := v3
									if uint32(v1) > uint32(v3) {
										p55 = v1
									}
									v4 = p55
								l20:
									{
										if v1 == v4 {
											v1 = v4
											goto l17
										}
										t56 := int32(m.memory[uint32(v1+v5)])
										v3 = t56
										v6 = v3 - i32(9)
										var p58 int32
										if uint32(v6) <= uint32(i32(23)) {
											p58 = 1
										}
										p57 := i32(0)
										if i32_shl(i32(1), v6)&i32(8388639) != 0 {
											p57 = p58
										}
										if p57 != 0 {
											goto l17
										}
										switch v3 - i32(41) {
										case 0, 3:
											goto l17
										case 1, 2:
											goto l18
										default:
											goto l19
										}
									l19:
										if v3 == 0 {
											goto l17
										}
										if v3 == i32(59) {
											goto l17
										}
									l18:
										t59 := v0
										v1 = v1 + i32(1)
										store32(m.memory[int64(uint32(t59))+8:], uint32(v1))
										goto l20
									}
								}
							l6:
								m.memory[int64(uint32(v2))+35] = byte(i32(1))
								store64(m.memory[int64(uint32(v2))+64:], uint64(v14))
								t60 := m._sql3parse_optionalconflitclause(v0, v12)
								if t60 == 0 {
									goto l15
								}
								goto l0
							}
						l9:
							store64(m.memory[int64(uint32(v2))+128:], uint64(v14))
							if v1 == i32(38) {
								t61 := m._sql3lexer_next(v0)
								v1 = t61
								if v1 == i32(39) {
									t62 := m._sql3lexer_next(v0)
									v1 = t62
								}
								if v1 != i32(15) {
									goto l0
								}
							}
							t63 := m._sql3lexer_peek(v0)
							if t63 != i32(19) {
								goto l0
							}
							m._sql3parse_expression(v7+i32(8), v0)
							t64 := int64(load64(m.memory[int64(uint32(v7))+8:]))
							t65 := v2
							v14 = t64
							store64(m.memory[int64(uint32(t65))+136:], uint64(v14))
							if int32(v14) == 0 {
								goto l0
							}
							t66 := m._sql3lexer_peek(v0)
							v1 = t66
							store32(m.memory[int64(uint32(v2))+144:], uint32(i32(0)))
							if v1&i32(62) != i32(40) {
								goto l15
							}
							_ = m._sql3lexer_next(v0)
							t69 := v2
							p68 := i32(2)
							if v1 == i32(40) {
								p68 = i32(1)
							}
							store32(m.memory[int64(uint32(t69))+144:], uint32(p68))
							goto l15
						}
					l10:
						store64(m.memory[int64(uint32(v2))+116:], uint64(v14))
						t70 := m._sql3parse_foreignkey_clause(v0)
						v1 = t70
						if v1 == 0 {
							goto l0
						}
						store32(m.memory[int64(uint32(v2))+124:], uint32(v1))
						goto l15
					}
				l13:
					store64(m.memory[int64(uint32(v2))+100:], uint64(v14))
					t71 := m._sql3lexer_next(v0)
					if t71 != i32(2) {
						goto l0
					}
					t72 := int64(load64(m.memory[int64(uint32(v0))+12:]))
					store64(m.memory[int64(uint32(v2))+108:], uint64(t72))
					goto l15
				}
			l22:
				{
					if uint32(v1) >= uint32(v3) {
						goto l21
					}
					t73 := v0
					v4 = v1
					v1 = v4 + i32(1)
					store32(m.memory[int64(uint32(t73))+8:], uint32(v1))
					t74 := int32(m.memory[uint32(v4+v5)])
					v13 = t74
					if v13 == 0 {
						goto l21
					}
					if v6 != v13 {
						goto l22
					}
					if uint32(v1) >= uint32(v3) {
						goto l17
					}
					t75 := int32(m.memory[uint32(v1+v5)])
					if v6 != t75 {
						goto l17
					}
					t76 := v0
					v1 = v4 + i32(2)
					store32(m.memory[int64(uint32(t76))+8:], uint32(v1))
					goto l22
				}
			l21:
				v3 = i32(0)
				if v6 != 0 {
					p32 = i32(0)
					goto l23
				}
			l17:
				v3 = v1 - v8
				p32 = v5 + v8
			l23:
				v4 = p32
				store32(m.memory[int64(uint32(v2))+96:], uint32(v3))
				store32(m.memory[int64(uint32(v2))+92:], uint32(v4))
				goto l15
			}
		}
	l4:
		v4 = v2
	}
l0:
	m.___stack_pointer = v7 + i32(16)
	return v4
}
func (m *Module) _sql3_array_grow(v0, v1, v2 int32) int32 {
	var v3 int32
	if int32(bits.OnesCount32(uint32(v1))) == i32(1) {
		{
			p0 := v1 << 1
			if v1 == i32(1) {
				p0 = i32(1)
			}
			v2 = p0 * v2
			if v0 == 0 {
				t1 := m.Xmalloc(v2)
				v0 = t1
				goto l0
			}
			if uint32(v2) < uint32(i32(17)) {
				goto l0
			}
			t2 := int32(load32(m.memory[uint32(i32(65952)):]))
			v3 = t2 - v0
			if v3 == i32(16) {
				store32(m.memory[uint32(i32(65952)):], uint32(v0))
			}
			{
				t3 := m.Xmalloc(v2)
				v1 = t3
				if v1 == 0 {
					goto l1
				}
				if v0 == v1 {
					goto l1
				}
				p4 := v2
				if uint32(v2) > uint32(v3) {
					p4 = v3
				}
				v2 = p4
				if v2 == 0 {
					goto l1
				}
				memory_copy(m.memory, uint32(v1), uint32(v0), uint32(v2))
			}
		l1:
			v0 = v1
		}
	l0:
	}
	return v0
}
func (m *Module) _sql3parse_expression(v0, v1 int32) {
	var v2, v3, v4, v5, v6, v7, v8, v9, v10, v11 int32
	m._sql3lexer_checkskip(v1)
	{
		t0 := int32(load32(m.memory[int64(uint32(v1))+4:]))
		v4 = t0
		t1 := int32(load32(m.memory[int64(uint32(v1))+8:]))
		t2 := v4
		v8 = t1
		if uint32(t2) <= uint32(v8) {
			goto l0
		}
		t3 := v1
		v2 = v8 + i32(1)
		store32(m.memory[int64(uint32(t3))+8:], uint32(v2))
		t4 := int32(load32(m.memory[uint32(v1):]))
		t5 := v8
		v5 = t4
		v10 = t5 + v5
		t6 := int32(m.memory[uint32(v10)])
		if t6 != i32(40) {
			goto l0
		}
		v11 = i32(2) - v4
		v7 = i32(1)
	l2:
		v3 = v2
		if uint32(v2) < uint32(v4) {
			t7 := v1
			v2 = v2 + i32(1)
			store32(m.memory[int64(uint32(t7))+8:], uint32(v2))
			{
				{
					{
						t8 := int32(m.memory[uint32(v3+v5)])
						v6 = t8
						switch v6 - i32(34) {
						case 0, 5:
							goto l8
						case 1, 2, 3, 4, 8, 9, 10, 12:
							goto l2
						case 6:
							goto l3
						case 7:
							goto l4
						case 11:
							goto l5
						case 13:
							goto l6
						default:
							goto l7
						}
					}
				l8:
					{
						if uint32(v2) >= uint32(v4) {
							goto l2
						}
						t9 := v1
						v3 = v2
						v2 = v3 + i32(1)
						store32(m.memory[int64(uint32(t9))+8:], uint32(v2))
						t10 := int32(m.memory[uint32(v3+v5)])
						v9 = t10
						if v9 == 0 {
							goto l2
						}
						if v6 != v9 {
							goto l8
						}
						if uint32(v2) >= uint32(v4) {
							goto l2
						}
						t11 := int32(m.memory[uint32(v2+v5)])
						if t11 != v6 {
							goto l2
						}
						t12 := v1
						v2 = v3 + i32(2)
						store32(m.memory[int64(uint32(t12))+8:], uint32(v2))
						goto l8
					}
				l5:
					if uint32(v2) >= uint32(v4) {
						goto l2
					}
					t13 := int32(m.memory[uint32(v2+v5)])
					if t13 != i32(45) {
						goto l2
					}
				l11:
					{
						if v2 == v4 {
							goto l9
						}
						t14 := v1
						v3 = v2 + i32(1)
						store32(m.memory[int64(uint32(t14))+8:], uint32(v3))
						v6 = v2 + v5
						v2 = v3
						{
							t15 := int32(m.memory[uint32(v6)])
							v3 = t15
							switch v3 - i32(10) {
							case 0, 3:
								goto l10
							case 1, 2:
								goto l11
							default:
								goto l12
							}
						}
					l12:
						if v3 != 0 {
							goto l11
						}
					l10:
					}
					goto l2
				}
			l6:
				if uint32(v2) >= uint32(v4) {
					goto l2
				}
				t16 := int32(m.memory[uint32(v2+v5)])
				if t16 != i32(42) {
					goto l2
				}
				store32(m.memory[int64(uint32(v1))+8:], uint32(v3+i32(2)))
				v2 = v3 + i32(4)
			l14:
				{
					if v2+v11 == i32(4) {
						goto l9
					}
					t17 := v1
					v3 = v2 - i32(1)
					store32(m.memory[int64(uint32(t17))+8:], uint32(v3))
					{
						v6 = v2 + v5
						t18 := int32(m.memory[uint32(v6-i32(2))])
						v9 = t18
						if v9 != i32(42) {
							if v9 != 0 {
								goto l13
							}
							v2 = v3
							goto l2
						}
						if uint32(v3) >= uint32(v4) {
							goto l13
						}
						t19 := int32(m.memory[uint32(v6-i32(1))])
						if t19 != i32(47) {
							goto l13
						}
						store32(m.memory[int64(uint32(v1))+8:], uint32(v2))
						goto l2
					}
				l13:
					v2 = v2 + i32(1)
					goto l14
				}
			}
		l4:
			v7 = v7 - i32(1)
			if v7 != 0 {
				goto l2
			}
			goto l15
		l7:
			if v6 != 0 {
				goto l2
			}
		}
		if v7 == 0 {
			goto l15
		}
		store64(m.memory[uint32(v0):], uint64(i64(0)))
		return
	l15:
		store32(m.memory[uint32(v0):], uint32(v10))
		store32(m.memory[int64(uint32(v0))+4:], uint32(v2-v8))
		return
	l3:
		v7 = v7 + i32(1)
		goto l2
	l9:
		v2 = v4
		goto l2
	}
l0:
	store64(m.memory[uint32(v0):], uint64(i64(0)))
}
func (m *Module) _sql3parse_optionalorder(v0, v1 int32) {
	var v2 int32
	t0 := m._sql3lexer_peek(v0)
	v2 = t0
	store32(m.memory[uint32(v1):], uint32(i32(0)))
	if uint32(v2-i32(35)) <= uint32(i32(1)) {
		_ = m._sql3lexer_next(v0)
		t3 := v1
		p2 := i32(2)
		if v2 == i32(35) {
			p2 = i32(1)
		}
		store32(m.memory[uint32(t3):], uint32(p2))
	}
}
func (m *Module) _sql3parse_optionalconflitclause(v0, v1 int32) int32 {
	var v2, v3 int32
	t0 := m._sql3lexer_peek(v0)
	v3 = t0
	store32(m.memory[uint32(v1):], uint32(i32(0)))
	{
		if v3 != i32(27) {
			goto l0
		}
		_ = m._sql3lexer_next(v0)
		v2 = i32(2)
		t2 := m._sql3lexer_next(v0)
		if t2 != i32(28) {
			goto l0
		}
		t3 := m._sql3lexer_next(v0)
		v0 = t3
		if uint32(v0-i32(29)) > uint32(i32(4)) {
			goto l0
		}
		store32(m.memory[uint32(v1):], uint32(v0-i32(28)))
		v2 = i32(0)
	}
l0:
	return v2
}
func (m *Module) _sql3parse_foreignkey_clause(v0 int32) int32 {
	var v1, v2, v3 int32
	{
		t0 := m.Xmalloc(i32(36))
		v1 = t0
		if v1 == 0 {
			goto l0
		}
		t1 := m._sql3lexer_next(v0)
		if t1 != i32(2) {
			goto l0
		}
		t2 := int64(load64(m.memory[int64(uint32(v0))+12:]))
		store64(m.memory[uint32(v1):], uint64(t2))
		t3 := m._sql3lexer_peek(v0)
		if t3 == i32(19) {
			_ = m._sql3lexer_next(v0)
		l1:
			{
				t5 := m._sql3lexer_next(v0)
				if t5 != i32(2) {
					goto l0
				}
				t6 := int32(load32(m.memory[int64(uint32(v1))+8:]))
				t7 := v1
				v2 = t6 + i32(1)
				store32(m.memory[int64(uint32(t7))+8:], uint32(v2))
				t8 := int32(load32(m.memory[int64(uint32(v1))+12:]))
				t9 := m._sql3_array_grow(t8, v2, i32(8))
				v3 = t9
				if v3 == 0 {
					goto l0
				}
				store32(m.memory[int64(uint32(v1))+12:], uint32(v3))
				t10 := int64(load64(m.memory[int64(uint32(v0))+12:]))
				store64(m.memory[uint32(v3+v2<<3-i32(8)):], uint64(t10))
				t11 := m._sql3lexer_peek(v0)
				t12 := m._sql3lexer_next(v0)
				v3 = t12
				if t11 == i32(18) {
					goto l1
				}
			}
			if v3 != i32(20) {
				goto l0
			}
		}
	l4:
		{
			{
				t13 := m._sql3lexer_peek(v0)
				v3 = t13
				v2 = v3 - i32(27)
				var p15 int32
				if uint32(v2) <= uint32(i32(26)) {
					p15 = 1
				}
				p14 := i32(0)
				if i32_shl(i32(1), v2)&i32(0x6000001) != 0 {
					p14 = p15
				}
				if p14 != 0 {
					goto l2
				}
				if v3 == i32(10) {
					goto l2
				}
				return v1
			}
		l2:
			_ = m._sql3lexer_next(v0)
			var p17 int32
			{
				if v3 != i32(10) {
					if v3 != i32(27) {
						if v3 != i32(52) {
							p17 = i32(0)
							goto l3
						}
						t18 := m._sql3lexer_next(v0)
						if t18 != i32(2) {
							goto l0
						}
						t19 := int64(load64(m.memory[int64(uint32(v0))+12:]))
						store64(m.memory[int64(uint32(v1))+24:], uint64(t19))
						goto l4
					}
					t20 := m._sql3lexer_next(v0)
					v2 = t20
					if uint32(v2-i32(45)) < uint32(i32(-2)) {
						goto l0
					}
					{
						{
							t21 := m._sql3lexer_next(v0)
							switch t21 - i32(45) {
							case 0:
								goto l5
							case 3:
								goto l6
							case 4:
								goto l7
							case 5:
								goto l8
							default:
								goto l0
							}
						}
					l6:
						if v2 == i32(44) {
							store32(m.memory[int64(uint32(v1))+20:], uint32(i32(3)))
							goto l4
						}
						store32(m.memory[int64(uint32(v1))+16:], uint32(i32(3)))
						goto l4
					l7:
						if v2 == i32(44) {
							store32(m.memory[int64(uint32(v1))+20:], uint32(i32(4)))
							goto l4
						}
						store32(m.memory[int64(uint32(v1))+16:], uint32(i32(4)))
						goto l4
					l5:
						t22 := m._sql3lexer_next(v0)
						v3 = t22
						if uint32(v3-i32(48)) < uint32(i32(-2)) {
							goto l0
						}
						if v3 == i32(46) {
							if v2 == i32(44) {
								store32(m.memory[int64(uint32(v1))+20:], uint32(i32(1)))
								goto l4
							}
							store32(m.memory[int64(uint32(v1))+16:], uint32(i32(1)))
							goto l4
						}
						if v2 == i32(44) {
							store32(m.memory[int64(uint32(v1))+20:], uint32(i32(2)))
							goto l4
						}
						store32(m.memory[int64(uint32(v1))+16:], uint32(i32(2)))
						goto l4
					}
				l8:
					t23 := m._sql3lexer_next(v0)
					if t23 != i32(51) {
						goto l0
					}
					if v2 == i32(44) {
						store32(m.memory[int64(uint32(v1))+20:], uint32(i32(5)))
						goto l4
					}
					store32(m.memory[int64(uint32(v1))+16:], uint32(i32(5)))
					goto l4
				}
				t24 := m._sql3lexer_next(v0)
				v3 = t24
				p17 = i32(1)
			}
		l3:
			v2 = p17
			if v3 != i32(53) {
				goto l0
			}
			t26 := v1
			p25 := i32(1)
			if v2 != 0 {
				p25 = i32(4)
			}
			store32(m.memory[int64(uint32(t26))+32:], uint32(p25))
			t27 := m._sql3lexer_peek(v0)
			if t27 != i32(54) {
				goto l4
			}
			_ = m._sql3lexer_next(v0)
			{
				{
					t29 := m._sql3lexer_next(v0)
					switch t29 - i32(55) {
					case 0:
						goto l9
					case 1:
						goto l10
					default:
						goto l0
					}
				}
			l9:
				t31 := v1
				p30 := i32(2)
				if v2 != 0 {
					p30 = i32(5)
				}
				store32(m.memory[int64(uint32(t31))+32:], uint32(p30))
				goto l4
			}
		l10:
			t33 := v1
			p32 := i32(3)
			if v2 != 0 {
				p32 = i32(6)
			}
			store32(m.memory[int64(uint32(t33))+32:], uint32(p32))
			goto l4
		}
	}
l0:
	return i32(0)
}
func (m *Module) _symbol_is_comment(v0, v1 int32) int32 {
	var v2 int32
	{
		{
			switch v0 - i32(45) {
			case 0:
				goto l0
			case 2:
				goto l2
			default:
				goto l1
			}
		l0:
			v0 = i32(1)
			t0 := int32(load32(m.memory[int64(uint32(v1))+8:]))
			v2 = t0 + i32(1)
			t1 := int32(load32(m.memory[int64(uint32(v1))+4:]))
			if uint32(v2) >= uint32(t1) {
				goto l1
			}
			t2 := int32(load32(m.memory[uint32(v1):]))
			t3 := int32(m.memory[uint32(t2+v2)])
			if t3 != i32(45) {
				goto l1
			}
			goto l3
		}
	l2:
		v0 = i32(1)
		t4 := int32(load32(m.memory[int64(uint32(v1))+8:]))
		v2 = t4 + i32(1)
		t5 := int32(load32(m.memory[int64(uint32(v1))+4:]))
		if uint32(v2) >= uint32(t5) {
			goto l1
		}
		t6 := int32(load32(m.memory[uint32(v1):]))
		t7 := int32(m.memory[uint32(t6+v2)])
		if t7 == i32(42) {
			goto l3
		}
	}
l1:
	v0 = i32(0)
l3:
	return v0
}
func (m *Module) _sql3lexer_comment(v0 int32) {
	var v1, v2, v3, v4, v5, v6, v7, v8, v9, v10 int32
	t0 := int32(load32(m.memory[uint32(v0):]))
	v6 = t0
	var p1 int32
	{
		t2 := int32(load32(m.memory[int64(uint32(v0))+4:]))
		v7 = t2
		t3 := int32(load32(m.memory[int64(uint32(v0))+8:]))
		t4 := v7
		v1 = t3
		if uint32(t4) <= uint32(v1) {
			v3 = v1
			p1 = i32(0)
			goto l0
		}
		t5 := v0
		v3 = v1 + i32(1)
		store32(m.memory[int64(uint32(t5))+8:], uint32(v3))
		t6 := int32(m.memory[uint32(v1+v6)])
		var p7 int32
		if t6 == i32(47) {
			p7 = 1
		}
		p1 = p7
	}
l0:
	v4 = p1
	{
		if uint32(v3) >= uint32(v7) {
			v1 = v3
			goto l1
		}
		t8 := v0
		v1 = v3 + i32(1)
		store32(m.memory[int64(uint32(t8))+8:], uint32(v1))
		t9 := int32(m.memory[uint32(v3+v6)])
		var p10 int32
		if t9 == i32(42) {
			p10 = 1
		}
		v2 = p10
	}
l1:
	p11 := v7
	if uint32(v1) > uint32(v7) {
		p11 = v1
	}
	v3 = p11
	v10 = v1 + v6
	v8 = v2 & v4
	v2 = v1
l3:
	{
		t12 := v3
		v4 = v2
		if t12 == v4 {
			v2 = v3
			v5 = i32(1)
			goto l2
		}
		t13 := v0
		v2 = v4 + i32(1)
		store32(m.memory[int64(uint32(t13))+8:], uint32(v2))
		v5 = v4 + v6
		t14 := int32(m.memory[uint32(v5)])
		v9 = t14
		if v9 != 0 {
			if v8 != 0 {
				if uint32(v2) >= uint32(v7) {
					goto l3
				}
				if v9 != i32(42) {
					goto l3
				}
				t15 := int32(m.memory[int64(uint32(v5))+1])
				if t15 != i32(47) {
					goto l3
				}
				t16 := v0
				v2 = v4 + i32(2)
				store32(m.memory[int64(uint32(t16))+8:], uint32(v2))
				v5 = i32(0)
				goto l2
			}
			v5 = i32(0)
			switch v9 - i32(10) {
			case 0, 3:
				goto l2
			default:
				goto l3
			}
		}
	}
	v5 = i32(1)
	v2 = v4 + i32(1)
l2:
	t17 := int32(load32(m.memory[int64(uint32(v0))+20:]))
	v0 = t17
	if v0 != 0 {
		store32(m.memory[uint32(v0):], uint32(v10))
		t19 := v0
		p18 := i32(-1)
		if v8 != 0 {
			p18 = i32(-2)
		}
		p20 := p18
		if v5 != 0 {
			p20 = i32(0)
		}
		store32(m.memory[int64(uint32(t19))+4:], uint32(p20-v1+v2))
	}
}
func (m *Module) _str_nocasencmp(v0, v1, v2 int32) int32 {
	var v3, v4, v5, v6 int32
l1:
	{
		if v2 == 0 {
			goto l0
		}
		t0 := int32(m.memory[uint32(v0)])
		v4 = t0
		p1 := v4
		if uint32((v4-i32(65))&i32(255)) < uint32(i32(26)) {
			p1 = v4 | i32(32)
		}
		v5 = p1
		t2 := int32(m.memory[uint32(v1)])
		t3 := v5
		v3 = t2
		p4 := v3
		if uint32((v3-i32(65))&i32(255)) < uint32(i32(26)) {
			p4 = v3 | i32(32)
		}
		v3 = p4
		if t3 == v3 {
			if v4 == 0 {
				goto l0
			}
			v2 = v2 - i32(1)
			v1 = v1 + i32(1)
			v0 = v0 + i32(1)
			goto l1
		}
	}
	v6 = v5 - v3
l0:
	return v6
}
func (m *Module) _sql3lexer_checkskip(v0 int32) {
	var v1, v2, v3 int32
l1:
	{
		v1 = i32(0)
		{
			t0 := int32(load32(m.memory[int64(uint32(v0))+8:]))
			v2 = t0
			t1 := int32(load32(m.memory[int64(uint32(v0))+4:]))
			if uint32(v2) >= uint32(t1) {
				goto l0
			}
			t2 := int32(load32(m.memory[uint32(v0):]))
			t3 := int32(m.memory[uint32(t2+v2)])
			v1 = t3
			v3 = v1 - i32(9)
			if uint32(v3) > uint32(i32(23)) {
				goto l0
			}
			if i32_shl(i32(1), v3)&i32(8388639) == 0 {
				goto l0
			}
			store32(m.memory[int64(uint32(v0))+8:], uint32(v2+i32(1)))
			goto l1
		}
	l0:
		t4 := m._symbol_is_comment(v1, v0)
		if t4 != 0 {
			m._sql3lexer_comment(v0)
			goto l1
		}
	}
}
func (m *Module) Xmemory() Memory {
	return (*wasmMemory)(&m.memory)
}

//go:nosplit
func i32(x int32) int32 { return x }

//go:nosplit
func i64(x int64) int64 { return x }

//go:nosplit
func i32_shl(x, y int32) int32 {
	return x << (y & 31)
}

//go:nosplit
func i32_shr_u(x, y int32) int32 {
	return int32(uint32(x) >> (y & 31))
}

//go:nosplit
func i64_shr_u(x, y int64) int64 {
	return int64(uint64(x) >> (y & 63))
}

//go:nosplit
func load32(b []byte) uint32 {
	return binary.LittleEndian.Uint32(b)
}

//go:nosplit
func store32(b []byte, v uint32) {
	binary.LittleEndian.PutUint32(b, v)
}

//go:nosplit
func load64(b []byte) uint64 {
	return binary.LittleEndian.Uint64(b)
}

//go:nosplit
func store64(b []byte, v uint64) {
	binary.LittleEndian.PutUint64(b, v)
}

func memory_grow(mem *[]byte, delta, max int64) int64 {
	buf := *mem
	len := int64(len(buf))
	old := len >> 16
	if delta == 0 {
		return old
	}
	new := old + delta
	add := new<<16 - len
	max = min(max, int64(math.MaxInt)>>16)
	if new > max || new < old || add < 0 {
		return -1
	}
	*mem = append(buf, make([]byte, add)...)
	return old
}

func memory_init[T1, T2 int | uint32 | uint64](mem []byte, data string, dest T1, src, n T2) {
	x := uint64(dest)
	z := uint64(src)
	y := x + uint64(n)
	w := z + uint64(n)
	copy(mem[x:y], data[z:w])
}

func memory_copy[T uint32 | uint64](mem []byte, dest, src, n T) {
	x := uint64(dest)
	z := uint64(src)
	y := x + uint64(n)
	w := z + uint64(n)
	copy(mem[x:y], mem[z:w])
}

const data0 = "temporary\x00primary\x00initially\x00key\x00without\x00abort\x00not\x00constraint\x00autoincrement\x00default\x00set\x00restrict\x00conflict\x00always\x00exists\x00references\x00as\x00alter\x00drop\x00temp\x00to\x00no\x00action\x00column\x00foreign\x00null\x00fail\x00virtual\x00check\x00rollback\x00match\x00if\x00unique\x00delete\x00collate\x00immediate\x00create\x00update\x00ignore\x00rename\x00table\x00deferrable\x00cascade\x00replace\x00rowid\x00generated\x00deferred\x00stored\x00add\x00desc\x00asc\x00\x00\x00\x00\x90\x00\x01\x00\x04\x00\x00\x00\x15\x00\x00\x00\x16\x00\x00\x00\x00\x00\x00\x00\x18\x00\x00\x00\x19\x00\x00\x00\x1a\x00\x00\x00\x16\x00\x00\x00\x00\x00\x00\x00\x18\x00\x00\x00\x19\x00\x00\x00\x1a\x00\x00\x00\x00\x00\x02\x00\xb0\x01\x01"
