name: Reproducible build

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6

    - name: Build
      shell: bash
      run: .github/workflows/repro.sh

    - uses: actions/attest-build-provenance@v4
      if: matrix.os == 'ubuntu-latest'
      with:
        subject-path: |
          sqlite3.go
          sqlite3.dat
          fts5/fts5.go
          fts5/fts5.dat
          rtree/rtree.go
          rtree/rtree.dat
          spellfix/spellfix.go
          spellfix/spellfix.dat
          vec1/vec1.go
          vec1/vec1.dat
          parser/parser.go
